base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.opi.feature.eclipse/feature.xml
build/build.sh

See ISISComputingGroup/IBEX#1074
This makes Tycho build both a Win32 and a Linux client, regardless what platform the build is run on.
Also added a build.sh script to allow building directly on Linux. Works the same way build.bat does on Windows.

Client build on Linux

---

base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/SynopticDescription.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/component/ComponentDetailView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/EditSynopticDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/InstrumentTreeView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/model/SynopticViewModel.java

To test:
* Trying to create or edit a synoptic with duplicated components stops you from saving it, giving a clear error message
* Adding a synoptic gives the synoptic a unique name (try adding children as well as top level components)
* Copying components gives the copied component and all children unique names (try breaking it by doing things like selecting multiple components to copy)
Old synoptics should work as they did before, but will not be able to be saved until the unique names are removed. On Larmor for example 'Sample Stack' is duplicated.

Ticket1055 synoptic component name duplication

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/DaeView.java

If the reference "Boolean" type is used, the object it points to may be gone (i.e. null) by the time the async execute is performed (i.e. this ticket). Using the primitive type avoids this issue (though potentially forces the execution to be performed synchronously).
To test, run the workflow described in ticket 1112:
Open IBEX
Change instrument to "Demo"
Change to the DAE perspective
Click "Begin Run"
Close the application
https://github.com/ISISComputingGroup/IBEX/issues/1112

Use primitive rather than reference type

---

base/uk.ac.stfc.isis.ibex.instrument.tests/src/uk/ac/stfc/isis/ibex/instrument/list/tests/InstrumentListUtilsTest.java
base/uk.ac.stfc.isis.ibex.instrument/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/list/InstrumentListObservable.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/list/InstrumentListUtils.java

The Instrument list is now in a PV called CS:INSTLIST, a json string compressed and hexed.
To test this story, check that the list of instruments in the GUI (IBEX > Switch Instrument) matches those in the PV and is updated without closing the GUI when the PV changes, e.g. with a caput (you do have to close and re-open the Instrument selection dialog though).
In case of parsing error of the json string, the client shouldn't crash:
a. if the error affects a single instrument (e.g. "name" spelled wrong), that instrument does not appear in the list
b. if the error affects the entire string (e.g. missing brackets at the start), no instrument is displayed
We can discuss whether an error message should be displayed, but I suggest doing the work in another ticket, as the dialog has changed in the …

Ticket1092 configurable instrument names

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/IocSimulationCellDecorator.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/IocsTable.java

Resource leak was caused by many Fonts being created and not disposed within the IOCs table each time a property changed was fired by the editable configuration.
To test:
Try to create a new configuration, adding 30+ groups. The client shouldn't crash anymore.
(The issue was appearing when any property change was fired, so actions like adding/removing/renaming/swapping blocks and groups was contributing to the leak).
NOTE: there is now an RCPTT System Test to cover this, see pull request ISISComputingGroup/ibex_system_tests#1

Ticket 1147: resource leak when creating many groups

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/DaeView.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/VerticalGradientComposite.java

User can now switch between tabs in DAE Experiment Setup at any time (i.e. whether the instrument is running or not), but the panels inside the tabs are disabled when the instrument is running.
As part of this, I have fixed a bug introduced in the last sprint, that caused the tabs to be enabled when the instrument was running!
See also corresponding pull request for system tests ISISComputingGroup/ibex_system_tests#4
To be able to run an instrument, you need to have valid wiring/detector/spectra table files set in the DAE Experiment Setup -> Data Acquisition panel. Valid files (originally copied from NDXDEMO) can be found in this ticket's branch for the System Tests, under RCPTT_Tests\TestFiles\Tables

Ticket1193 enable dae tabs

---

mvn_user_settings.xml

In the maven user settings, we were accessing external resources via proxies. My understanding is these were necessary in the past to get to external resources but they are in fact now blocking it. I've deactivated the filters and the Maven build works as expected. Isabella has confirmed.

Ticket1228_Broken_target_platform

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsPanel.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/Utils.java

Start the Ibex GUI when the instrument is already running.
The DAE Time Channels tables and their title labels are now greyed out (i.e. they look exactly the same as when the instrument run is started while the Ibex GUI is running)

Ticket1252 dae time channels not greyed out

---

base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/internal/Variables.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/SaveSynopticDialog.java

IMPORTANT: This ticket can be reviewed but NOT merged until the corresponding changes in the blockserver have been deployed to the instruments.
For the changes in the blockserver see pull request: ISISComputingGroup/EPICS-inst_servers#43
The blockserver has been changed so that any PV related to synoptics has prefix IN:DEMO:CS:SYNOPTICS: instead of IN:DEMO:CS:BLOCKSERVER:SYNOPTICS:
Test that the new blockserver publishes PVs under the new names.
The change involved refactoring the way the configuration PV names and BlockRules PV names are generated: check that the same PVs still exist.
Following the changes in the blockserver, the GUI has been updated to expect the new PV names: test that the updated GUI can open/modify synoptics when the new blockserver is running.
Also, the GUI now …

Ticket1053 shorter synoptics pv names

---

base/uk.ac.stfc.isis.ibex.ui.perspectives/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.perspectives/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/BasePerspective.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/IsisPerspective.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/Perspectives.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/PreferencePage.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/switcher/PerspectiveSwitcherView.java

Added a preference page for visible perspectives (currently all default to visible)
As per https://github.com/ISISComputingGroup/IBEX/issues/1372
* Go to preference menu (Ctrl+Alt+P)
* Go to the ISIS Perspectives tab
* Modify the checkboxes to only display some perspectives
* Restart IBEX and confirm only expected perspectives are shown
---

Preference page for perspectives

---

base/uk.ac.stfc.isis.ibex.instrument.tests/src/uk/ac/stfc/isis/ibex/instrument/custom/tests/CustomInstrumentInfoTest.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/custom/CustomInstrumentInfo.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/internal/PVPrefix.java
base/uk.ac.stfc.isis.ibex.ui.mainmenu/src/uk/ac/stfc/isis/ibex/ui/mainmenu/instrument/InstrumentSelectionPanel.java
base/uk.ac.stfc.isis.ibex.ui.mainmenu/src/uk/ac/stfc/isis/ibex/ui/mainmenu/instrument/custom/CustomInstrumentPanel.java
base/uk.ac.stfc.isis.ibex.validators.tests/src/uk/ac/stfc/isis/ibex/validators/tests/InstrumentNameValidatorTest.java
base/uk.ac.stfc.isis.ibex.validators/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/InstrumentNameValidator.java

When switching instrument, the custom instrument name must now start with "ND" instead of "NDW".
Also added a help message under the instrument name text box and a help message for setting the PV prefix of the custom instrument info.
While doing this ticket I noticed that the validation message on the instrument name was too long and was getting cropped in the dialog, so I've split it into two shorter messages.
###To test
ISISComputingGroup/IBEX#1218
Open the Switch Instrument dialog. Verify that custom instrument names starting with "ND" are valid.
Check the usefulness of the help label for the instrument name in the Switch Instrument dialog and the help label for the PV prefix in the Instrument Setup dialog
---

Ticket1218 custom instrument names

---

base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/observable/BooleanWritableObservableAdapter.java

The checkbox for setting the visibility of the experiment title should now correctly reflect whether the corresponding DISPLAY:TITLE PV is connected or disconnected at all times. (previously only checked connection to PV once on DAE initialisation)
###To test
https://github.com/ISISComputingGroup/IBEX/issues/1409
Switching the instrument on/off AFTER opening the DAE perspective in the GUI correctly changes enabled state of the display title checkbox.
---

checkbox enabled state corresponds to pv connection state

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC_single.opi

Changed the OPI so that the NAME field is read-only
###To test
ISISComputingGroup/IBEX#1285 (rework following review)
IMPORTANT: the Mercury IOC is one of those that hangs for a long time if it doesn't find an instrument, and so you can't simply start it in simulation mode. To make it work for the test, you'll need to modify the MercuryTemp.db to comment out all the DTYP fields and INP/OUT that use @asyn.
Then you can start the IOC and set the SIM record to 1.
To test, you'll need to start the Mercury IOC in simulation mode, add it to a synoptic and open the OPI from the synoptic. The NAME PV is a waveform; in simulation mode you'll need to do:
`caput -S %MYPVPREFIX%MERCURY_01:1:SIM:NAME "a test name"`
The name field is read-only in the OPI …

Ticket 1285: changed OPI so that name is read-only

---

base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/internal/ObservableModel.java

ISISComputingGroup/IBEX/issues/1321
In the "Experiment Details" perspective, a default role for an added experiment team member is now 'User'.

change default experiment team role to 'User'

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamStatusView.java

See https://github.com/ISISComputingGroup/IBEX/issues/1429
To test ensure spelling is now correct

Fixed typo in beam status legend

---

base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/EmptyLogPlotterView.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterDisplay.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/OpenLogPlotterPopup.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/Perspective.java

Fixed log plotter empty label to work when opening the log plotter from an OPI
Fixes https://github.com/ISISComputingGroup/IBEX/issues/1428
System tests are at https://github.com/ISISComputingGroup/ibex_system_tests/pull/21
The empty log plotter view works as expected when opening and closing plots via an OPI
---

Empty log plotter fixes

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

Sets the visibility of the date created/modified labels in the summary tab depending on configuration history. If of length 0, it is a new configuration and the labels should not be visible.
https://github.com/ISISComputingGroup/IBEX/issues/1445
Labels are hidden in new configuration, visible otherwise.
---

GUI: Date created/modified should not appear if blank

---

base/uk.ac.stfc.isis.ibex.opis/resources/linkam95.opi

Update OPI to use PUMP:SPEED:PC instead of raw PUMP:SPEED value
1477
Behaviour should be unchanged. The PUMP:SPEED:PC should report the same value as PUMP:SPEED did before PR https://github.com/ISISComputingGroup/EPICS-ioc/pull/69
---

Use specific pump speed percentage PV

---

base/uk.ac.stfc.isis.ibex.devicescreens/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.feature.base/feature.xml

https://github.com/ISISComputingGroup/IBEX/issues/1513
Running the GUI from within Eclipse fails because of dependency issues. I suspect everyone is getting around this by using "Run Configurations".
I have added the required dependencies to the base feature.
(on master) If you start ibex.product from within Eclipse **it should fail to start.** Though it might not if you have been using a run configuration to get round the problem - you could try deleting your copy of Eclipse and installing a fresh copy from Kits$
(on this branch) If you start ibex.product from within Eclipse **it should start**.
The GUI can be started from ibex,product without fiddling with run configurations
---

Targets and targets.ui were missing from the base feature

---

base/uk.ac.stfc.isis.ibex.ui.nicos/build.properties
base/uk.ac.stfc.isis.ibex.ui/build.properties
build/build.bat
build/check_build.py

Fixes https://github.com/ISISComputingGroup/IBEX/issues/1492
Also adds a check build script that should prevent the same error from happening again
Run build.bat
Confirm that arrow icons appear in synoptic editor and in groups panel of config editor (see original ticket) of the new build
Remove the /icons/ path from a build.properties
Run build.bat
Confirm the build doesn't work with a sensible error
Original issue is fixed and new script works as expected
---
- Are there unit tests in place? Are the unit tests small and test the a class in isolation?
- Are there [system tests](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/System-Testing-with-RCPTT) in place? Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- Has …

Ticket 1492: Fix missing icons 

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/ObservedSpectrum.java
base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/observing/BufferedObservablePairTest.java
base/uk.ac.stfc.isis.ibex.epics/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/BufferedObservablePair.java

Fixed a bug where the spectra plots occasionally wouldn't update after switching to a different spectra plot number. The bug stemmed from a method being called with a PV value as argument before that value had been received, resulting in the thread to die. Fixed by adding a check for null before the method call.
https://github.com/ISISComputingGroup/IBEX/issues/1402
Graph always updates appropriately after switching to a different spectra plot. I verified by printing a line in case of the value being null and comparing the subsequent behaviour with and without the check.
---

Ticket1402 Spectra Plot Update

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java

Previously, the alarm observer would (wrongly) set the display value to "error" in case of an error (e.g. observed alarm value has wrong type on CA). Now it sets the block's alarm state to minor. This is a preliminary solution aiming to make as little changes as possible.
I have created https://github.com/ISISComputingGroup/IBEX/issues/1573 to discuss how we want to handle these errors properly.
https://github.com/ISISComputingGroup/IBEX/issues/1571
1. Block value does not get obscured by "error" message
1. Block alarm is set to "minor" in case of error in the alarm field (e.g. PV observed by block does not possess an alarm field)
---

better handling of alarm error

---

base/uk.ac.stfc.isis.ibex.validators.tests/src/uk/ac/stfc/isis/ibex/validators/tests/PvValidatorTest.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/PvValidator.java

Allow field on PVs in edit config.
https://github.com/ISISComputingGroup/IBEX/issues/1576
1. Go to edit config
1. Add a block with a field
1. Check error message for invalid PV
---
Check they are in release 2.1.0
After merge please add commit to release branch as well

Allow field to be added to PV addresses

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/.classpath
base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/.project
base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/build.properties
base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/pom.xml
base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/src/uk/ac/stfc/isis/ibex/ui/dashboard/tests/models/ObservableDecimalRatioTest.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/models/MonitorPanelModel.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/models/ObservableDecimalRatio.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/views/DashboardView.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/MonitorPanel.java
base/uk.ac.stfc.isis.ibex.ui/src/org/eclipse/wb/swt/SWTResourceManager.java

Fixed formatting of current/total so it now displays up to 9999.99.
Added extra space to the monitor panel in the dashboard, so the good/raw frames can display up to 8 digits each.
ISISComputingGroup/IBEX#1632 and ISISComputingGroup/IBEX#1648
The dashboard should now be able to display the correct number of digits.
I suggest you create in the SIMPLE IOC some TEST versions of the following PVs and point the GUI DAE observables to the test versions, so you can try out numbers with various digits:
%MYPVPREFIX%DAE:BEAMCURRENT (this is an ai)
%MYPVPREFIX%DAE:GOODUAH (ai)
%MYPVPREFIX%DAE:GOODFRAMES (longin)
%MYPVPREFIX%DAE:RAWFRAMES (longin)
---

Ticket1632 dashboard numbers display

---

base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/InstrumentInfo.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/custom/CustomInstrumentInfo.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/internal/LocalHostInstrumentInfo.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterSettings.java

More information is now saved and loaded when the GUI is closed. Rather than just instrument name, the host name and pv prefix are also now saved/restored. Fixes https://github.com/ISISComputingGroup/IBEX/issues/1110. 
* Test that the GUI is able to display the remembered instrument when the instrument list is down (just change the hardcoded INSTLIST PV)
* Test that custom instruments are remembered on GUI restart
---

Ticket1110 remember custom inst

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamStatusPanel.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/StatsPanel.java

Title the statsPanel `Beam statistics` to make it slightly clearer. Having thought about what I commented eariler `Beam information` is too generic. I also modified the code documentation slightly to make it clearer what `Stats` means. One other minor change was to remove an unused variable.
https://github.com/ISISComputingGroup/IBEX/issues/1596
Clear in GUI what the bottom right panel in the beam status perspective is
---

Clarify that stats refers to statistics

---

base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/WaitFor.java

Don't switch to the IOC log view on updates. It disrupts the user workflow
https://github.com/ISISComputingGroup/IBEX/issues/1603
Perspective does not switch to IOC log when configuration changed
---
… the user workflow

Ticket1603: Don't switch to IOC log on update

---

base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/InstrumentInfo.java

https://github.com/ISISComputingGroup/IBEX/issues/1855
Set PV INST LIST to SIMPLE IOC set the instrument list to only have names (no pvprefix).
Can switch instruments.
---
No it is failing because the constructor is not being fired through deserialisation magic which I don't know how to replicate.
Not needed

instantiate PVPrefixFactory when needed to avoid NPE

---

base/uk.ac.stfc.isis.ibex.ui.tests/src/uk/ac/stfc/isis/ibex/ui/tests/ASyncEventLimiterTest.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/AsyncMessageModerator.java

https://github.com/ISISComputingGroup/IBEX/issues/1850
Hit it with lot of messages ensure that when messages stop CPU load returns to normal. (connect to MUONFE is good test for this and compare to original client)
---

Reset task lock denied flag on requeue of task.

---

base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/PythonBuilderTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/DateTimeProvider.java

Replaced LocalDate & LocalTime in the script generator package with java.util.date to make it Java 1.7 compatible until we have decided it is time to move onto 1.8.
https://github.com/ISISComputingGroup/IBEX/issues/1920
* Package is Java 1.7 compatible
* Script generator not broken
---

Getting time & date from java.util.date rather than LocalDate/LocalTime

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml
base/uk.ac.stfc.isis.ibex.client.tycho.parent/suppressions.xml

Checkstyle now ignores *.tests packages (https://github.com/ISISComputingGroup/IBEX/issues/1918)
Confirm that Jankins does not show checkstle errors for test files.
---
- Jenkins is now ignoring .tests packages as required.

Ticket1918: Checkstyle ignores tests

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/SynopticHandler.java

…d before the synoptic perspective is opened
To reproduce the problem:
- Open Ibex client
- Edit a synoptic
- Click save
You should see the null pointer exception (on master). This is because `SynopticHandler.java` tries to get the name of the current displayed synoptic. If the synoptic perspective has never been opened, the current synoptic will be `null`. I've added an extra check for that condition.
The only other instance of this method is `refreshSynoptic` in `SynopticSelectionViewModel`. In that case we don't need to check for null because the synoptic perspective will have definitely been opened.
https://github.com/ISISComputingGroup/IBEX/issues/1925
- No null pointer exception when a synoptic is edited and saved before the synoptic perspective is opened.
---

Ticket1925: Unable to save synoptic

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/DeviceScreensDescriptionViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/DeviceScreensDescriptionViewModel.java

Added a check in the Edit Device Screens Dialogue to see if any of the device screens are pointed at a blank target, in which case a helpful error message is displayed and the "OK" button disabled. 
This prevents the user from creating device screens with non-existent OPI that throws an error when attempted to view.
https://github.com/ISISComputingGroup/IBEX/issues/1810
* User can not save device screens with a blank target
* Functionality to create/edit/delete valid device screens is preserved
---

added check that devices do not have blank targets + test

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/DevicesOpiTargetView.java

The device screens UI will now popup an error dialog if the user tries to open a device screen with no target assigned. Note that this is a protective measure as ticket #1810 will prevent users from saving a device screen without a target.
https://github.com/ISISComputingGroup/IBEX/issues/1878
---

Ticket1878: Error on no target

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/Perspective.java

Make the device screens available by default
https://github.com/ISISComputingGroup/IBEX/issues/1930
The device screen should be available by default.
If you have previously manually added the device screens, you will need to go into the settings menu (CTRL + ALT + P), then go into "ISIS perspectives" and restore defaults. When you restart the GUI, check that device screens are enabled.
---

Make device screens avialable by default

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/NOP.java

A bit of a fudge to force the menu to check for enabled at startup of GUI.
https://github.com/ISISComputingGroup/IBEX/issues/1932
---

Ticket 1932: Disable synoptic menu

---

base/uk.ac.stfc.isis.ibex.help/src/uk/ac/stfc/isis/ibex/help/Help.java
base/uk.ac.stfc.isis.ibex.help/src/uk/ac/stfc/isis/ibex/help/internal/Observables.java
base/uk.ac.stfc.isis.ibex.help/src/uk/ac/stfc/isis/ibex/help/internal/package-info.java
base/uk.ac.stfc.isis.ibex.help/src/uk/ac/stfc/isis/ibex/help/package-info.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/AboutHandler.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/ManualHandler.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/VersionPanel.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/package-info.java

Adds java version to help dialog, see https://github.com/ISISComputingGroup/IBEX/issues/1940
Open Help->About. Confirm that java version and path are displayed
---

Ticket1940 show java version

---

build/jenkins_build.bat

https://github.com/ISISComputingGroup/IBEX/issues/1941
Check on kits$ to see if the JRE is in the Client directory.
The JRE should be in the client directory and when running the client the JRE path in help->about points at the bundled one
---

Bundling JRE with client

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

https://github.com/ISISComputingGroup/IBEX/issues/1229
The target platform has been updated to point at 3.3.11.
This fixes #1229 upgrade CS-Studio and #1206 remove exception on startup.
You will need to "set the target platform" to the new one in this PR.
#1206 is simple to test: start the GUI from Eclipse and confirm you don't get the Security Exception mentioned in the ticket.
If none of this works it might be because Eclipse has cached the previous version. Try restarting Eclipse, if that fails delete the ibex_gui repo and clone it again.
Check everything works as it should in the GUI. Please check that you can connect to your local instrument and a remote one.
Please also close #1206.
---

Ticket 1229: Target platform updated to point at 3.3.11

---

base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/DescriptionsProvider.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/list/DeviceScreensComparitor.java

Sort device screens in a case insensitive way so `a` comes before `B`.
https://github.com/ISISComputingGroup/IBEX/issues/1973
Device screens are sorted alphabetically invariant of capitalisation
---

Ignore case on sorting device screens

---

base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/AboutDialogBox.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/VersionPanel.java

The java path in the about dialog is now wrapped to be on 2 lines. This will still cut off text >2 lines but as path lengths can vary a lot it is hard to find a solution that looks sensible for all cases.
https://github.com/ISISComputingGroup/IBEX/issues/2016
---

Ticket2016: Wrap java path

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServerVariables.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/ClosableObservable.java

This will cause regression of issue #2017 but will act as a temporary fix for blocks appearing disconnected due to being garbage collected.
This PR is intended as a **temporary** fix while a proper fix is worked on.
https://github.com/ISISComputingGroup/IBEX/issues/2165
---

Ticket2165 temporary fix for pvs disappearing

---

base/uk.ac.stfc.isis.ibex.dae.tests/src/uk/ac/stfc/isis/ibex/dae/tests/periods/WritingXmlFromPeriodSettingsTest.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/periods/XMLBackedPeriodSettings.java

Adds a null check against period control type
https://github.com/ISISComputingGroup/IBEX/issues/2023
Unfortunately we haven't found a way to reproduce the crash as reported on the initial ticket. If DAE is not running the instrument just stays in a "processing" state and on a real instrument you'll get a popup saying "DAE not running". After a chat with @FreddieAkeroyd we think it's getting some bad XML from somehow, which causes a value to go to null and then the DAE perspective to crash with a `NullPointerException`
From the stack trace/code, I've added a null check and a unit test against the appropriate behaviour. 
Reviewer, merge this/mark complete if it looks like a sensible solution to the exception in the original ticket. You're welcome to look for ways to reproduce it, but …

Ticket2023 dae crashing if disconnected

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/internal/ComponentFilteredConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/ComponentFilteredConfiguration.java

Preserve the order of groups as set in the configuration editor, including component groups
https://github.com/ISISComputingGroup/IBEX/issues/2273
Before starting, create a component with at least 2 groups
-  [x] Create a config, add the component. Verify that the component groups appear in the config when it is saved
---

Ticket2273 groups should be orderable

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/DeviceScreensModel.java

Call the parent method in `onCanWriteChanged`, otherwise the base property `canWrite` will never be updated and will stay at the default `false`. This will mean:
```
writableDeviceScreenDescriptions.canWrite()
```
is never true and the remote device screens won't be set.
I've checked and not found the same pattern elsewhere in the code so this should be an isolated problem. Worth bringing up at the sprint review though.
https://github.com/ISISComputingGroup/IBEX/issues/2420
---

Ticket2420: Device screens not written to server

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/DaeView.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java

I've done some rework on the layouts of the controls in the DAE perspective. I think the way the experimental setup tabs are embedded in the experiment setup tab look a bit nicer. Primarily though, the changes make it so that the experiment setup tab and its controls (esp. data acquisition) don't disappear when the GUI is shrunk
https://github.com/ISISComputingGroup/IBEX/issues/2443
---

Ticket2443 dae perspective layout

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/InstrumentTreeView.java

Enable you to drag and drop in the synoptic editor. There is no supporting code and this is not the right way to do it. There will be a follow up that will fix this including rcptt tests.
https://github.com/ISISComputingGroup/IBEX/issues/2563
1. Can drag and drop synoptic components in the tree view.
---

Add data to transfer as dummy string.

---

base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.opis/check_opi_format_tests.py

The script checker was failing on OPIs with empty text with NoneType errors. I've done 
- Some refactoring to eliminate duplicate code
- Improved error handling logic
- Improved code readability
- Added a test for empty text
https://github.com/ISISComputingGroup/IBEX/issues/2615
---

Ticket2615: OPI checker script fails for existing OPIs

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java

Blocks in the blocks overview display a purple border when the underlying PV goes into an INVALID-alarm state. 
https://github.com/ISISComputingGroup/IBEX/issues/2604
An INVALID state is reflected with a purple border around the relevant block. `SimpleIOC` has a PV `VALUE1` which is in an INVALID state by default, you can use this for testing.
---

Blocks display purple border when PV alarm state is "INVALID"

---

base/uk.ac.stfc.isis.ibex.opis/resources/ieg_system.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

As per ticket:
- Rename labels as described by Matt North
- Remove IEG sample bin pressure
- Remove macros associated with sample bin pressure
https://github.com/ISISComputingGroup/IBEX/issues/2758
- Labels match description requested by Matt North
- Display of values for the IVC pressure appropriate for:
- `<0`
- `0`
- `(0,350)`
- `350`
- `>350`
- No unit test changes necessary
- Added system tests for IVC pressures listed above, except `>350` which already existed
- No documentation changes required
---

Ticket2758 ieg negative pressure

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

Added an indicator for a disconnected sensor to the Eurotherm OPI. 
Related PR: https://github.com/ISISComputingGroup/EPICS-ioc/pull/194
https://github.com/ISISComputingGroup/IBEX/issues/2653
* Warning is hidden while sensor is connected
* Warning is displayed while sensor is disconnected
* OPI layout still looks good
N/A
N/A
N/A
---

Add indicator for disconnected sensor to OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/single_chopper_control_panel.opi

Adds the standard "manager mode required" indicator to the MK3 chopper OPI.
https://github.com/ISISComputingGroup/IBEX/issues/2718
No unit tests - OPI change only.
System tests not available for OPIs
No additional documentation was added, generic manager mode documentation exists at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-access-security
---

Add access security indicator

---

.gitignore
base/uk.ac.stfc.isis.ibex.dae.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.dae.tests/src/uk/ac/stfc/isis/ibex/dae/tests/spectra/SpectrumTests.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/ObservedSpectrum.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/Spectra.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/Spectrum.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/SpectrumYAxisTypes.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/UpdatableSpectrum.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectraPlotsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumPlot.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumView.java

Adds the ability to select whether to display the DAE spectra plots in "counts /s" (same as what we currently have) or "counts" (which SANDALS want).
https://github.com/ISISComputingGroup/IBEX/issues/2687
* The easiest way to see this is to find an instrument with a discontinuity in their time channel binnings, and check that this translates to a discontinuity on the spectra plots.
* Start an ibex client
* Select a few different settings on the spectra screen for spectrum numbers, period and axis types
* Restart the client
* Verify that the settings are the same as you just set.
I've added some unit tests to check that a test spectra gets scaled appropriately when in absolute counts mode, and is unchanged when in count rate mode.
Discussed RCPTT with @John-Holt-Tessella but we decided …

Ticket2687 absolute spectra count

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/actions/DaeAction.java

Fixes a case where (I think) two threads were entering the same non-threadsafe method simultaneously, causing some DAE buttons to be in the incorrect state. This applies to all the DAE buttons (Start run, stop run, apply changes, etc).
https://github.com/ISISComputingGroup/IBEX/issues/2643
Firstly, set up your ICP so that it won't die when doing many runs:
- In `C:\Instrument\Apps\EPICS\ICP_Binaries\isisicp.properties`, add the line `isisicp.asyncend = false`
- In `C:\Instrument\Apps\EPICS\ICP_Binaries\icp_config.xml` set CRPTSize to 60000000
- Stop the ISISDAE ioc
- Kill the ISISICP process from task manager
- Restart the ISISDAE ioc (this will automatically restart ICP)
- Ensure you have valid wiring/spectra tables etc so that you are able to start a run.
Using the master branch:
- Run …

Fix DAE buttons being greyed out in setup

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/adapters/TextUpdatedObservableAdapter.java
base/uk.ac.stfc.isis.ibex.ui.dae.tests/.classpath
base/uk.ac.stfc.isis.ibex.ui.dae.tests/.project
base/uk.ac.stfc.isis.ibex.ui.dae.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.dae.tests/build.properties
base/uk.ac.stfc.isis.ibex.ui.dae.tests/pom.xml
base/uk.ac.stfc.isis.ibex.ui.dae.tests/src/uk/ac/stfc/isis/ibex/ui/dae/tests/DAEComboContentProviderTest.java
base/uk.ac.stfc.isis.ibex.ui.dae/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DAEComboContentProvider.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetupViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsViewModel.java

I've updated the DAE perspective to get the directory path for error messages concerning missing tables from the DAE rather than constructing it in place. The previous path builder gave incorrect values.
https://github.com/ISISComputingGroup/IBEX/issues/2825
Added some unit tests for the combo box logic
Automated system tests are currently on hold owing to framework changes. I've added a test to the manual system tests
No changes
---

Get content directory from DAE PVs, rather than building in place

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor_v2.opi

Adds access security indicator to galil OPI as per https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-access-security
https://github.com/ISISComputingGroup/IBEX/issues/2789
- Access security is set up.
- Indicator displays when access security is set up and not enabled
- Indicator does not display at other times.
Not applicable
Not applicable
Documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-access-security is sufficient
---

Add manager mode indicators

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/BlockNameValidatorTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/BlocksTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/EditableConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/GroupsTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockNameValidator.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableGroup.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ConfigEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/blockselector/BlockSelector.java

There was some confusion between different methods in the EditableConfiguration, I improved their names and made sure they were used correctly everywhere.
https://github.com/ISISComputingGroup/IBEX/issues/2755
* Create a config which includes blocks inside groups, blocks outside groups and blocks from components.
* Confirm that you cannot add a block with the same name as any of the above (this was refactored)
* Go to the synoptic editor screen and add a block to a synoptic component
* Confirm that all blocks appear in the dialog box
Added some tests to improve coverage of how groups work.
No change to documentation other than comments
---

Ticket2755: Synoptic editor can select select all blocks

---

base/uk.ac.stfc.isis.ibex.opis/resources/sample_stack/setMotorMacros.py

I've added some extra methods so that if you have multiple axes with the same suffix (e.g. CHOP:Z, STACK:Z) then the generic sample stack OPI will detect it and make sure to generate different labels
https://github.com/ISISComputingGroup/IBEX/issues/2843
- Create a sample stack OPI (e.g. in device screens)
- Add various combinations of macros, where some of them overlap in the description above
- The OPI should always generate unique, sensible labels for the axes
Note that this can be done without a motor IOC running but there's a delay when opening the IOC because it waits for all the PVs it's looking for to time out.
None. OPI
None. OPI
Not needed
---

Ticket2843: Break degeneracy in OPI label generation for generic sample stack

---

base/uk.ac.stfc.isis.ibex.help/src/uk/ac/stfc/isis/ibex/help/Help.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/AboutDialogBox.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/VersionPanel.java

Add the current PVPrefix into the Help -> About menu.
This will change according to the selected instrument.
https://github.com/ISISComputingGroup/IBEX/issues/2419
Added to manual system test template
---

Display PVPrefix in Help -> About

---

base/uk.ac.stfc.isis.ibex.validators.tests/src/uk/ac/stfc/isis/ibex/validators/tests/PvValidatorTest.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/PvValidator.java

Added a check to the PV validator to 
https://github.com/ISISComputingGroup/IBEX/issues/2644
Validator catches PV Addresses that have a double colon, for example `INS::SOMETHING:`
Added a specific test for double colons.
---

Add regex to check for double colons in PV and a test for it

---

base/uk.ac.stfc.isis.ibex.opis/check_OPI_format_utils/xy_graph.py
base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.opis/check_opi_format_tests.py
base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi
base/uk.ac.stfc.isis.ibex.opis/resources/TPG300.opi
base/uk.ac.stfc.isis.ibex.opis/resources/neocera_ltc21.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template.opi

Increase buffer size in graph to make it capture all points. Also update check script to ensure this can not happen again. Fix other similar OPIs,
https://github.com/ISISComputingGroup/IBEX/issues/2762
Can plot more than 100 points of heater changes on the graph (see handy script on ticket)
Can not test graph plotting but have tested opi format checker
Non no-point
Non - small change
---

Increase buffer size to be the same as temperature

---

base/uk.ac.stfc.isis.ibex.ui.motor/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/MotorOPIView.java
base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/TableOfMotorsView.java

Close any open motor OPIs when we change instrument
https://github.com/ISISComputingGroup/IBEX/issues/1897
- Open a motor OPI from the motors table
- Change instrument
- Verify the OPI closes
UI only
Test 29-1 added
None needed
---

Ticket1897 close motor opis on instrument change

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/ConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Configuration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/ConfigEditing.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/internal/Variables.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/widgets/SynopticSelection.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/widgets/SynopticSelectionViewModel.java

We've removed "recommended" from the default synoptic name in the config editor dialog as it didn't add any functionality. On discussion with @John-Holt-Tessella, the main use of having a default synoptic appears to be to be able to return to an appropriate synoptic in the synoptic perspective. As such, we've added a "load default" synoptic button to the perspective.
Additionally, the default synoptic in the config editor dialog will now always be the default synoptic for that configuration. Previously, if no synoptic was actively selected by the user at time of creation, the default synoptic for the current configuration would be used. This could lead to confusing behaviour on saving and loading configurations.
https://github.com/ISISComputingGroup/IBEX/issues/2527
Run the new manual …

Ticket2527 default synoptics in edit config dialog

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.ui.beamstatus/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamGraphView.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoView.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/McrNewsPanel.java

Continued the migration of the beam status perspective to Eclipse 4: 
- added viewparts for MCR News and Beam Stats
- hidden toolbar on beam status graph
https://github.com/ISISComputingGroup/IBEX/issues/2812
/
/
Removed relevant TODOs in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eclipse-4-Migration-TODOs
---

Ticket2812 e4 beamstatus view

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/detectordiagnostics/DetectorDiagnosticsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/run/RunSummary.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectraPlotsPanel.java

Added scrolled composites to all DAE perspective tabs to account for resizeable viewparts.
https://github.com/ISISComputingGroup/IBEX/issues/2812
Can arbitrarily resize DAE perspective without any UI elements becoming inaccessible in any of its tabs.
/
/
Removed relevant TODO in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eclipse-4-Migration-TODOs
---

Ticket2812 e4 dae scrollbars

---

base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/package-info.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/preferences/PreferenceConstants.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer.tests/src/uk/ac/stfc/isis/ibex/ui/journalviewer/tests/JournalViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/models/JournalViewModel.java

Added a manual refresh button in the Journal Viewer perspective. Slightly updated connection status labels (to make last successful update visible even when last attempt to connect was unsuccessful) and adapted connection information communicated by the `JournalModel` accordingly.
https://github.com/ISISComputingGroup/IBEX/issues/2902
- Updated `JournalViewModelTests` to work with changes in models.
Added test 32-3 to manual system tests spreadsheet.
/
---

Ticket2902 journal viewer refresh

---

base/uk.ac.stfc.isis.ibex.journal/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/models/JournalViewModel.java

Allow the journal viewer to display paginated results
To check the performance, I loaded all of ENGIN-X's journal files from the last 5 years into my local database. I wrote a quick script to do this, it's not perfect but it can serve as the basis for a data ingestion upgrade script in the future.
https://github.com/ISISComputingGroup/IBEX/issues/2904
I have made the user interface quite dumb at the moment because it's likely to change in the next ticket (table view)
None added in model because SQL layer is hard to mock. None added in viewmodel as there is no logic so nothing to test.
RCPTT dead, squish not yet alive
None
---

Ticket2904 jv pagination

---

base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/models/BannerModel.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/views/DashboardView.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/Banner.java

Makes it more obvious when an instrument is in simulation mode. Should look similar to the mockup on the ticket, bearing in mind the colour-blindness considerations in the comments.
https://github.com/ISISComputingGroup/IBEX/issues/2869
No unit tests added as this was only GUI code
None added, RCPTT not being developed any more, squish not yet ready.
None required for this minimal change.
---

Ticket2869 sim mode more obvious

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/EditableConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableIoc.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/ObservableEditableConfiguration.java

Fixes the crash described in https://github.com/ISISComputingGroup/IBEX/issues/2222
https://github.com/ISISComputingGroup/IBEX/issues/2222
- Follow the steps listed in the ticket. Ensure you cannot reproduce the bug.
I've added a unit test to ensure state is not shared when it shouldn't be. This test should fail on the old code and pass on the new code.
None added.
None.
---

Ticket2222 ioc settings persist after cancelling

---

base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/widgets/SynopticPanel.java

Removed logic for not showing beam in synoptic when only one component exists.
https://github.com/ISISComputingGroup/IBEX/issues/2922
Create a synoptic with only one component and check "show beam" option. Make sure beam is displayed after saving.
This is a GUI change and is hard to do unit tests for because it spans multiple sections.
We aren't currently doing system tests.
Checked documentation and can't see anywhere it says that a single component won't show the beam.
Current documentation is shows this behaviour properly.
---

Ticket2922 Remove logic for not showing beam in synoptic when only one component exists.

---

base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pvmanager/PVManagerWritable.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/LoggerUtils.java
base/uk.ac.stfc.isis.ibex.ui.configserver/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DisablingConfigHandler.java

Adds some extra debug logging
https://github.com/ISISComputingGroup/IBEX/issues/3001
- If no extra environment variables are set, no additional logging.
- If an envoronment variable called `IBEX_GUI_EXTRA_DEBUG` is set to `1`, you get additional debug messages.
- If an envoronment variable called `IBEX_GUI_EXTRA_DEBUG` is set to any other value, you do not get additional debug messages.
No unit-testable logic
None
Added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Eclipse-logging
---

Ticket 3001

---

base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
base/uk.ac.stfc.isis.ibex.opis/resources/EurothermFileCheck.py
base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/DisplayChannels.js
base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/DisplaySummary.js
base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

- Stopped errors regarding local PV data source not being configured. This involved adding the missing dependency `org.diirt.datasource-loc`
- I've been through a selection of OPIs that covers all external scripts and several internal The following issues were found:
- JS API now expects `boolean` rather than boolean `String` equivalents
- One instance of the import module in a Python script has been changed
- I've added the dependency for the `databrowser` OPI widget for the stress rig OPI
- I've added a ticket to improve the appearance of the new `databrowser` in the stress rig OPI
https://github.com/ISISComputingGroup/IBEX/issues/2875
- All existing scripts within OPI work as in E3
No change
No change
No change
---

Ticket2875 fix opi scripting

---

base/uk.ac.stfc.isis.ibex.opis/resources/JulaboFP50.opi

Adds a control mode selector to the Julabo FP50 OPI (The FL300 does not support setting control modes).
As part of this, I took the opportunity to convert the OPI to new-style.
https://github.com/ISISComputingGroup/IBEX/issues/3097
None
See IOC system tests PR
None
---

Convert julabo OPI to new style. Add control mode.

---

base/uk.ac.stfc.isis.ibex.opis/resources/CCD100/CCD100.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CCD100/single_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Removes references to flow on CCD100 OPI (it is not only used to measure flow it can measure many different things)
https://github.com/ISISComputingGroup/IBEX/issues/3142
n/a
n/a
n/a
---

Remove reference to flow on CCD100

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationPanel.java

DAE view -> Run information tab - > Period Duration value incorrectly showed Period Sequence value.
Changed it to show Period Duration.
https://github.com/ISISComputingGroup/IBEX/issues/3132
On the IBEX client, go to: DAE view -> Run information tab
And check that the Period Duration in the Periods group shows the correct value.
You can see the correct value in an EPICS terminal with "caget IN:LARMOR:DAE:RUNDURATION_PD" (using LARMOR as an example).
N/A
N/A
No change to docs made.
---

Ticket3132: Fixed bug: periodDuration showed periodSequence value

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/detectordiagnostics/DetectorDiagnosticsTable.java

Sorts DAE detector diagnostics tables purely numerically rather than string based
https://github.com/ISISComputingGroup/IBEX/issues/3186
Table sorts correctly
This is quite hard to test, the sorting logic is quite deep down in SWT layers, this change just passes it the correct comparator to use.
None added, minimal change
None
---

Sort DAE table numerically

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/McrNewsPanel.java

We changed the URL for the MCR display as per the recommendation in the ticket.
https://github.com/ISISComputingGroup/IBEX/issues/3244
The url has been changed.
Not applicable.
Not applicable.
We looked in the user's manual and the developpre's manula but there wasn't any documentation on the URL.
---

updated MCR display URL

---

base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/WritableComponentView.java

I removed the checkbox next to the synoptics writable PV components in the GUI.
https://github.com/ISISComputingGroup/IBEX/issues/3205
After launching the IBEX GUI, the checkbox next to the synoptics writable PV components should have disappeared..
None available.
None available.
As far as I can tell there is no documentation relating to the checkbox.
---

Removed the checkbox next to the synoptics writable PV components

---

base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/ManagerModeModel.java

We needed to wait for a short time for the manager mode pv to connect before checking if we were in manager mode. This was returning null, and so throwing the exception.
Added a half second wait before trying to open the dialog when the manager mode status is unknown.
https://github.com/ISISComputingGroup/IBEX/issues/3213
Manager mode dialog opens first time.
N/A
Added a manual system test to the spreadsheet.
N/A
---

Added half second wait for manager mode PV.

---

base/uk.ac.stfc.isis.ibex.ui.scripting/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/InterruptScript.java

Adds the Ctrl+C shortcut to the scripting window.
https://github.com/ISISComputingGroup/IBEX/issues/3241
* Start a script
* Change perspective and press Ctrl+C
* Go back to scripting, confirm script is not interrupted
* Press Ctrl+C and confirm script is interrupted
Too closely tied to framework.
Not currently doing.
---

Ticket 3241: Added keyboard shortcut to interrupt scripts

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/EditConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java

Gave the user the option of staying on their current config, or switching to the new one when using "Save as..." while editing current config.
https://github.com/ISISComputingGroup/IBEX/issues/3203
N/A
N/A
N/A
---

Added option to switch config on save as, or not.

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/DeleteSynopticHandler.java

I added a warning that pops up when a user tries to delete a synoptic that is being used in the current configuration. I also ensured that upon deletion of said synoptic, the current configuration's synoptic is switched to "-- NONE --". As it's only after deletion of a synoptic used in a configuration that a configuration whose synoptic doesn't exist can be loaded or edited, the defaulting of the synoptic to "-- NONE --" is done after deletion of the synoptic.
https://github.com/ISISComputingGroup/IBEX/issues/3211
-On edit or load of configuration whose synoptic does not exist the NONE is selected. (Moved to: https://github.com/ISISComputingGroup/IBEX/issues/3288)
-On deletion of a synoptic used in a configuration the user should be warned.
None applicable.
None applicable.
None related. …

Added warning when trying to delete synoptic in current configuration.

---

base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi

Removed confusing options in oscillating radial collimator OPI
https://github.com/ISISComputingGroup/IBEX/issues/3135
Confirm that they user can no longer set the mounting radius or change the underlying motor.
---

Ticket 3135: Tidy Merlin ORC

---

base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/UserDetails.java

I trimmed any leading or following white space (tabs, spaces etc.) from the user name and institute name in the experiment team table.
https://github.com/ISISComputingGroup/IBEX/issues/3305
Please notice the name of this branch starts with two Ts (TT) when trying to check it out.
None required.
None required.
None found.
---

Trimmed any leading or following whitespace from the various names.

---

base/uk.ac.stfc.isis.ibex.opis/resources/Common Scripts/CopyPVs.py
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/gem_jaws/Jaws_gem.opi

Created script to copy PVs from OPIs (only works for PVs with values of type double).
Added button to run that script for GEM Jaws to copy beam height & width and beam centre coords to the beamscraper jaws.
**Note:** Only works when beamscraper jaws are on MOT:JAWS6.
https://github.com/ISISComputingGroup/IBEX/issues/3018
Check that the button "Send to Beamscraper Jaws" in the GEM Jaws OPI copies the setpoint values for Size of Beam at Sample (Horizontal and Vertical) and Beam Centre (Horizontal and Vertical) to the beamscraper jaws.
N/A
N/A
N/A
---

Ticket 3018: Added button to copy GEM jaw params to beamscraper jaws

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/EditConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.experimentdetails/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/rblookup/RBLookupViewModel.java

I refined the logic as to when the changes should be saved to the current config or not. To do so, I added a method to check if the confirmation dialog asking whether or not to switch to the current config had been called. The reason for doing so is that the same save dialog (not the confirmation dialog) is called for "save as" and for "save". This means that checking if the confirmation dialog has been okayed happens both for "save" and "save as", and therefore if the user clicks "save", the confirmation dialog doesn't open and the previous logic assumed that the confirmation dialog had been refuted. This lead to the configuration not being saved when the "save" button was used. Adding a method to check if the confirmation dialog has been called or not allows to distinguish between when …

Fixed config saving issue.

---

base/uk.ac.stfc.isis.ibex.epics/.classpath
base/uk.ac.stfc.isis.ibex.epics/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.epics/build.properties
base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/ca/ca.xml
base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/datasources.xml
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pv/ObservablePV.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pvmanager/PVManagerObservable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pvmanager/PVManagerSettings.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pvmanager/package-info.java

Removes need to have channel access config files in user area
To do this I've put them in a resources folder and then poked PV manager to use these files as opposed to it's default ones
https://github.com/ISISComputingGroup/IBEX/issues/3311
- Delete `.diirt` folder from `C:\Users\<name>\`
- Check that if you build E4 via the IDE, you can still talk to PVs
- Check that if you build E4 via the batch script, you can still talk to PVs
None - this is setting PV manager preferences / system environment variables, no testable logic
Yes, they should work (even after we remove .diirt on the squish server).
When merged I will remove section in documentation that talks about how to set up channel access for E4.
---

Remove need to have diirt config files in user area

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockDetailsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/validators/ComponentValidator.java
base/uk.ac.stfc.isis.ibex.validators.tests/src/uk/ac/stfc/isis/ibex/validators/tests/PvValidatorTest.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/ErrorAggregator.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/ErrorMessage.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/ErrorMessageProvider.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/PvValidator.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/WarningMessage.java

I added a warning in the block editor when you try to create a block containing `<pv name>:SP`, `<pv name>:SP:RBV`, `CS:SB:*` . This warning will not be called when an error message is to be displayed and does not stop the user from setting the block. I decided to set this warning in the block editing dialog as that is when the decision to create a block pointing to a certain PV is taken. See ticket for warning messages.
https://github.com/ISISComputingGroup/IBEX/issues/2620
I added unit tests to check that the warning is triggered and that it contains the correct message.
NA
None found.
---

Addded a warning when creating a bad PV.

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/TargetPropertiesViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/TargetPropertiesWidget.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/TargetPropertiesViewModel.java

Auto selects first device screens macro.
https://github.com/ISISComputingGroup/IBEX/issues/2835
- When a device screen is selected the first macro becomes active ready for entering data without needing to be selected specifically.
None required.
None required.
None related
---

Auto selects 1st device screens macro.

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/DefaultName.java
base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/BlocksEditorViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigDetailsDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ConfigEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksEditorViewModel.java

I added the option to copy blocks when editing a configuration. For this, I added:
- A copy button to the block tab of the config editing panel.
- A method that copies one or more blocks when they are selected in the table.
- A method to rename these blocks so that each block has a unique name.
- A keyboard listener that allows for the key combination ctrl+c to be detected and used as a shortcut to copy the selected blocks in the table.
https://github.com/ISISComputingGroup/IBEX/issues/3293
- The blocks are copied correctly, are added to the configuration and are displayed in the table.
- Both the shortcut and the button work, for one or more blocks.
- The button is correctly placed.
- A unique name is given to the copied block or blocks.
Unit tests added to test the view model for the …

Added option to copy blocks when editing a configuration.

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/SynopticPreview.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/SynopticPresenter.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/beamline/BeamlineComposite.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/beamline/BeamlineCompositeContainer.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/BasicComponent.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/ComponentPropertiesView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/ComponentView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/GroupView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/WritableComponentView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/views/SynopticView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/widgets/SynopticPanel.java

The OPIs now cannot be opened from the synoptic preview. Similarly, changing the value of a writable PV in the synoptic preview changes its value in the preview but doesn't write the value to the PV. This ticket involved passing a boolean from the point where the synoptic was created to where the OPIs could be opened or where the PVs could be modified.
https://github.com/ISISComputingGroup/IBEX/issues/2583
N.B.: To write to a PV you must press `ENTER` after filling in the writable text box. 
None required.
None required.
None related.
---

Disallowed opening OPIs from synoptic preview.

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

The `synoptic` drop down menu now displays the default synoptic when opening the configuration editing dialog. 
https://github.com/ISISComputingGroup/IBEX/issues/2883
- When editing a configuration, the "default synoptic" the drop down menu displays the default synoptic. 
- This does not stop the user from setting a default config, and doesn't break the default config button in the synoptic perspective.
None needed.
None needed.
None related.
---

The drop down menu now displays default synoptic when editing configs.

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.ui.logplotter/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.logplotter/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/EmptyLogPlotterView.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterHistoryPresenter.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/OpenLogPlotterPopup.java

I had a look at adding an extra tool item to open the properties pane - this is not easy, the code is buried in an "internal" CSS class (see [here](https://github.com/ControlSystemStudio/cs-studio/blob/master/applications/appunorganized/appunorganized-plugins/org.csstudio.rap.rtplot/src/org/csstudio/swt/rtplot/internal/ToolbarHandler.java)).
However, I have made the properties screen open in a sensible way from the right click context menu. at the same time I also made all the other items in that context menu open in sensible places. The only one I was unable to "fix" was "Open data browser perspective", which is hard-wired to CSS's data browser perspective. Luckily it is easy for our users to get back out of this state - clicking on any IBEX perspective will take them back to a known …

Ticket3080 open logplotter properties

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java

Fix a thread going CPU bound and leaking memory in the GUI.
**NOTE: in E3, there is a (different) issue with a memory leak when switching instruments. This leak does not appear in E4. Since everyone is going to be on E4 soon I have not put any effort into fixing that leak. It also only occurs when switching instruments so is unlikely to be an issue on the instruments.**
https://github.com/ISISComputingGroup/IBEX/issues/3330
- Memory leak / going CPU bound issue is fixed
- None added - this is hard as it's to do with the threading.
Added documentation to the relevant area of the code.
---

Fix memory leak

---

base/uk.ac.stfc.isis.ibex.opis/resources/live_view.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

This ticket adds a live view OPI.
See https://github.com/ISISComputingGroup/IBEX/issues/2230
To test:
* Get changes from https://github.com/ISISComputingGroup/EPICS-areaDetector/pull/7
* Follow instructions on https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-Live-View for running a simulated live view
* Run the live view via a device screen
* Change the X and Y of the detector in ADSimDetector/iocs/simDetectorIOC/iocBoot/iocSimDetector/st_base.cmd
* Restart the IOC, confirm the OPI updates appropriately.
Note:
* The default update time of the simulator is 0.001 secs, which is pushing the OPI much more than the 1 sec the DAE will run at. I saw some rendering issues at this speed in E3 but not in E4, if you do have issues try lowering this value as specified in the …

Ticket 2230: Add a live view OPI

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/PerspectiveResetAdapter.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/commands/ResetPerspective.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/commands/SwitchPerspective.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/views/PerspectiveSwitcherView.java

I added a shortcut to reset a perspective's layout. The shortcut is "Alt+Shift+O". This is a bit awkward, "O" isn't the first letter that pops to mind when thinking of "Reset Layout" but  "Alt+Shift+R", "Alt+Shift+E", "Alt+Shift+A", "Alt+Shift+L", "Alt+Shift+Y" are already taken. "Alt+Shift+Z" could maybe be better as it is close to "Ctrl+Z" that is often used to undo the last change?
**Note: it has been implemented as Alt+Shift+Z**
https://github.com/ISISComputingGroup/IBEX/issues/3421
- "Alt+Shift+O" resets the current perspective's layout.
- "Alt+Shift+O" is a suitable keybinding.
None required.
None required.
None found.
---

Created shortcut to reset layout.

---

base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pvmanager/PVManagerWritable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/writing/BaseWritable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/writing/BaseWriter.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/writing/ForwardingWritable.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/ConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditCurrentConfigHandler.java

Fixes some concurrency issues in some writable / writer layers which were causing items in the configuration menus to be greyed out erroneously.
https://github.com/ISISComputingGroup/IBEX/issues/3397
With the master branch:
- Open the GUI 10 times pointing at an instrument with a running blockserver
- Confirm that sometimes, some of the items in the configuration menus are greyed out when they shouldn't be.
With this branch
- Open the GUI 10 times pointing at an instrument with a running blockserver
- Confirm that the correct set of menu items is enabled reliably
This is to do with multithreading - it would be very hard to unit test.
This already has appropriate system test coverage because almost all of the squish tests interact with the configuration menu(s) in some way. The original …

Ticket3397

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/BlocksTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Block.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockFactory.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ConfigEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/DeleteTableItemHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksEditorViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksTable.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/IocOverviewPanel.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

I changed the buttons in block editor to be ``Add Block``, ``Duplicate Block``, ``Edit Block`` and ``Delete Block``. I also added a feature to underline the first letter of each (except for ``Delete Block``) as these letters are used for the keyboard shortcuts. I didn't underline the delete block as I'm guessing using the ``DEL`` key is fairly instinctive and because I couldn't get more than one letter per word to be underlined. This is because I used the mnemonic tool, by setting and ``&`` before each letter corresponding to a keyboard shortcut and simulated a key event where the alt key would be pressed. This is a slightly dodgy way of doing this, but after struggling for a while I did not manage to set the button to only have one underlined character (because you can only underline …

Underlined the relevant letters.

---

base/uk.ac.stfc.isis.ibex.banner/src/uk/ac/stfc/isis/ibex/banner/motion/ObservableMotionControl.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/MotionControlModel.java

Stop all button is permanently enabled when it is writable (even if motors not moving)
https://github.com/ISISComputingGroup/IBEX/issues/3399
Stop all button is permanently enabled when it is writable (even if motors not moving)
n/a - UI change only
n/a
n/a
---

Better logic for stop all button.

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/DeleteSynopticHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/NewSynopticHandler.java

Users can now delete synoptics again 
[3488](https://github.com/ISISComputingGroup/IBEX/issues/3488)
- Can delete synoptics 
None
Squish test under creaion now 
None
---

Can now delete synoptics

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/OSIRIS_jaws.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/vertical_jaws.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Added an OPI for a vertical-only jaw set as used in OSIRIS 
[Link to ticket](https://github.com/ISISComputingGroup/IBEX/issues/3463)
- The jaw set only uses North-South jaws
- Can set a vertical centre 
- Can set a vertical gap
- Can set positions of the 2 jaws individually 
New IOC test framework tests to check galil-powered vertical jaws  
N/A
None 
---

Ticket3463 osiris jaws opi

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupRow.java

Fixed an issue where the blocks panel would get stuck continuously resizing itself due to changing column widths. Gave the block names label a fixed size and added the block's full name to the tooltip (in case it is too long and gets truncated).
https://github.com/ISISComputingGroup/IBEX/issues/3554
- The juddering behaviour described in the original ticket is not observed anymore
- All information on the blocks panel is still clearly visible to the user.
/
/
/
---

Fixed size for block name label

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/single_chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/single_chopper_control_panel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.targets/src/uk/ac/stfc/isis/ibex/ui/targets/OpiTargetView.java

Added a macro to the MK3 Chopper OPI that allows users to point it at a different instrument. If not set, it will default to the local instrument prefix.
Also fixed a bug where blank macros on an OPI would be set to an empty string rather than not being set.
Fixes https://github.com/ISISComputingGroup/IBEX/issues/3524
None. Started adding unit tests for the change that checks for blank macros in an OPI target, but the logic is in an abstract class which makes testing problematic. Factoring that bit out into a testable class seems more trouble than it is worth - let me know if you disagree
None, OPI only
None
---

Allow setting inst prefix as macro on mk3 chopper

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/inout_motion_setpoints.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position_part.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/position_LED.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/setTargetPosition.py

"Few motion setpoints"(<4) OPI:  added individual LEDs for indicating whether motor is in one of the individual setpoint positions as requested by INES for the In/Out neutron camera.
Related PR: https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/11
https://github.com/ISISComputingGroup/IBEX/issues/3577
None. Contains some simple scripting but pending discussion how to implement OPI script testing framework, how to deal with CSS dependencies etc.
None, OPI only
None
---

Create individual position indicators for motion set points as needed

---

base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/model/desc/TargetDescriptionTest.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/ComponentDescription.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/Property.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/TargetDescription.java

Fixes an implicit link between a source & copied synoptic component's macros.
https://github.com/ISISComputingGroup/IBEX/issues/3697
- Workflow in ticket is no longer broken
Added a test simulating the workflow in ticket
This is adequately tested by unit tests; system tests at this level of detail not needed.
N/a
---

Ticket3697 fix synoptic copy

---

base/uk.ac.stfc.isis.ibex.opis/resources/moxa1240.opi

Change moxa 1240 OPI PVs to point at scaled rather than raw input values 
https://github.com/ISISComputingGroup/IBEX/issues/3969
N/A, OPI change only
N/A OPI change only
None
---

Change OPI to point to scaled PV

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/GeniePythonConsoleFactory.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PythonInterpreterProviderFactory.java

PyDEV v6 caused an issue with resetting layouts while the python console is open (the upgrade was done in ticket 3506)
Downgrade back down to Pydev 5.9.2 (this is still an upgrade over our previous version).
Flash reviewed by @Alistair-McGann-Tessella

Downgrade PyDEV to fix reset layout

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product

Adds flag to generate core dumps on segmentation fault.
https://github.com/ISISComputingGroup/IBEX/issues/3877
Core dumps can be analysed.
To test this, here is some code to generate a segmentation fault. Insert it into a location of your choosing. **Ensure that you do not commit this to git**.
```
import sun.misc.Unsafe;
...
try {
Field f = Unsafe.class.getDeclaredField( "theUnsafe" );
f.setAccessible( true ); 
Unsafe unsafe = (Unsafe) f.get( null );
unsafe.putAddress(0, 0);
} catch (Throwable t) {
System.out.println("Crashed while trying to crash");
}
```
After IBEX has crashed with the above code, you should be able to run a command like the following to get a traceback of where every thread was at the time of the crash. You may need to change the JDK release depending on what you have …

Add flag to create dump on crash

---

base/uk.ac.stfc.isis.ibex.opis/resources/ips.opi
base/uk.ac.stfc.isis.ibex.opis/resources/itc503/itc503.opi

Cryogenic users do not want to be able to set the ITC or IPS into locked control mode from the GUI.  To implement this, the "Locked/Remote only" modes have been removed from the GUI for ITC503 and the "Local & Locked / Remote & Locked" modes have been removed for IPS. The control mode is no longer populated by PV's and the control mode options are hard coded into the GUI. This removes the possibility of the GUI populating empty items in the drop down menu if the modes were just removed from the DB records.
https://github.com/ISISComputingGroup/IBEX/issues/4227
Amended release notes to include suggested changes.
See https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev
---

Ticket4227 remove locked state from itc ips

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper_lift.opi

Users of the fermi chopper lift opi on EMMA do not want to be able to move the chopper whilst it is levitated. To do this, the LEVITATION_COMPLETE PV is read and used to disable the  "Clamp in Beam" or "Park in Beam" buttons when it is levitated. Additionally, when the PV is in alarm (i.e. the device is disconnected) the users want to be able to move the chopper so the buttons are enabled by default in this condition. 
[#3751](https://github.com/ISISComputingGroup/IBEX/issues/3751)
To test this, run the SKFMB350 emulator and in the GUI press 'Run'. Ensure that the levitation complete LED comes on, try to use the  "Clamp in Beam" or "Park in Beam" buttons. Whilst the levitation complete LED is still on, turn off the emulator. Try to use the  "Clamp in Beam" or "Park in Beam" buttons. …

Ticket3751 fermi chopper lift opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/jsco4180.opi

Added alarm sensitive borders to JASCO 4180 stream records.
Some further alarms can be added using the `error_setter.template` but since the template also transfers values (with errors) extra work to change records is required (where record redirection is used).
[#4257](https://github.com/ISISComputingGroup/IBEX/issues/4257)
---

Ticket 4257 - Jasco 4180: no errors for disconnected device

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

Display interlocks on model 8500 as well as 8000.
https://github.com/ISISComputingGroup/IBEX/issues/4355
- Interlocks panel displays on both Danfysik 8000 and 8500 models.
n/a
n/a
n/a
---

Display interlocks for a model 8500 Danfysik.

---

base/uk.ac.stfc.isis.ibex.opis/resources/jsco4180.opi

Added a control on the Jasco OPI for setting the pump calculation method in timed mode.
Related PRs:
https://github.com/ISISComputingGroup/EPICS-Jsco4180/pull/4
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/189
https://github.com/ISISComputingGroup/IBEX/issues/4029
OPI only
OPI only
Added note about calculation method on [Jasco wiki page](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/JASCO-PU--4180-HPLC-Pump).
---

Add control for setting pump calculation method

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/Descriptions.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/MacroInfo.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/OpiDescription.java
base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/model/desc/TargetDescriptionTest.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/TargetDescription.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/DeviceScreensDescriptionViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/DeviceDescriptionWrapper.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/selector/TargetSelectorViewModel.java

- Added default macro value key to `opi_info.xml`
- Modified GUI code to display these defaults in macro tables of device screens and synoptic editor windows.
https://github.com/ISISComputingGroup/IBEX/issues/4346
- Default macro values specified in `opi_info.xml` file are displayed in both the device screens and synoptic editor windows.
- Values already entered manually aren't overwritten.
Modified tests as changed which object is passed in (macro list containing name and value, rather than just name as previously).
N/A
Wiki page describing OPI creation needs to be edited when ticket merged.  Additional instruction required to add (optional) default values for any macros used.
---

Display default OPI macro values in GUI editor windows

---

base/uk.ac.stfc.isis.ibex.alarm.tests/src/uk/ac/stfc/isis/ibex/alarm/tests/AlarmSettingsTest.java
base/uk.ac.stfc.isis.ibex.alarm/src/uk/ac/stfc/isis/ibex/alarm/AlarmSettings.java
base/uk.ac.stfc.isis.ibex.ui.logplotter.tests/src/uk/ac/stfc/isis/ibex/ui/logplotter/tests/LogPlotterSettingsTest.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterSettings.java

Change timezone from UTC to Europe/London for the gui mysql connection strings
https://github.com/ISISComputingGroup/IBEX/issues/4406
- Unit tests updated to expect new connection string
-
-
---

Change timezone to Europe/London rather than UTC

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

See https://github.com/ISISComputingGroup/IBEX/issues/4299
To test:
* Open more details screen on motor OPI
* Confirm it has the name of the motor as the tab title
N/A
N/A
N/A
---

Ticket 4299: More details screen now has motor name as title

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_inout.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setPositionMacros.py

This ticket is part of the work to provide the parameters found on the 'Components: Positions relative to beam' screen on the opi in the same order in which they are found in the config. The work also provides an indication as to whether the parameter is in the mode or not. 
[#4264](https://github.com/ISISComputingGroup/IBEX/issues/4264)
Have created an entry in:
https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev
---

Ticket4264 reflectometry ordered positions

---

base/uk.ac.stfc.isis.ibex.opis/resources/itc503/itc503.opi

Rearranges the heater set point to match the IOC.
Adds large text indicating the device is in local mode.
https://github.com/ISISComputingGroup/IBEX/issues/4033
N/A 
N/A
N/A
---

Ticket4033 itc

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/TargetPropertiesViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/TargetPropertiesTable.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/TargetPropertiesWidget.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/TargetPropertiesViewModel.java

Changed the configure device screen macro value table to work in the same way as the edit synoptic dialog, so the values can be edited directly in the table. Removed the counter-intuitive text box which this functionality makes redundant.
https://github.com/ISISComputingGroup/IBEX/issues/4345
Removed everything to do with the old value text box, and replaced with an alternative where relevant.
The [relevant documentation](https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Create-and-Manage-Device-Screens) on this still accurately describes the new functionality, despite the changes.
---

Ticket4345 macro value not editable in table

---

base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterHistoryPresenter.java

Fixed bug introduced by me in https://github.com/ISISComputingGroup/ibex_gui/pull/907 where an axis was being created even if it's not required.
No new axis is created when adding a plot to an existing axis.
---

Fixed bug where plotting axis was being created unnecessarily

---

base/uk.ac.stfc.isis.ibex.opis/resources/tti355.opi

1. PV name changes: Forgot to commit these to the branch before merging into master; master currently has a broken OPI in that the ON, OFF `OUTPUTSTATUS` buttons are pointing at the wrong record. `OUTPUTSTATUS` was updated to match against the Kepco.
2. Label change: Changed to have a more clear description as per a conversation with John.
[#3784](https://github.com/ISISComputingGroup/IBEX/issues/3784)

Ticket 3784 - Updated PV names

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin.xml
build/check_build.py

- Added a check which fails the build if the icon location pointer is incorrect
- Corrected the icon location
https://github.com/ISISComputingGroup/IBEX/issues/4537
---

Ticket4537 fail build if icon red square

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewConfigHandler.java

The behaviour of `setCurrentConfig()` changed as a result of block server changes, so its use here was now incorrect. Replaced by saving the new config and then loading it.
https://github.com/ISISComputingGroup/IBEX/issues/4605
---

Ticket4605 Fixed switch to new config not working

---

base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/NicosQueueContainer.java
base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/models/QueueScriptViewModel.java

Added the ability to drag and drop scripts in the queue.
https://github.com/ISISComputingGroup/IBEX/issues/3359
N/A
N/A
N/A
---

Ticket3359 Added drag and drop to NICOS script queue

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeModel.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/IDae.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/run/RunSummaryViewModel.java

Interact correctly with both TITLE:SP and TITLE to allow auto-population of title to work 
See ISISComputingGroup/IBEX#4140
* Setting a title containing @blockname@ results in block value appearing in title 
---

Add support for auto-title from blocks

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/DoubleListEditor.java

As title.
https://github.com/ISISComputingGroup/IBEX/issues/4647
N/A
N/A
N/A
---

Ticket4647 Fixed bug with being unable to reorder blocks in groups

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product

Make jaws manager much faster. The option I've added tells jython not to load all "site packages" (i.e. modules we've pip installed) every time it starts. I've checked the OPIs which use non-standard scripts, and they appear to load correctly with this option enabled.
https://github.com/ISISComputingGroup/IBEX/issues/4668
On master, point at NIMROD and open their jaws manager screen. Time this (on my machine it takes 10+ seconds).
On this branch, do the same. Should be less than 1s (not really measurable manually)
n/a, configuration change only
If anyone has ideas about how to automatically system test this I'm open to ideas. I think using squish will be hard because:
- Getting into the OPI layers from squish is fiddly
- It will be very prone to race conditions
I will add a manual system …

Add python argument not to import entire site module to each interpreter

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

Motor deenergise warning 
https://github.com/ISISComputingGroup/IBEX/issues/4602
1. Warning should appear for galil motors whose motor off deadband (see galil engineering view) is greater than -0.001 (i.e. 0 is not small enough) and who has automatically de-engise No.
OPI not needed
Not needed
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Galil-default-parameters
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Motors-Trouble-Shooting#the-axis-will-not-move-a-message-gets-put-in-the-log-of-begin-not-valid-with-motor-off
---

Add warning for motor-off deadband

---

base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/macros/tests/MacroViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/macros/MacroViewModel.java

Creating config without having to fill in macro values was causing an error and not end up saving the config. The config can now be saved without having to fill in the macro values and no errors from the block server.
[#4904] (https://github.com/ISISComputingGroup/IBEX/issues/4904)
-[ ] Does saving the config without macro values filled in for IOCs give any error on the block server?
-[ ] Does saving the config without macro values filled in actually save the config?
*Highlight and provide a link to any additions or …

Config now can be created without having to fill in macro values for IOCs

---

Jenkinsfile

Add disableConcurrentBuilds() (as in genie python) - may be cause of all these extra builds? No sure why it would start happening now though
---

Disable concurrent builds

---

base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/Activator.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Script generator pipeline was failling because it could not find Python when running tests, but it shouldn't be trying to start it. Stopping it from running these in tests.
---

Separate out activation of bundle from start of Python process

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/macros/MacroValueValidator.java

GUI Now validates the length of macro too
[#4934](https://github.com/ISISComputingGroup/IBEX/issues/4934)
- IOC = DFKPS, Macro = CALIB_FILE
- IOC = CCD100, Macro = DEV_NAME
- IOC = TRITON, Macro = RAMP_FILE_NAME
---

added new macro value validator check for validating length of macro

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi

Matplotlib window now instantiated with decent size upon creation.
[#5016](https://github.com/ISISComputingGroup/IBEX/issues/5106)
---

plot window to appear in decent size

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi

As an EMU scientist I want the calibrated danfysik to show me which calibration file it is using on the OPI.
This is an easy tweak, already hotfixed on EMU

Add calibration file to calibrated danfysik opi

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/templates/generator_template.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/test_generator.py

The muons wanted do_run to be renamed to runscript. As this is so early on and the name seemed generic enough we decided to swap this out.

Script gen run script

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
base/uk.ac.stfc.isis.ibex.opis/resources/matplotlib.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template.opi

Device specific documentation has been migrated off of github to the internal user manual. This PR is to update the links in relevant OPIs accordingly.
https://github.com/ISISComputingGroup/IBEX/issues/5112
Links to info pages from Matplotlib, Fermi Chopper and Kepco OPIs still work and lead to pages in the user manual.

Link to shadow instead of github

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java

Fixed the visibility of groups containing all hidden blocks. Found (again) during manual system testing.
https://github.com/ISISComputingGroup/IBEX/issues/3334
- When there are other blocks that are visible in the config, and show hidden is `false`, Groups containing all hidden blocks now _do not_ get displayed as a blank group in the panel
- When there are no other blocks that are visible in the config, and show hidden is `true`, Groups containing all hidden blocks now _do_ get displayed in the panel
/
/
/
---

groups with all hidden blocks behave correctly

---

base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plot.opi
base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plots_mode.py
base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plots_script.py

Add GUI logic to display counts or counts/ns (on Muons) or counts/us (on Neutrons). Builds on https://github.com/ISISComputingGroup/EPICS-isisdae/pull/64 which serves the EGU field correctly. 
First test counts/us and counts are specified correctly on the spectra plots axis (by changing the mode on the drop down box) for your "Neutron" instrument. Then perform changes specified in https://github.com/ISISComputingGroup/IBEX/issues/5116#issuecomment-581141361 and do the same.
Ensure that the value persists by building the client, running the built client and changing the mode of the spectra plots. Then close the client and reopen, check that the changes are persisted in the spectra plots axes.
https://github.com/ISISComputingGroup/IBEX/issues/5116
- The x axis is labelled as nanoseconds on …

Ticket5116 dae spectra plots ns

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServerVariables.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/Editing.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/ObservableEditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/ConfigEditing.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/adapters/UpdatedObservableAdapter.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/ClosableObservable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/ForwardingObservable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/TransformingObservable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pv/Closer.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/InstrumentUtils.java
base/uk.ac.stfc.isis.ibex.ui.banner/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/ConfigurationViewModels.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/ConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/ConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigDetailsDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/EditConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ConfigEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/UIUtils.java

Fix various memory leaks on editable configuration
https://github.com/ISISComputingGroup/IBEX/issues/5136
- Opening multiple configuration no longer fills up the mmemory
- (You can check) The number of Editable configuration is < 5 at al ltimes
-
Relying on memory test in squish
Will update debugging memory error sin the wiki
---

Ticket5136 memory leak

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini

The first commit (44df850) adds a button in the Script Generator panel to open the relevant page on the user manual.
The Java file was indented with a mix of tabs and spaces, so the second commit (30a3a6b) converts all tabs to spaces to avoid weird indentation in some editors.
The third commit capitalises the button text to be consistent with the rest of the UI.
https://github.com/ISISComputingGroup/IBEX/issues/5166
1. In the Script Generator panel of the IBEX client, a button labelled "Open Manual" is displayed next to the "Get Validity Errors" button
2. When clicked, the button opens the "Using the Script Generator" user manual page in a browser
3. The same button is dispayed and behaves in the same way in the standalone script generator
---

Add link to manual in script generator

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

The Eurotherm IOC had a bug where focus remained on the xy graphs zoom in functionality even when attempting to fill in values in the OPI that are not on the graph.
Bringing the xy graph to the front fixes this. No idea why, will make a ticket to investigate.
https://github.com/ISISComputingGroup/IBEX/issues/5203

Bringing xy graph to front to fix, not sure why it works

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

Auto-selects the default synoptic from the synoptic dropdown menu in the configuration edit dialog.
https://github.com/ISISComputingGroup/IBEX/issues/5155
- Create or load a config with a default synoptic
- Edit the config
- In the "Synoptic" dropdown menu, the default synoptic should be automatically selected
---

Populate dropdown with default synoptic

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/ReceiveBannerMessage.java

Changed `rsakey` from string to map because JsonDeserialisation converts `rsakey` to a dictionary in after migrating Nicos to python 3
[#4887](https://github.com/ISISComputingGroup/IBEX/issues/4887)
Nicos script server can run python 3 user scripts and is displayed correctly
Should pass previous unit test
---

rsakey changed to map because of migrating NICOS to python 3

---

build/build.bat
build/build_script_generator.bat

When running build.bat without the env variable python 3 set the python script is not run correctly. Set a default for build.bat of C:\Instrument\Apps\Python3\python.exe
---

Ensure python 3 is set to a default

---

build/build.bat

If you ran build.bat in the same terminal multiple times and mvnErr had been set at one point the build would exit after running maven with no errors. This clears mvnErr before running maven to prevent this happening.
---

Clear mvnErr before running maven again

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/build.properties

The script generator builds were broken because they were not copying across the correct resources, python_support should now be copied across, not defined_actions.
---

Copy across the right directory during build

---

base/uk.ac.stfc.isis.ibex.opis/resources/lakeshore372.opi

A dummy widget was accidentally added in an invalid place on the lakeshore 372 opi, this caused scrollbars to appear in a container when they shouldn't have.
This manually removes the badly-positioned dummy widget and adds it back in at the end of the file, where it should be.

Fix ls372 opi

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/CheckboxLabelProvider.java
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/StateLabelProvider.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/ControlCellLabelProvider.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundCellLabelProvider.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/SortableObservableMapCellLabelProvider.java

To test:
* Confirm code builds
* Confirm tables still work in the GUI
* Confirm less warnings of type inference

Removed some guessing of types from the DataboundTable hierarchy

---

base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini

Eclipse now shows memory monitor by default. Prevent this in config ini file.

Stopping eclipse displaying memory monitor by default

---

base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml

The script generator was attempting to pull in log4j (whose API has changed and is managed by the ibex logger). As the IBEX logger exports it, we don't need to have it in our script generator features.
To test (requires dependencies to be updated):
Build the script generator using build_script_generator.bat and run it. Confirm it works.

Remove log4j from feature requirements

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

When you switch script definition the help text should be updated. This somehow regressed after the last time I tested it, because the property names were changed. Change the property string to match and now it switches definitions.
To test:
- Switch between script definitions and check the help text updates

Fix switching listener property

---

build/build.bat
build/jenkins_build.bat

JRE is now copied every time `build.bat` is run, rather than just `jenkins_build.bat`.
When running `build.bat` the jre is copied into `built_client`.
---

Copy jre into the build as part of build.bat

---

base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller/zero_field_controller_basic_panel.opi

Changes the reference to the `STABLE` PV to `AT_SETPOINT` in the zero field controller OPI (see [linked PR](https://github.com/ISISComputingGroup/EPICS-ZFCNTRL/pull/8)). The field label has also been changed to "At setpoint" and made a bit larger to fit the extra text.
https://github.com/ISISComputingGroup/IBEX/issues/5190
- When running the updated IOC, the "At setpoint" field correctly displays the value of the `AT_SETPOINT` PV
---

Rename STABLE PV to AT_SETPOINT

---

base/uk.ac.stfc.isis.ibex.runcontrol/src/uk/ac/stfc/isis/ibex/runcontrol/internal/RunControlAddresses.java

Renames the constant to mirror the change in PV name.
https://github.com/ISISComputingGroup/IBEX/issues/5207
- The PV is correctly set when running with the modified name
---

Rename SUSPEND_ON_INVALID to SOI

---

base/uk.ac.stfc.isis.ibex.ui.reflectometry/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.reflectometry/plugin.xml

Fixes bug where ctrl-c would not work in reflectometry perspective
https://github.com/ISISComputingGroup/IBEX/issues/5387
CTRL-C should interrupt a script in both the scripting and reflectometry perspectives (note: it is the same script running in both)
n/a
n/a
n/a
---

Allow ctrl-C in reflectometry perspective

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/blades_script.py
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_base.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_diagram.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/more_detail_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/single_jaw_manager.opi
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsPanel.java

* Made all GEM jaw managers use blade_scripts.py.
* Prior to this fix, if the horizontal and vertical limits of jaw travel differed but the vertical and horizontal gaps were set equal, the gap on the GUI would not appear square as expected. This PR applies a scaling factor to the jaw heights/widths to correct this and also adds red lines to the GUI to indicate actual limits of travel on the shorter travel axis.
https://github.com/ISISComputingGroup/IBEX/issues/4732
* Gem_jaws_manager and Jaws device screens work as expected. Try setting vertical and horizontal motor limits of travel differently e.g. v. limit 50, h. limit 40, and setting the gaps equal e.g. v. gap 25 and h. gap 25 and make sure the gap looks square. Red lines should also appear indicating the limit of travel on the shorter …

Ticket4732 jaws aspect ratio

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/crisp/hgaps_CRISP.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/crisp/important_params_CRISP.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/crisp/sample_stack_CRISP.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_inout.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setPositionMacros.py
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/set_point_column_labels.opi

Changed Reflectometry front panel OPI so that:
> - Slit gaps and sample stack parameters are displayed on the reflectometry front panel OPI using the param_move.opi (same as all other parameters)
> - The layout is adjusted to reasonably fit everything
> - ~The "important parameters" panel is populated dynamically based on a tag given to reflectometry parameters at the config level~
> - The "important parameters" panel is now a linking container that can be swapped out in the future depending on the current instrument (same as slits and sample stack)
plus
- Compressed controls for individual parameters so that we can fit more of them in the available space on other instruments (e.g. POLREF: 5 slits, 6 sample stack axes)
-Increased number of parameters that can be displayed on the "All …

Updated layout

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

Allow user to tab across the script gen table.
https://github.com/ISISComputingGroup/IBEX/issues/5121
---

Ticket5121 script gen tabbing across table

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_uncalibrated.opi

Add a rule to the auto on/off settings on Danfysik OPIs to make them invisible when the DISABLE_AUTOONOFF macro is set to 1.
https://github.com/ISISComputingGroup/IBEX/issues/5268
* When DISABLE_AUTOONOFF is 1, the auto on/off enable/disable button and the "Sweep to 0 and power off" button are not visible
* They are visible when DISABLE_AUTONOFF is 0.
No unit tests for the GUI
No system tests
None
---

Hide danfysik auto on/off options if appropriate macro not set

---

base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

Fixes issue where table sorting was broken
To test:
* Start your instrument
* Start the GUI on the latest master
* Go to IOC -> Start/stop IOCs
* Click on one of the headings of the table
* The table should sort 
See https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/49
---

Sorting action now defaults to none

---

base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java

Removed call to load_script that did nothing
To test:
* Start the scripting perspective and confirm you can still call genie python commands through`g.begin()` and also through `begin()`
---

Remove dummy call to load_script

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Consoles.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/GenieOpenConsoleAction.java

Fixed some checkstyle warnings

fixed some checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java

Fixed tabbing on the script generator so that a new row is created when tabbing from the last editable column.
To test:
* Add an action to the script generator
* Click on a field to make it editable
* Continually tab across and confirm a new action is created when you get to the end of the row
See https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/57
---

Fixed tabbing for estimate column

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setPositionMacros.py

Needed to modify the script to make it work with reflectometry IOC in python 3. I'm guessing that the compressed/hexed message used to include some terminator and now it does not.
Related PR: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/293
https://github.com/ISISComputingGroup/IBEX/issues/4884
---

Fix refl OPI script

---

build/jenkins_build_script_generator.bat

Added multibranch pipeline in Jenkins to build script generator release version.
https://github.com/ISISComputingGroup/IBEX/issues/5418
- The build process assigns an identifiable release number to the stand-alone Script Generator.
- The build process copies the stand-alone Script Generator to the appropriate release folder.
- New Jenkins pipeline for script generator release build is available as `scriptgenerator_release` in  http://epics-jenkins.isis.rl.ac.uk/
The release folder is located in the share inside `script_generator_release`
*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to …

Set Different directory for script generator release build via jenkins

---

base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/GeniePythonConsoleFactory.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PythonInterpreterProviderFactory.java

Scripting console and Script generator to use system install of genie python and if not available, revert to using bundled python.
https://github.com/ISISComputingGroup/IBEX/issues/5463
---

Ticket5463 bundling genie python

---

base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi

See https://github.com/ISISComputingGroup/IBEX/issues/4569
* Open the aperture/waveguide OPI
* Confirm advanced tab cannot be selected and there is a tooltip explaining why
* Switch to manager mode and confirm you can select the tab
---

Ticket 4569: Disable advanced view when not in manager mode

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

While maven is happy building both specified target platforms, the eclipse IDE seems to default to using whichever is specified last. Specify windows last.
To review:
- Verify maven build still produces both `linux` and `win32` builds in `base\uk.ac.stfc.isis.ibex.e4.client.product\target\products\ibex.product`
- Verify you can launch from eclipse successfully after reloading target platform

Swap target platform order

---

base/uk.ac.stfc.isis.ibex.ui.configserver.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/tests/TempIocTest.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/TempEditableIoc.java

Prevent temporary IOCs from "writing through" to the underlying IOC object until they are saved.
https://github.com/ISISComputingGroup/IBEX/issues/5558
- Bug is fixed
- Added test would have caught the issue
Unit test added which replicated the bug and proves it is fixed. Should fail on old code.
Not added.
Not added.
---

Ticket5558 cancel saves macros

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/ReceiveSession.java
base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java

On reconnect actually restart the MessageParser thread to receive messages.
https://github.com/ISISComputingGroup/IBEX/issues/5561
Both before and after I have switched instruments and back the following occur:
- When I send a message through the message simulator in C:\Instrument\Apps\EPICS\ISIS\IocLogServer\master\dev-tools it appears in the IOC log
- When I trigger a log message in the DAE it appears in the DAE perspectives recent log messages
*Highlight and provide a link to any additions or changes to the …

Fix log issue by restarting correctly

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py

Squish was failing whilst trying to generate a script (http://epics-jenkins.isis.rl.ac.uk/job/System_Tests_Squish/). This was because we were no longer telling jinja2 where to load script definitions from. This PR adds the repo path where we get the definitions from.
N/A
I can generate a script and view the generated script when parameters are valid.
Was caught by a squish test!
---

Load scripts from repo fixing bug where we couldn't load them

---

base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.opis/check_opi_info.py
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

1. Added automated `opi_info.xml` checks as part of build which make sure the listed resources are valid
2. Corrected existing issues:
- changed `slit_motors.opi` to `jaws/slit_motors_4.opi` as old path was invalid
- removed `XY Shutter Arm Beam-stop` entry as the device was removed in [#4770](https://github.com/ISISComputingGroup/IBEX/issues/4770)
https://github.com/ISISComputingGroup/IBEX/issues/5522
- `opi_info.xml` does not contain windows-style paths (i.e. paths containing `\`)
- The files that `opi_info.xml` refers to should exist
- The file paths should be cased the same way on the filesystem and `opi_info.xml`, e.g. `jaws.opi` vs `JAWS.OPI` should fail.
- There is an automated test that checks the above conditions and is run as part of the build.
Created `class …

Add opi_info.xml checks as part of build

---

base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java

Changed the default location of genie_python within `PreferenceSupplier.java` to point to the Python 3 directory so that `sys.path` no longer outputs to the old `...Apps\\Python\\Lib...`
https://github.com/ISISComputingGroup/IBEX/issues/5591
`sys.path` contains `Python3` rather than `Python` directories:
e.g.: `'C:\\Instrument\\Apps\\`**`Python3`**`\\Lib\\site-packages\\genie_python'` (good)
and not: `'C:\\Instrument\\Apps\\`**`Python`**`\\Lib\\site-packages\\genie_python'` (bad)
N/A
N/A
N/A
---

Ticket5591 Update genie default location to Python3

---

base/uk.ac.stfc.isis.ibex.configserver.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/HasProtectedElementTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/MultipleConfigsSelectionDialog.java

Changed the Load Configuration dialogue so that there is no protected configurations warning message when there are none in the list. 
If at least one protected configuration is in the dialogue list, then the message will be displayed.
https://github.com/ISISComputingGroup/IBEX/issues/5062
- Warning message and icon are shown only when there is a protected config in the selection list
N/A
N/A
N/A
---

Display load config warning only when protected configs in list

---

base/uk.ac.stfc.isis.ibex.journal.tests/src/uk/ac/stfc/isis/ibex/journal/tests/JournalCalcTotalPagesTest.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalSearch.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer.tests/src/uk/ac/stfc/isis/ibex/ui/journalviewer/tests/JournalViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/models/JournalViewModel.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/NumbersOnlyListener.java

1. **Replaced the old spinner with new UI elements for page control:**
- Text label to show currently displayed entries out of total `e.g. Entries 16-30 out of 50`. 
Search filters are taken into consideration when displaying the total results.
- Buttons to navigate through the pages: `First, Previous, Next, Last`. Buttons will be greyed out when not relevant or pressing them would cause an out of bounds error (e.g. Next button on the last page).
- Text field displaying the current page; user can type in a page number to navigate there.
Field input is verified via listener to be numbers only. If desired page number is out of bounds due to it being too high, page will be set to last (page max). If desired page is out of bounds due to other reasons, users will be informed by message.
2. …

Ticket4479 journal viewer page number control

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
build/build_script_generator.bat

Rearranges imports so error is caught when git is not available
https://github.com/ISISComputingGroup/IBEX/issues/5700
None
None
None
---

Rearrange imports

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java

Sets the `__from_ibex__` variable to `True` in genie python when being opened from IBEX so that plots will be opened. 
ISISComputingGroup/IBEX#5583
See ticket
None
None
None so far
---

Ticket5583: Setting var in genie python when opening from ibex

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/ConfigInfoTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/SynopticInfo.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/DeleteComponentsDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/MultipleConfigsSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/RecentConfigSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/MultipleSynopticsSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/SynopticSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/dialogs/BasicSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/dialogs/SelectionDialog.java

Added "Description" column to the configurations and component list selection dialog tables.
(Load/Edit/Delete)
https://github.com/ISISComputingGroup/IBEX/issues/4800
* Name of configuration to show alongside the description before loading the configuration.
N/A
Manual testing: Open the Configurations Load/Edit/Delete or Components Edit/Delete selection dialogs, see that list table has two columns (Name and Description) of the config/component.
N/A
---

Added config descriptions column to dialog

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/ResetSelectionTextCellEditor.java

A hot fix that will reset the selection of a cell if it loses focus. Note that further docs and a better solution will be provided to call the ticket complete.
See https://github.com/ISISComputingGroup/IBEX/issues/5708
Fixes original issue and causes no new side effects
---

Ticket 5708: Set the selection of cell editors after focus leaves editor

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/sample_stack.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/sample_stack.opi

Minor changes for POLREF front panel OPI: 
- made PVs for height / height2 the right way around
- removed height2 for vertical mode
https://github.com/ISISComputingGroup/IBEX/issues/5459
OPI is correct
/
/
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectomtery-IOC-POLREF#sample-stack
---

Remove height2 for vertical mode. Fix PVs

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java

When filtering configs we should do it on the name not description, this was happening to work in some cases as people are lazy and set the description equal to the name. This was caught be a squish test.
To test:
* On master create a config that has the same name and description and switch to it
* Confirm it doesn't appear in the delete configuration dialog
* Change the description to not be the same as the name
* Confirm it does appear in the delete configuration dialog
* Switch to this branch and confirm it no longer appears in the dialog in either case
---

Filtering configs should be done on name, not description

---

base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi

Fixes "contol" to "communications" in Kepco OPI, found during ISISComputingGroup/IBEX#5851 
Relates to ISISComputingGroup/IBEX#5851
Typo is fixed
N/A
N/A
N/A
---

Fix typo in Kepco OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/stopMtrFromMtrName.py

Remove use of COORDX:MTR; Switch from COORD2 to COORD1 and COORD1 to COORD0
https://github.com/ISISComputingGroup/IBEX/issues/5865
- Sans2d scraper aperture motor stop works
- Sans sample changer opi uses correct PVs
---

Correct opi usage of motion setpoints

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/SURF/important_params.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/set_instrument_panels.py

- Add macro for setting matplotlib url (e.g. `ndxdemo:<port>` for remotely looking at the plot on `DEMO` )
- Make path separator OS agnostic
- Add "monitor in beam" parameter to important parameters panel for SURF

minor OPI fixes

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_uncalibrated.opi

Show polarity setpoint only when IOC is explicitly set to do so.
https://github.com/ISISComputingGroup/IBEX/issues/5296
- Polarity setpoint is hidden for standard DFKPS
- Polarity setpoint is shown for RIKEN DFKPS
/
/
/
---

Selectively hide polarity SP

---

base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryActivationParametersTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryCollimationParametersTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryConstantsTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryCorrectionsTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryErrorLogTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryFrontPanelTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryOpiTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryOtherParametersTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometryRedefineMotorsTargetView.java
base/uk.ac.stfc.isis.ibex.ui.reflectometry/src/uk/ac/stfc/isis/ibex/ui/reflectometry/ReflectometrySlitParametersTargetView.java

Updated docstrings in reflectometry OPI views to fix checkstyle warnings. (ignore whitespace changes for easier comparison)

fix checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/DeviceScreensModel.java

Explicitly sets the devicescreens to a sensible default. Previously we were relying on getting a disconnected event from the PV to initialise it but we were trying to get the value before we got this event.
See https://github.com/ISISComputingGroup/IBEX/issues/5995
* Start the GUI up pointing to a disconnected instrument
* Edit the device screens and confirm that the dialog now opens
* Confirm devicescreen behaviour unchanged when pointing to a connected instrument
---

Ticket 5995: Allow opening device screens on non-running instrument

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

See https://github.com/ISISComputingGroup/IBEX/issues/4334
To Test:
* Edit a configuration to add a very long description
* Save the configuration
* Confirm this long description appears in the load description selection dialog (you may have to resize the window to see it all)
* 
---

Ticket 4334: Removed arbitrary limit on description length

---

base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/internal/TestableObservable.java
base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/internal/VariablesTest.java

As a result of https://github.com/ISISComputingGroup/IBEX/issues/4019 or https://github.com/ISISComputingGroup/ibex_gui/pull/1230/files changed the defaultReaderRemote for the synoptic Variables class to an observable that concatenates values and units. The GUI pipeline was failing because the test for that method had not been updated to reflect the new behaviour. This PR also updates the test.
*Highlight and …

Fix failing test

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java

Adds an `insertionLocation` parameter to `CreateDefaultAction()` which is set to `null` if a user clicks `Add Action to end` or set to the insertion location if a user clicks `Insert Action below`. In `createDefaultAction()` the previous row's value (or last row's value in the case of adding an action to the end) is copied and applied to the new action.  
ISISComputingGroup/IBEX#6017
See Ticket
None modified
Squish test added
None, docs already exist for copyPreviousRow behaviour and this is a bug fix
---

fixing insert action copy previous row behaviour 

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/EditableIocsTable.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/EditPanel.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

Added tooltips for the auto-start/auto-restart/sim. level labels in Add IOC and column headers in the config table.
https://github.com/ISISComputingGroup/IBEX/issues/2046
As a user, I would like tooltips for the auto-start and auto-restart properties of IOCs to tell me what they do.
N/A
N/A
---

Added tooltips for auto-start/auto-restart/sim. level

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/PVSelectorPanel.java

Improve PV search speed when adding to block by using a timer to wait for user input to finish before starting the search.
https://github.com/ISISComputingGroup/IBEX/issues/5892
- Search is made a bit quicker by using a timer or similar method
- If the search text has not changed the function should not perform a search
N/A
N/A
N/A
---

Improve PV search speed/responsiveness when adding to block

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorJsonFileHandler.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Changed the extension in which script generator parameters files are saved from `.json` to `.sgp` (script generator parameters). 
Changed the extension filters in param. save/load dialogs to `.sgp` for saving and `.sgp`/`.json` for loading (to be compatible with param. files created before the change).
https://github.com/ISISComputingGroup/IBEX/issues/5371
1. Saving a parameters file in the script generator results in a file with a more meaningful extension
2. Loading parameters still works correctly with this new extension
N/A
N/A
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/The-IBEX-Script-Generator#saving-the-parameter-values-and-loading-back-up
---

Changed script generator parameter files from .json to .sgp

---

base/uk.ac.stfc.isis.ibex.ui.logplotter/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterHistoryPresenter.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/OpenLogPlotterPopup.java

When sufficiently zoomed out the databrowser averages data to save memory. Additionally, when it has no data it will assume the data stays constant, in the example linked in the ticket it averaged the data just before getting no data for a long period of time and so it assumed this average was the value for that time. This changes any added PVs to `RAW` mode, stopping the averaging
As the user zooms in this averaging should correct itself but it didn't seem to be doing this very well, I'm not sure why.
See https://github.com/ISISComputingGroup/IBEX/issues/6233
Also https://github.com/ISISComputingGroup/IBEX/issues/2177
I can't think of an easy way to test this
---

Ticket 6233: Use RAW requests on the log plotter data

---

base/uk.ac.stfc.isis.ibex.ui.scripting/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Consoles.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/ConsolesCountMonitor.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/GeniePythonConsoleFactory.java

Added a label in the GUI scripting toolbar to display the number of currently active consoles when there is more than one.
https://github.com/ISISComputingGroup/IBEX/issues/5597
There is an obvious indication in the GUI scripting toolbar of how many consoles are open
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/86
N/A
---

Added currently active consoles count when multiple consoles

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/action_bar.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/correction.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/full_opi.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_align.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_list.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_highlighted.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_with_cv.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/tab_constants.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/value.opi

Changed reflectometry OPI to disable controls reflecting the state of DISP fields on parameters indiciating whether writing to PV is allowed or not.
https://github.com/ISISComputingGroup/IBEX/issues/5900
If `.DISP` on a reflectometry parameter is 1:
- Setpoint field is greyed out
- Setpoint field is disabled
- Move button is disabled
OPI only
/
https://github.com/ISISComputingGroup/ibex_user_manual/wiki/Reflectometry-View#parameter-states
---

Disable controls on DISP

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_highlighted.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move_with_cv.opi

Display parameters when the sp mirrors rbv.
https://github.com/ISISComputingGroup/IBEX/issues/6273
For float value with and without characteristic value and emphasis:
1. rbv mirrors sp No, in beam Yes - show SP and move
2. rbv mirrors sp No, in beam No - show SP and no move button and out label
3. rbv mirrors sp Yes, in beam Yes - hide SP and move button show Mirrors RBV in place of SP 
4. rbv mirrors sp Yes, in beam No - hide SP and move button show Mirrors RBV in place of SP no out label
N/A opi change
N/A opi change
see ticket.
---

Hide controls when sp mirrors rbv and show message

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/ReceiveBannerMessage.java

Log if NICOS disconnects due to a version mismatch, rather than failing silently.
https://github.com/IsisComputingGroup/ibex/issues/6296
Message is logged if connecting to a server with mismatched nicos version
---

Add message if nicos version does not match expected version

---

base/uk.ac.stfc.isis.ibex.opis/resources/TPGx6x_common.opi

* Run a TPG 26X in RECSIM: `%PYTHON3% run_tests.py -t tpg26x -tm RECSIM -a`
* Set the pressure to `caput %MYPVPREFIX%TPG26X_01:SIM:1:PRESSURE 1e-6`
* Confirm that you can actually read this value on the OPI
---

Update TPG to use scientific notation if very small

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/openOPI.py

Fixes bug where the view motors button on the motion set points opi was opening an OPI with disconnected PVs.
To test:
* On master point a GUI at LOQ and open A2 on the synoptic
* Click `view motors` on the OPI (you may need to right click on it and select actions->Execute script)
* Confirm the motor details button is shown as disconnected
* Checkout this branch and confirm that the above no longer shows disconnected
---

Fixed open OPI script to pass through PV prefix

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi

The motion setpoints OPI stationary LEDs were pointing to the incorrect PVs showing a little pink box rather than the LED. This prompted a support call from nimrod.
---

Correct motion setpoints PVs

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
base/uk.ac.stfc.isis.ibex.opis/resources/galil/single_axis_params.opi

Increases the precision on MRES/ERES fields as they were taking the default precision of the motor (5 d.p) but often need to be set more precisely than this.
* Point your GUI at a running instrument, confirm the motor screen and galil engineering screens give more decimal places on the MRES and ERES
---

Increase precision on MRES

---

base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ActionsTableTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ScriptGeneratorSingletonTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/templates/generator_template.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/AbstractGenerator.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorContext.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorPython.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionsWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Added check for script definition having global parameters, and if it does, GUI ability to display and and set them.
https://github.com/ISISComputingGroup/IBEX/issues/5616
For updated script that contains `global_params_definition` see https://github.com/ISISComputingGroup/ScriptDefinitions/pull/4
- Upon loading a script definition with a `global_params_definition` dictionary in the script generator. Text boxes are available to enter values for all paameters defined in the dictionary.
- Enterring values that do not match the type set in the `global_params_definition` for that parameter leads to the text box being highlighted in red, and displays a tooltip explaining the validity error.
- The script can make use of the global parameters set in the script generator, both in estimating the …

Ticket 5616 added global parameters script generator

---

base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/ConnectionHandler.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java

See https://github.com/ISISComputingGroup/IBEX/issues/6351 
To test:
* Start a python script that will plot after some time e.g.
```
def sleep_then_plot():
from time import sleep
sleep(2)
g.adv.open_plot_window(True)
```
* Switch to a different perspective and confirm that a plot window does not open there
* Switch back to the scripting perspective and confirm it does open a window
* Confirm that after running such a script and switching to the refl perspective it will also refresh the plotting window there
---

Ticket 6351: Do not open plot outside scripting

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/dialogs/SaveScriptGeneratorFileMessageDialog.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Removed "Save Parameters", "Save Parameters As".
Renamed "Generate Script" to "Generate Script As", added new "Generate Script" to save to current file, or create a new one with the suggested name.
Updated squish tests: https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/101
https://github.com/ISISComputingGroup/IBEX/issues/6492
N/A
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/101
https://github.com/ISISComputingGroup/IBEX/pull/6610
---

Script Generator: Reformulate save and load parameters workflow

---

base/uk.ac.stfc.isis.ibex.ui.runcontrol/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/EditRunControlDialog.java
base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/RunControlEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/RunControlSettingsPanel.java
base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/RunControlSettingsTable.java

Created functionality for the ticket's acceptance criteria. There is now a message popping up on top to inform user about non-permanent nature of changes in Run Control. 'Additional' group was added to contain Show Wiki page button and button to open configurations menu. The button is greyed out if no block is selected.
https://github.com/ISISComputingGroup/IBEX/issues/6488
There is a message to this effect on the menu
There is a link to the user manual providing more detail on how the differences between the run controls
Optionally, there is a button that guides you to where you can edit the run control in the configuration
There are no unit tests, see [ticket #6639](https://github.com/ISISComputingGroup/IBEX/issues/6639)
There are no system tests, see [ticket …

Add feedback on Run Control screen

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/dialogs/QueueScriptPreviewDialog.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Added optional dialog with preview of the generated script.
If user chooses to preview the script before queuing, the preview dialog with the script will be displayed. The script can then be queued or cancelled.
https://github.com/ISISComputingGroup/IBEX/issues/4170
* Users can preview the generated script(s) before sending them to NICOS
N/A
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/105
https://github.com/ISISComputingGroup/IBEX/pull/6638
---

Added generated script preview when queuing script

---

base/uk.ac.stfc.isis.ibex.ui.reflectometry/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/InterruptScript.java

Attempt to interrupt active scripting console only if one exists.
https://github.com/ISISComputingGroup/IBEX/issues/6238
Pressing Ctrl+C before the scripting console is open does not freeze the GUI
N/A
N/A
https://github.com/ISISComputingGroup/IBEX/pull/6648
---

Interrupt script console only if it exists

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

Added a new section to the danfysik OPI to display when connected to a 9000 series danfysik, that properly displays the 9000 series' interlocks
https://github.com/ISISComputingGroup/IBEX/issues/6543
A new test for the danfysik 9100 has been added to the IOCTestFramework https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/475
---

Updated the Danfysik OPI to handle 9000 series danfysik

---

base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/widgets/SearchControl.java

Add time to the IOC log from & to date search filter, as before it was only checking the date.
https://github.com/ISISComputingGroup/IBEX/issues/5305
Messages can also be filtered by time.
N/A
N/A
https://github.com/ISISComputingGroup/IBEX/pull/6687
---

IOC Log: add time to search datetime filter

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorFileHandler.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/dialogs/SaveScriptGeneratorFileMessageDialog.java

When trying to open generated script file and Notepad++ is not found, display warning and open with the Windows Notepad.
https://github.com/ISISComputingGroup/IBEX/issues/6692
* Error message has been amended to give clearer information to user
* Optionally: Use normal Notepad instead and inform user they could/should obtain Notepad++
* There are tests for this
N/A
Not sure what is the best way of testing this, and if it's worth it. Let me know what you think
https://github.com/ISISComputingGroup/IBEX/pull/6699
---

Script Gen: handle missing notepad++

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi

Add new tab to EUROTHRM OPI to display millivolts (mV) for each sensor
If the sensor is not active, the millivolts will not be displayed for that sensor
Eurotherm: display millivolts somewhere
#6571
https://github.com/ISISComputingGroup/IBEX/issues/6571
- Within IBEX GUI, a user can view millivolts (mV) for active eurotherm sensors by selecting the "Display Millivolts" tab visible within the eurotherm device screen. Sensors which are not active are not visible.
- Accessing "Display Millivolts" tab is intuitive/easy to find
- "Display Millivolts" tab is user friendly (understandable)
NA
NA
NA
---

Add_mV_tab_EUROTHRM_OPI

---

base/uk.ac.stfc.isis.ibex.e4.product/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchAdvisor.java
base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchWindowAdvisor.java
base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java

https://github.com/ISISComputingGroup/IBEX/issues/6577
Added warning to opening multiple clients. This is accomplished using combination of:
1. Temporary files in an user/local/IBEX/tmp folder [more here](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Local-files-and-start-up)
2. Locking those temporary files to make sure files are not left-over after a crash
3. Detecting those files and checking for a lock at startup of every new instance of client
https://github.com/ISISComputingGroup/IBEX/issues/6577
New wiki page added https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Local-files-and-start-up
This can be helpful next time we want to change something in this area as now we have a temporary files folder
that can be re-used.
---

Ticket6577 multiple gui clients running give warning

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Changed dependency target from pydev to our pydev fork. Fork added to shadow.
http://shadow.nd.rl.ac.uk/ICP_P2/Pydev/
https://github.com/ISISComputingGroup/IBEX/issues/1154
1. Remove the following icons from the top of the console: pin console. (check the functionality of pin console first)
2. Remove the "select python type" dialog which appears when creating a new console.
3. Warn the user before he or she kills a console.
Most up-to-date version of PyDev fork needs to always be updated on shadow
http://shadow.nd.rl.ac.uk/ICP_P2/Pydev/

Ticket1154 Modify PyDev for IBEX

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorExpectedFinishTimer.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Added an expected finish time to script generator below the time estimate, the finish time is the current time + the time estimate
https://github.com/ISISComputingGroup/IBEX/issues/6483
The script generator has a finish time displayed beneath the time estimate.
Squish tests at https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/108
---

Added expected finish time to script generator

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DeleteComponentsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DeleteConfigsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/DeleteItemsDialogHelper.java

Added dialogs to confirm before deleting components or configs
https://github.com/ISISComputingGroup/IBEX/issues/6627
N/A
N/A
N/A
---

Added dialogs to confirm before deleting components or configs

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Created OPI for Wish Jaws but a couple of PVs are missing.
PVs that are connected are Vertical and Horizontal Gap and their setpoints.
The OPI is created based on the VI:  (located here: C:\LabVIEW Modules\Instruments\WISH\WISH Jaws).)
There is also a Setup Dialogue to set gaps which is written to the text file on LabVIEW. This gaps could be set via editing the text file directly which then can be seen in the Front Panel. However, WISH scientists do not use neither Setup Dialogue nor text file.
Also they added that:
"The jaws are jittering a bit and sometimes to get the right value you need to send a value that is a bit off and repeat the operation several times so actually we just set values in the VI and drive."
1. Populate "Experiment Type" menu, possibly create an enum PV for this.
2. …

Created OPI for Wish Jaws but a couple of PVs are missing

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi

Removed some unnecessary scrollbars on the Eurotherm OPI after INTER flagged this as an issue.

Resize height and fix tab0 xpos

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi

Now uses labels rather than text inputs for jaw readbacks as scientists (and us developers) were getting confused as to why setting a value in the RBV box was not setting a SP.

switching from text input to label for wish jaw readback values

---

base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi

Updated the OPI field values to reflect changes made in [Db refactor](https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/3) in EPICS_PearlPressure repository so that the OPI displays PV values
* [WIKI](https://github.com/ISISComputingGroup/IBEX/wiki/PEARL-Instrument-Details#pearl-notes)
* IOC PR that changes made in this PR are for: [Db_refactor](https://github.com/ISISComputingGroup/EPICS_PearlPressure/pull/3)
* Testing instructions:
* Checkout [main](https://github.com/ISISComputingGroup/EPICS_PearlPressure) in `C:\Instrument\Apps\EPICS\support\PearlPressureController\master` and run `make` to ensure they are up to date.
* Run the tests with `- a` flag to run IOC in simulation mode: `system_tests\run_tests.bat -a`
* Checkout this PR's branch `opi_refactor` in …

Update OPI Based on IOC Refactor

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosModel.java

Undo some local changes for stopping Nicos from trying to connect, that were accidentally committed previously. Fixes ibex_gui pipeline tests

uncomment nicos code

---

base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi

Adds motors moving flag to OPI. PV had already been implemented as part of earlier work.
Fixes https://github.com/ISISComputingGroup/IBEX/issues/7043
Fixes https://github.com/ISISComputingGroup/IBEX/issues/6765
https://github.com/ISISComputingGroup/IBEX/issues/6765
- `BUSY` pv is displayed on OPI
n/a/ opi only
n/a/ opi only
n/a/ opi only
---

Add BUSY pv to OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi

Adds a warning on the eurotherm OPI if the IOC is started but no channels have been configured
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7152#issuecomment-1163038700)
- Start the a eurotherm IOC with no channels configured (no `ADDR_x` macros), verify warning is present
- Start a eurotherm IOC with at least one channel configured (e.g. `ADDR_1=1`), verify warning is not present
n/a opi only
n/a opi only
n/a opi only
---

Add warning on OPI if eurotherm started with no channels configured

---

build/install_client.bat
build/install_script_generator.bat

Use /MIR flag on robocopy to avoid accidentally leaving stale files behind after a deploy.
https://github.com/ISISComputingGroup/IBEX/issues/7034
Old files are no longer left behind when a deploy "copies over" an old tree
---

Use /MIR flag on client install

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/MQConnection.java
base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java
base/uk.ac.stfc.isis.ibex.alarm/src/uk/ac/stfc/isis/ibex/alarm/AlarmReloadManager.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/CopyPerspectiveSnippetProcessor.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/FlashingButton.java
base/uk.ac.stfc.isis.ibex.epics.switching/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/InstrumentSwitchers.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pvmanager/PVManagerObservable.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java
base/uk.ac.stfc.isis.ibex.journal/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/widgets/SearchControl.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Set names for most threads in IBEX. This helps debugging as we can more easily tell which thread an update has come in on, or which threads are using excessive resources for example.
none
Most threads created by ibex have sensible names.
Note: some threads/threadpools are created by CSS/py4j etc and we cannot change the names of these.
---

Set names for most threads created by IBEX code, for easier debugging

---

.gitignore
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/ConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/EditableConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/GroupsTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Block.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableBlock.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableGroup.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/DisplayUtils.java

Preview blocks in config dialog before the config is saved
https://github.com/ISISComputingGroup/IBEX/issues/1357
- Create a config and a component with a block in it
- Add the component to the config, don't save yet
- Verify block is in config dialog
- Save the config
- Verify component block does not get saved in config's `blocks.xml`
Yes
---

Ticket1357

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosErrorState.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosModel.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/comms/ZMQSession.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/comms/ZMQWrapper.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ServerStatusViewModel.java

Don't log messages continuously to the GUI log file if NICOS cannot connect. This will now be an expected condition on many instruments which do not use NICOS.
Also fix a recurrent exception caused in the GUI by non-threadsafe code.
https://github.com/IsisComputingGroup/ibex/issues/7135
- GUI does not log repeated connection failures to NICOS
- GUI still logs the first connection failure after a working connection
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Running-Nicos
---

Ticket7135 nicos reliability

---

base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchWindowAdvisor.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/ManualHandler.java

I noticed a couple of instances where we were only printing, but not logging, exceptions. Exceptions should go to the log file so that any future issues can be debugged more easily.

Ensure exception stack traces are logged

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
base/uk.ac.stfc.isis.ibex.opis/resources/matplotlib.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template.opi
base/uk.ac.stfc.isis.ibex.opis/resources/weblinks.opi
base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/ManualHandler.java
base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini

Change links to https
See ISISComputingGroup/IBEX#7229
* links to help pages on user manual still work e.g. on kepco OPI and general ibex help link
---

Use https for links to user manual

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

Added minor warning label to 'DIP and max output lookup' in the Eurotherm OPI -  warns when DIP and max output lookup file is **not** the **default** and lookup **not on.**
[*Link to Ticket #4735*](https://github.com/ISISComputingGroup/IBEX/issues/4735)
- A message to remind the user when they change the default file but have not yet to turned lookup on
See: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/compare/Ticket_4735?expand=1
n/a
---

Ticket 4735

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java

The exceptions occurred due to the finalizer method of the BlocksMenu class trying to remove a listener which had already been disposed of if the menu was not open. 
There is a slight difference in the way that the 'edit host configuration/component' menu item is now greyed out instead of invisible when a user does not have write access to a block, though I think this is more clear.

fixing 'edit host configuration' menu item 

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_pressure.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_temp.opi

Added a percentage readout to show what % of the voltage limit is being used by the heaters on the pressure and temperature cards. This was requested by scientists that were mistakenly reading the "Power" value as a percent of the limit. 
Partially Fixes ISISComputingGroup/IBEX#6283
1. The percentage appears correctly on the settings screen of the temp and pressure cards. 
2. The readout style should match the other readouts related to voltage
3. The style matches the usual IBEX style guide. 
Added unit tests to check that the calculation is occuring correctly. 
N/A
---

Add % of Volt Limit to Pressure and Temp Cards on Mercury Cryostat GUI

---

base/uk.ac.stfc.isis.ibex.opis/resources/ttiplp.opi

Adds warning lights and a reset button to the TTIPLP Screen. Apparently the device would trip without anyone noticing, so this should make it much more obvious. 
Partially Resolves ISISComputingGroup/IBEX#7213
As a user, I am able to see if the device has tripped due to overvoltage or overcurrent, and reset the trip state, allowing the device to output again. 
Added tests for trip status when changing trip limits and the setpoints of the voltage and current. 
N/A
N/A
---

Add TTIPLP Trip Information to GUI

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/OpenLogPlotterPopup.java

Added message boxes to Beam Info and OPIs that warn when adding a PV to the Log Plotter if the Log Plotter perspective is disabled.
https://github.com/ISISComputingGroup/IBEX/issues/7133
See ticket.
---

Ticket7133 log plotter disabled notification

---

.gitignore
build/build.bat
build/build_script_generator.bat

Use local `.m2` cache directory.
This prevents conflicts if maven is updated in one project/branch but not another, and the `.m2` repo structure changes incompatibly between versions.

Use local .m2 location

---

base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
base/uk.ac.stfc.isis.ibex.ui.graphing/META-INF/MANIFEST.MF

Depend on `tyrus` directly via maven, rather than via a custom P2 site.
This was missed from dependency updates because the plotting ticket (which tyrus was added in) happened in parallel with dep updates.
Both methods *work*, but depending via maven is significantly nicer and makes it much easier to update dependencies etc later as we don't have to mess around with rebuilding custom P2 sites.

Depend on tyrus via maven rather than via custom P2 site

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

adding IOCNAME into mtr details page

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/comms/RepeatingJob.java

When the Script Server stops or crashes the `RepeatingJob` tries to send a message to a socket that is null and throws an `IllegalStateException`, this exception is caught inside the `run` method of the `RepeatingJob` but then gets rethrown. That exception seems to never be caught.
To reproduce:
- Start NICOS.
- Stop NICOS.
- There should be an uncaught exception stack trace in the console.
All relevant info is already logged or shown in the GUI, so the rethrow can safely be removed.
https://github.com/ISISComputingGroup/IBEX/issues/7483
I don't think adding any tests is necessary.
*Mention any automated tests or manual tests that you have added or modified, if …

Ticket7483

---

base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper_Master.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Added `TYPE` OPI macro, for each controller, which hides the park box for fermi choppers.
https://github.com/ISISComputingGroup/IBEX/issues/6100
---

Ticket6100

---

base/uk.ac.stfc.isis.ibex.ui.graphing/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.graphing/build.properties

Icons for [#7461](https://github.com/ISISComputingGroup/IBEX/issues/7461) were not linked to maven build so were not visible/behaving correctly.

Link matplotlib toolbar icons to maven build

---

base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibModelTests.java
base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibViewModelTests.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibCanvasData.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibCursorType.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibDragSelectionType.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigure.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigureViewModel.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibToolbar.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketModel.java

- Added zoom selection box
- Added different cursor styles for appropriate nav styles
- Added tooltips for each button on the toolbar 
Implemented tooltips rather than using the plot message as:
-  It responds quicker than setting the plot message via the websocket (e.g. `model.setPlotMessage()`) and then waiting for the `viewModel` to update it
-  Was more concise approach
Kept `MAX_DRAW_RATE_MS` at 100 instead of 50; does mean slightly slower response on faster machines for panning/drawing zoom selection box but gives a slightly more acceptable performance on the slower ones.
[Ticket #7461](https://github.com/ISISComputingGroup/IBEX/issues/7461)
See `.../graphing/tests/MatplotlibViewModelTests.java`
*Highlight and provide a link to any additions or changes to the documentation, if …

Ticket7461

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

Added a new grouping container to the motor details for Galils and Beckhoffs that shows the current error and has a button to open the engineering view. For Beckhoff there is a reset error button as well.
https://github.com/ISISComputingGroup/IBEX/issues/7542
---

Ticket7542

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

If an issue occurs in the Motion Setpoints code (like a duplicate name) the error is not immediately obvious when using the SANS Sample Changer OPI.
This adds a text update showing that error message.

Added motion setpoints error message to SANS sample changer OPI.

---

base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi

Add new moving indicator PV into the oscillating collimator OPI. 
[Ticket #7625](https://github.com/ISISComputingGroup/IBEX/issues/7625)
---

Add new moving indicator PV to osc. collim. OPI

---

.gitmodules

Adds `.gitmodules` metadata - not sure why this was missing? https://stackoverflow.com/questions/59633536/git-submodules-without-gitmodules-file#:~:text=If%20the%20.,half%2Dformed%20submodule%20is%20easier suggests taht a submodule without a `.gitmodules` file is broken.
This was causing git diff to always report a change.

Fix script_definitions submodule

---

base/uk.ac.stfc.isis.ibex.opis/resources/nimatro.opi

Updated NIMA Trough OPI to display low/high limits, readback, and setpoint all in one place for the user. This was a suggested improvement that wasn't included in original ticket, but to improve functionality and user experience.
https://github.com/ISISComputingGroup/IBEX/issues/7141

updated OPI to display high/low

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorEditingSupport.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/StringEditingSupport.java

Make script generator steps read only once they have begun execution
https://github.com/ISISComputingGroup/IBEX/issues/6922
[System tests](https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/133)
[Script definitions for tests](https://github.com/ISISComputingGroup/ScriptDefinitions/pull/9)
---

Ticket6922 script generator read only when excuting step

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Reduced clutter in script generator by moving some buttons into right click menu on the table itself
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7843)
---

Added rightclick menu to script generator

---

base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/TS2Observables.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/TargetStationTwoPanel.java

Two new PV's were added to the beam information tab: 
- TG:TS2:DMOD:BEAM:LIM
- TG:TS2:DMOD:CHRGCHNG:TIME
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7852)
---

Added PVs to beam information tab

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/displaying/DisplayBlockTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java

Extra line in hover tooltip that shows pv address.
https://github.com/ISISComputingGroup/IBEX/issues/7895#issue-1793152685
See ticket
Added a new unit test to check tooltip value
No system test
No change
---

Ticket7895

---

base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi

Updated the OPI to update PVs directly from entering in Values to the text fields, rather than having to push a "Set" button to do so. 
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7882)
Open aeroflex in Device Screens, after adding the IOC in configurations within IBEX, and then Run IOC, and then check that Carrier Frequency Values and RF Level can be changed by entering in a value from the left. It should update into the group on the right of the OPI called "Readout Parameters"
System tests will need to be reworked entirely for the Aeroflex, as several recent tickets have made significant changes to the IOC.
*Highlight and provide a link …

Removed set buttons for RF and CarFreq, pointed fields at appropriate PVs

---

base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2700/keithley_scanner_values.opi

added missing connection to LED PV on keithley 2700
Use this following command in an EPICS terminal to switch status of the scanner from on to off:
caput TE:NDW2555:KHLY2700_01:SCAN:STATE:SP 0
caput TE:NDW2555:KHLY2700_01:SCAN:STATE:SP 1
---

added missing connection to LED PV

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelDelay.opi

I added some simple rules to the set buttons in `ChannelDelay.opi` that disable the button 
- if the inputs are incomplete (i.e. there is no channel link set) or 
- if the value is of wrong format (e.i. not a number) or
- if the values of delay are out of the supported range based on the manual (0 - 2000 sec)
[#7891](https://github.com/ISISComputingGroup/IBEX/issues/7891)
---

Ticket7891 dg645 input

---

base/uk.ac.stfc.isis.ibex.alarm.tests/src/uk/ac/stfc/isis/ibex/alarm/tests/AlarmSettingsTest.java
base/uk.ac.stfc.isis.ibex.alarm/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.alarm/src/uk/ac/stfc/isis/ibex/alarm/AlarmCounter.java
base/uk.ac.stfc.isis.ibex.alarm/src/uk/ac/stfc/isis/ibex/alarm/AlarmSettings.java
base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.e4.client/authorization.conf
base/uk.ac.stfc.isis.ibex.e4.client/jaas.conf
base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.e4.product/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/Application.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/AlarmButtonViewModel.java
base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
base/uk.ac.stfc.isis.ibex.opis/resources/Alarm/AlarmHistory.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Alarm/AlarmTable.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
base/uk.ac.stfc.isis.ibex.ui.alarm/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.alarm/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.alarm/src/uk/ac/stfc/isis/ibex/ui/alarm/AlarmHistoryView.java
base/uk.ac.stfc.isis.ibex.ui.alarm/src/uk/ac/stfc/isis/ibex/ui/alarm/AlarmTableView.java
base/uk.ac.stfc.isis.ibex.ui.alarm/src/uk/ac/stfc/isis/ibex/ui/alarm/AlarmView.java

* Add alarm history and table to Alarm perspective
* Allow alarm acknowledgememnt and disable
* Alarm counter is orange and not flashing rather than red and flashing if unacknowledged alarms that are no longer in alarm  
Note that building the client is not dependent on the CSStudio / EPICS-CSS changes - these just build a new separate product, everything else needed by GUI is already present and unchanged
A gui is built from this PR by  `ibex_gui_pr_pipeline` and deployed to  `Kits$\CompGroup\ICP\Client_E4\branches`
See ISISComputingGroup/IBEX#7943
See description
*Mention any automated tests or manual tests that you have added or modified, if applicable. The …

Ticket7943 alarm history

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi

Changed the hue of the fault RED colour for the LEDs in Fermichopper. 
https://github.com/ISISComputingGroup/IBEX/issues/7863
Fermichopper fault lights are a clearer/brighter RED than before.
---

Changed fault LED red colour

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

A <value> and <entry> tag in the opi_info.xml were missing closing tags. This was breaking the GUI so required changes have been made. 
N/A - Flash review requested.

Fixed missing closing tags in opi_info.xml

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adding labels into the right hand side displays, to make it obvious that they correspond to left hand side setpoints.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7892)
N/A
N/A
---

Added labels to DG645 right displays

---

base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaModelObject.java
base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java

Show IOC connected to COM ports in Moxa table.
https://github.com/ISISComputingGroup/IBEX/issues/7896
Make sure the above is true.
To test:
- Make sure your EPICS server is running
- Open `Moxa Ports` perspective
- Change PORT macro of IOCs in `Configuration > Edit COnfiguration > IOC > Select and Edit IOC`

Ticket7896 iocs in use

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi

DG645 updated to remove fields for DELAYUNIT PVs after DELAY PVs. The DELAY PV will now have a dynamically updated EGU that can be used to show the units after the value so the extra field is no longer necessary.
[#7887](https://github.com/ISISComputingGroup/IBEX/issues/7887)
The OPI should display units following the value via a single PV in the delay readback components of the DG645 OPI.
Check that the delay readback components are showing a delay value followed by the units, and that this is provided by only the DELAY PV. (**Note**: The Ticket7887 branch changes to the dg645 ioc need to be applied for the intended functionality to be displayed)

DG645 Delay Generator - Add units to Readback Delay (real changes)

---

base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi

DISABLE fields have been added to the .db file records which scan every 2 seconds, this is switched ON or OFF via the 'Local' and 'Remote' buttons on the OPI. 
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7878)
---

OPI updates to Aeroflex - Remote and Local Button

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/hgaps.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/important_params.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/INTER/vgaps.opi

- Removed references to obsolete Slit 4 on front panel
- Added Button for S3 beam blocker mode to front panel
- Added Button for Monitor 3 In/Out toggle to front panel
https://github.com/ISISComputingGroup/IBEX/issues/8061
see ticket
N/A
N/A
N/A
---

remove S4 and add Monitor3 on front panel

---

base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/PanelViewModel.java

There was an issue where Experimental Control where you could can the variables of other machines remotely.
I have added a clause that prevents the user from changing it unless it is on the localhost machine
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8011)
1. The instrument's Experimental Control panel is greyed out whilst the instrument is in various statuses - RUNNING, STEP UP
---

DAE remains grey if the main is not Localhost

---

base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/EnumEditingSupport.java

Added dropdown fix that makes it easier to open a number of dropdowns in the GUI. Specifically any that use the class `EnumEditingSupport` in `uk.ac.stfc.isis.ibex.ui.widgets` in `ibex_gui`.
[8069](https://github.com/ISISComputingGroup/IBEX/issues/8069)
---

Ticket8069_apply_enum_dropdown_fix

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java

This is needed for the squish test object map to find the combo box. (It is looking for a box that has the label widget on its left)
---

Place script definition selector in the same container as the label

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/Constants.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/IBEXButtonFactory.java

Script generator now transfers/loads actions and parameters whenever possible on a script definition change. Those that cannot be transferred are initialised to their default value.
I added a checkbox to enable/disable this feature because a lot of our testing was relying on the old behavior and it seemed useful to enable the user to turn this feature on/off. By default it is on.
https://github.com/ISISComputingGroup/IBEX/issues/5496
*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to help the …

Ticket5496_script_gen_load_params

---

build/build.bat
build/build_script_generator.bat

Same fix as [CS-Studio](https://github.com/ISISComputingGroup/isis_css_top/commit/98811562d58b989ef096087ec1f269165763d0f4) that was causing build to break.

set JAVA_TOOL_OPTIONS env variable to disable CEN header checks

---

build/build.bat

May be cause of "The process cannot access the file because it is being used by another process" with .lock file in .m2 repository

disable parallel build for the moment

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

Added a warning label that notifies the user that motor values can be changed but won't persist.
Meaningful changes start at line 3971. The other changes are due to styling differences.
https://github.com/ISISComputingGroup/IBEX/issues/8285
---

Add warning label

---

base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target

remove the older version from the target platform as it was breaking the build 
to review build.bat and see that it now passes

fix build - nebula.visualization duplication issue in target platform

---

base/uk.ac.stfc.isis.ibex.opis/validate_opis.py

Remove all references to Six
[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/8297)

Remove usage of six

---

base/uk.ac.stfc.isis.ibex.opis/resources/CAENv895.opi

Instead of a hard-coded number of cards, the OPI now looks up the number of required cards by the IOC. Additionally, adds an LED to each card to display status reads added by an earlier flash review.
[Ticket 8457](https://github.com/ISISComputingGroup/IBEX/issues/8357)

Ticket 8357 allow multiple crates and cards

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product

Disables zip64 field validation for jython.
This is needed to successfully launch IBEX from newer eclipse IDEs, and likely needed in order for future updates to eclipse framework.
This had previously been added to the maven build here https://github.com/ISISComputingGroup/ibex_gui/blob/master/build/build.bat#L31 but it is also needed at runtime from the IDE (and likely if we were to update our eclipse framework version too).
*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to …

Disable Zip64 validation for jython

---

base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi

Fixes commit https://github.com/ISISComputingGroup/ibex_gui/commit/670841c2fa5705f21438d340a6624a427b85a45e which seemed to have gone in without code review.
Noticed by Cryogenics on WISH and LET
Needs patching to all relevant instruments

Fixes 670841c2fa5705f21438d340a6624a427b85a45e

---

base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py

Demote font definitions check to a non-strict test
This will still be flagged on dev machines, but not checked by the build server. The build server doesn't have an EPICS checkout which is necessary to run this test.

Demote font definitions check to non-strict

---

base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/TS2Observables.java

to test this, before checking out see that right-clicking this PV in the beam status view gives the wrong PV to add to a config or add to log plotter. this should fix it.
---

small typo in beam status pvs

---

base/uk.ac.stfc.isis.ibex.opis/resources/envmon.opi

- Changed OPI such that if sensor A is not present sensor B's container is moved to the left where sensor A's would be if it was connected. For visual appeal
- Changed the error message that appears if neither sensor is connected so that it correctly guides the user to change the config. (Had the machine name in place of the ioc name)
[Ticket8465](https://github.com/ISISComputingGroup/IBEX/issues/8465)
[Original ticket #8130](https://github.com/ISISComputingGroup/IBEX/issues/8130)
---

Ticket#8465 Fixed visual changes in Environment Monitor OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds the CRATE macro (new to the CAENV895 OPI) to opi_info.xml
CAENV895 OPI opens with default crate 0
---

Add CAENV895 CRATE macro

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java

Now that we have added `ibex_bluesky_core` as a `genie_python` requirement, it also makes sense to make the `RE` available by default in the IBEX UI.
https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/15

Add RE = get_run_engine() as a default GUI initialization command

---

base/uk.ac.stfc.isis.ibex.opis/resources/chipir_filter_set.opi
base/uk.ac.stfc.isis.ibex.opis/resources/chipir_xyz_table.opi

This fixes a couple of things needed for CHIPIR - 
- renames "shutter" to "secondary shutter" on filters opi 
- adds individual stop buttons and a stop all which puts 1 to all 3 motors `.STOP` fields
once this is merged i'll patch onto CHIPIR.

CHIPIR snags - xyz table add stop buttons, filters rename to secondary shutter

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi

widens the error box for error in the diagnostics view of thebasic motor screen. 
on a beckhoff there's a reset error button which actually goes over the top,but this is OK because the text is left-aligned and will never be more than 5 characters.

show more of motor error message

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupTableViewer.java

This PR fixes [the ticket](https://github.com/ISISComputingGroup/IBEX/issues/8568)
To replicate the issue, go to DAE screen, "Experiment Setup" Tab and click on the "Periods" subtab.
---

Fix for array index out of bounds

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/Jaws.opi

Added fields to Jaws OPI to set the vertical and horizontal gap minimum limits.
[Ticket](https://github.com/ISISComputingGroup/IBEX/issues/8505)
The check_opi_format.py should be successful
---

Added vertical and horizontal gap limits

---

base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/Application.java

Recieve the following error: 
'The type Java17SealedInterfaceImpl may have only one modifier out of sealed, non-sealed, and final'
@Tom-Willemsen suggested to remove 'Final' from the line in question, within Application.java
---

removed final from application.java

---

base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/ChannelUtilities.py

Previously this used `getString` which is format-limited to printing 100 items in CS-Studio.  See [source code](https://github.com/ISISComputingGroup/cs-studio/blob/776ca26fb97c16816812b3ea27058ce86ab47f28/applications/opibuilder/opibuilder-plugins/org.csstudio.simplepv/src/org/csstudio/simplepv/VTypeHelper.java#L59).
Instead of requesting CS-Studio to human-format an array and then immediately unformatting it, just request the unformatted data in the first place...
[8660](https://github.com/ISISComputingGroup/IBEX/issues/8660)
Possible to select up to the maximum number of channels in the summary tab of the HVCAEN OPI.
---

Use PVUtil.getStringArray to get a string array

---

base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/RIKEN_magnet_PSUs.opi

Corrected PV prefix of trigger PV for Kickers 'icon' on OPI.  Was mistakenly left with local prefix during development.
---

Do not use local PV prefix for trigger PV

---

base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/TS1Observables.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoView.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/TargetStationOnePanel.java

(as per https://github.com/ISISComputingGroup/WebDashboard/issues/110 and https://github.com/ISISComputingGroup/EPICS-VMS/pull/3)
release notes: https://github.com/ISISComputingGroup/IBEX/pull/8686
to review check out, build the gui (eclipse or maven) and check that the EPB1 and Muon beam current are shown in the beam status view.

add muon and epb1 beam current fields to beam status view

---

.github/dependabot.yml
.github/workflows/lint.yml
base/uk.ac.stfc.isis.ibex.opis/requirements.txt
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_energyspec.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_event_energyspec.opi
base/uk.ac.stfc.isis.ibex.opis/resources/LITRON_POWER.opi
base/uk.ac.stfc.isis.ibex.opis/resources/ldens3300.opi
base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi
base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/magnetometer_row.opi
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/requirements.txt
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_git_utils.py

We can do various "pre-flight" checks/lints in GHA, without waiting for a full maven build to go through on the slowest build server. This makes the feedback loop much faster.
Migrating the full build / deploy process is harder & I'm declaring that out-of-scope

Check opis on GHA

---

base/uk.ac.stfc.isis.ibex.opis/resources/chipir_collimator/chipircollimator.opi

as requested by scientists. This takes up quite a lot of space but is really the only screen they look at most of the time. 
to test, check this branch out, build a gui and point to CHIPIR and look in their device screens. 
release notes: https://github.com/ISISComputingGroup/IBEX/pull/8708

CHIPIR: put filters on collimator screen

---

base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi

TC_01 was not set - set this. It'll never be TC_02 so just hardcode it as `$(TC)`.
to review, check out master and build a gui, point instrument to INTER and see that the TC macro is not defined when looking at their "inter tank" screen, then check this out and see that its fixed.

fix axis errors view on inter beckhoff screen

---

base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi

add inclinometer reading

---

.github/workflows/lint.yml
base/uk.ac.stfc.isis.ibex.activemq/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.feature.css/feature.xml
base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.opis/check_opi_format_tests.py
base/uk.ac.stfc.isis.ibex.opis/requirements.txt
base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target
base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/CheckboxLabelProviderTest.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
base/uk.ac.stfc.isis.ibex.ui.widgets/.settings/org.eclipse.jdt.core.prefs
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/CheckboxLabelProvider.java
build/build.bat
build/build_script_generator.bat
build/copy_in_maven.bat

https://github.com/ISISComputingGroup/IBEX/issues/8597
---

Dependency update

---

base/uk.ac.stfc.isis.ibex.opis/resources/litron.opi

Added a stale indicator to the LITRON opi that should be lit red when the wavelength value is stale, and off otherwise.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8687)

And stale light to opi

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/Constants.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java

Reorganised script generator buttons so they take up less space, and ensured they don't resize when the window is resized.
https://github.com/ISISComputingGroup/IBEX/issues/8826
---

Fixed scaling issues with script generator buttons
