ISISComputingGroup/ibex_gui

base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java

MUONFE now appears in the Instrument drop down (Ibex->Switch Instrument)

Ticket 1043, added MUONFE to list of instruments

---

base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/Instrument.java

Under IBEX->Switch Instrument, instruments are now sorted alphabetically, with localhost still at the top  of the list.
Please review pull request ISISComputingGroup/ibex_gui#196 before reviewing this one.

Ticket 1096 Instruments sorted alphabetically

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/McrNewsPanel.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/StatusPages.java

To test:
- Check MCR news displays correctly and refreshes every 30 seconds

Ticket1068 mcr as simple text

---

build/jenkins_build.bat

To test:
* Jenkins should create a symlink BUILD_LATEST to point at the most recent client build

Jenkins should now create a symlink to most recent build

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java
base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/ModelObject.java
base/uk.ac.stfc.isis.ibex.runcontrol/src/uk/ac/stfc/isis/ibex/runcontrol/EditableRunControlSetting.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/RunControlEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/RunControlSettingsPanel.java
base/uk.ac.stfc.isis.ibex.ui/src/org/eclipse/wb/swt/SWTResourceManager.java

Reverts ISISComputingGroup/ibex_gui#210

Revert "Added runcontrol indicator colours in the block tables"

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper.opi

Uses the new PV names
ISISComputingGroup/IBEX/issues/1166

Mk3 opi correction

---

base/uk.ac.stfc.isis.ibex.ui.dae/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/DaeView.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumPlot.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumView.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/Utils.java

Also change axes titles.
Update data when set plot button pressed

Make graph update on X and Y change of data

---

base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/list/InstrumentListObservable.java

When the instrument is switched, the content of the instrument list PV is logged.
The log message appearing when the instrument list was not filled correctly was pointing at a parsing error.  I have now noticed that the observables indicate that they are connected (in the while loop) before the value from the lowest-level observable (now called instrumentsPV, the one corresponding to the json string of the PV) is read properly, i.e. this string is still null. Most of the time this string then gets read before we proceed with querying the list of instruments, but maybe sometimes the string is still returned as null, probably causing the parsing error. I guess this would be down to random delays in dealing with channel access, as it works most of the time, but not all the time.
I have moved …

Ticket 1219: log instr list pv content

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/McrNewsPanel.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockRowCellDecorator.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/IocRowCellDecorator.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/macros/IocMacroDetailsPanel.java
base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/widgets/LogDisplay.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/component/ComponentDetailView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/BasicComponent.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/GroupView.java
base/uk.ac.stfc.isis.ibex.ui.weblinks/src/uk/ac/stfc/isis/ibex/ui/weblinks/WebLinksPanel.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/VerticalGradientComposite.java

I've removed all instances of "new Font(" and "new Color(" in the gui code, except within the SWTResourceManager itself.

Ticket1163 font resource leak

---

base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/internal/VariablesTest.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/SynopticModel.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/internal/Variables.java

Changed unit tests. Please take a look at the source code.

Ticket1179 unit tests for synoptic variables

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/filters/InterestFilters.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/filters/SourceFilters.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/PVSelectorPanel.java

Changes to allow for filter values to be perpetuated as in https://github.com/ISISComputingGroup/IBEX/issues/1243
Before checking out, to see original behaviour:
From either the synoptic or the add block launch the PV Selector dialog (Select PV buttons), every time you launch the screen it will show the PVs From "Active IOCs" with an Interest Level of "High". Change the values within the dialog, and open it from either location again, and the default values will be displayed. There are a number of combinations for this but a single test would be along the lines of:
Start IBEX client > Configuration > Edit Current Config > Blocks > Add Block > Select PV, note the Active IOCs and High selections, change these to Config IOCs and Medium, Cancel the dialog, Select PV again and note that the …

Store a selected value in the enums

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/component/ComponentDropListener.java

https://github.com/ISISComputingGroup/IBEX/issues/1244

Ticket1244 synoptics added to end

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditCurrentConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/LoadConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigSelectionDialog.java

https://github.com/ISISComputingGroup/IBEX/issues/1245

Ticket1245: Edit Configs Not Showing Current

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java

https://github.com/ISISComputingGroup/IBEX/issues/1148

Ticket 1148: Remove blocks from group when deleting group

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockDetailsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java

https://github.com/ISISComputingGroup/IBEX/issues/1164

Ticket 1164: Add validation on dialog creation

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditCurrentConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockDetailsViewModel.java

To test:
Check that the all checkstyle warnings I introduced in #238 and #239 are fixed

Fixed some checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

https://github.com/ISISComputingGroup/IBEX/issues/1242

Ticket1242: Fixed nebula repo link

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumPlot.java

See ticket https://github.com/ISISComputingGroup/IBEX/issues/1273

Swap DAE Spectra Axis Labels

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayConfiguration.java

ISISComputingGroup/IBEX/issues/1269

Ticket1269 stop empty groups from appearing

---

base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/internal/VariablesTest.java

The broken tests were in ibex.synoptic.tests. Should be fixed now

Ticket1290: fixed broken unit tests

---

base/uk.ac.stfc.isis.ibex.opis/resources/attenuator.opi

Changed CLOSE:SP to CLOSED:SP to match the PVS in the file
Relates to https://github.com/ISISComputingGroup/IBEX/issues/1292

Update Name for PVs

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java

To test, simply switch to IMAT. The current configuration (called IMAT) has enough blocks and groups to see this.
(otherwise create a configuration with lots of blocks and lots of groups)

Ticket 1291: reduced the number of rows by 1

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/BlocksTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockFactory.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/DuplicateBlockNameException.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlocksEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java

https://github.com/ISISComputingGroup/IBEX/issues/1254

Ticket1254 config not edited before block dialog accepted

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

ISISComputingGroup/IBEX/issues/1349

Ticket1349 dates in summary to labels 

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/DuplicateBlockNameException.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamStatusPanel.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamStatusView.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/McrNewsPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java

Added comments and such to get rid of checkstyle warnings introduced by the merge of https://github.com/ISISComputingGroup/ibex_gui/pull/249, https://github.com/ISISComputingGroup/ibex_gui/pull/255
Fixes https://github.com/ISISComputingGroup/IBEX/issues/1369
Jenkins does not return checkstyle warnings for this PR.
---

fixed checkstyle warnings.

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/SynopticPreview.java

ISISComputingGroup/IBEX/issues/1352
Changed to have just one "OK" button.

Ticket1352 synoptic preview duplicate buttons 

---

base/uk.ac.stfc.isis.ibex.devicescreens.tests/src/uk/ac/stfc/isis/ibex/devicescreens/tests/xmldata/DeviceScreensXmlProvider.java
base/uk.ac.stfc.isis.ibex.devicescreens.tests/src/uk/ac/stfc/isis/ibex/devicescreens/xml/tests/XmlUtilTest.java
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/xml/XMLUtil.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/internal/Variables.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/xml/XMLUtil.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/Activator.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/DeviceScreensView.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/Panel.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/Perspective.java

Fixed some checkstyle warnings
###To test
ISISComputingGroup/IBEX#1395
Check that the warnings are fixed
---

Ticket 1395: fixed checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeModel.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeWritables.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/IDae.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/pv/Channels.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/channels/BooleanChannel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/run/RunSummary.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/run/RunSummaryViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/views/DashboardView.java
base/uk.ac.stfc.isis.ibex.ui.experimentdetails/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/ViewModel.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/observable/BooleanWritableObservableAdapter.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/observable/StringWritableObservableAdapter.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/observable/WritableObservingTextBox.java

NOTE: While working on this ticket I have discovered that the PVManager does not properly handle writing values of type Boolean on ChannelAccess, which should be written as a numeric values 0/1 (e.g. using LongChannel) instead. We should find an appropriate place to record this for future reference.
Added a checkbox to the DAE Run Summary Tab that is wired up to a newly created PV in the ISISDAE IOC intended to be used for toggling visibility of the Run Title in the dataweb dashboard page.
###To test
Fixes https://github.com/ISISComputingGroup/IBEX/issues/1374
To Test: 
1. run ISISDAE IOC (make sure you have the latest version including the newly added PV, see comments)
2. camonitor %instrument prefix%:DAE:TITLE:DISPLAY
3. check / uncheck the box in the DAE Run …

Ticket1374 toggle experiment title visibility

---

base/uk.ac.stfc.isis.ibex.ui.logplotter/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/EmptyLogPlotterView.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/LogPlotterDisplay.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/Perspective.java

Fixes https://github.com/ISISComputingGroup/IBEX/issues/1325
###To test
* Start up IBEX and go to the log plotter perspective
* Confirm a sensible label is displayed
* Create a plot, confirm label disappears
* Close plot, confirm label reappears
* A descriptive label appears in the blank log plotter screen
---

Label on blank logplotter

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/build.properties

Icons are now in tyco build.
###To test
https://github.com/ISISComputingGroup/IBEX/issues/1426
1. Build tyco build
1. Run GUI ensuring synoptics have icons
System tests should now pass.

Add icons into tyco build

---

base/uk.ac.stfc.isis.ibex.opis.tests/src/uk/ac/stfc/isis/ibex/opis/tests/desc/OpiDescriptionTest.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/OpiDescription.java
base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/model/desc/TargetDescriptionTest.java
base/uk.ac.stfc.isis.ibex.synoptic/.checkstyle
base/uk.ac.stfc.isis.ibex.synoptic/.project
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/Property.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/TargetDescription.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/model/SynopticViewModel.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/properties/TargetPropertiesDescription.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/properties/TargetPropertyTable.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/properties/TargetPropertyValue.java

Fix bug.
###To test
https://github.com/ISISComputingGroup/IBEX/issues/1438
See ticket

Ticket1438 set macro value on old synoptics

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Following renaming of the Lakeshore218 IOC to LKSH218, the GUI itself doesn't need any special change apart from updating the example IOC name in the macro description for the synoptic OPI.
###To test
ISISComputingGroup/IBEX#1414
The GUI refers to the IOC with its new name
---

Ticket 1414: updated example IOC name in OPI info file

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/CalculationMethod.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/TimeChannels.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/TimeRegimeMode.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/TimeRegimeRow.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/TimeUnit.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetupViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsViewModel.java

https://github.com/ISISComputingGroup/IBEX/issues/1274
Can now select between time channel settings from file or from parameters specified in GUI.

Ticket1274 time channel settings in dae tab (GUI)

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsViewModel.java

Added a blank option to the table selection drop down menus so that there is always at least two options. Previously, selection events would not be registered if there was only one file in the list (even if it was different to the one currently saved in the DAESETTINGS PV), the user thus running the risk of being unable to change the table files. 
Also contains the following minor changes:
- Combobox now stretches to fill window (prevents error message from overflowing)
- Fixed path typo in error messages
https://github.com/ISISComputingGroup/IBEX/issues/1464
https://github.com/ISISComputingGroup/IBEX/issues/1463
Selecting a table from the drop down menu and submitting the changes always results in the correct path being written in the DAESETTINGS PV.
---

Ticket1464 blank spectra tables

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/.classpath
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/.project
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/build.properties
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/pom.xml
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/Perspective.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/ScriptGeneratorView.java

ISISComputingGroup/IBEX/issues/1459
Added a hidden perspective called Script Generator. Currently only contains a blank browser widget.
Enable the hidden perspective using Ctrl+Alt+P. 
*List the acceptance criteria for the PR*
---

Ticket1459 create script generator perspective 

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/plugin.xml

Fix the structure of the plugin.xml for the beam status perspective to avoid exceptions
https://github.com/ISISComputingGroup/IBEX/issues/1386
No exception on opening beam status perspective
---

Fix plugin class names, id, and structure

---

base/uk.ac.stfc.isis.ibex.dae.tests/src/uk/ac/stfc/isis/ibex/dae/tests/dataacquisition/SettingDaeSettingsFromXmlTest.java
base/uk.ac.stfc.isis.ibex.dae.tests/src/uk/ac/stfc/isis/ibex/dae/tests/periods/WritingXmlFromPeriodSettingsTest.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/XmlBackedDaeSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/periods/PeriodSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/periods/XMLBackedPeriodSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/TimeChannels.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/XmlBackedTimeChannels.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetupViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/periods/PeriodsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsViewModel.java

Separated the readback of the currently loaded DAE tables/ time channel & period files in the experiment setup from the drop down menu used to set them. This eliminates a race condition that would result in the UI not properly displaying the current file. 
Furthermore, the currently set file does not need to be in the list of files currently available on the instrument anymore to show up in the UI, which allows to reflect the state of the experiment setup more accurately, as it is possible to have a file loaded that does not exist (e.g. has since been renamed/deleted) as the file content is kept in the relevant PV.
https://github.com/ISISComputingGroup/IBEX/issues/1493
1. The readback labels in the DAE perspective show the correct path for the currently loaded files.
1. You can select a …

Ticket1493 dae tables race condition

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

I've updated the source for the Nebula plugin to get version 1.0.0
I can't see any change in the DAE graphs, but their functionality is somewhat limited on simulated instruments.
https://github.com/ISISComputingGroup/IBEX/issues/1242
The Gui still builds and there are no dependency issues. The behaviour of the DAE graphs are unaffected. Note I have added a release note for all Instruments to check this as it is hard to test the change on simulated instruments.
---

Ticket1242: Update version of Nebula

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java

Fix bug which should be on the release branch

Do not set value to error if their is an error getting a blocks error

---

base/uk.ac.stfc.isis.ibex.opis/resources/analyser.opi
base/uk.ac.stfc.isis.ibex.opis/resources/beamstop.opi
base/uk.ac.stfc.isis.ibex.opis/resources/inout_monitor.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polariser.opi
base/uk.ac.stfc.isis.ibex.opis/resources/rotating_bench.opi
base/uk.ac.stfc.isis.ibex.opis/resources/single_stage.opi
base/uk.ac.stfc.isis.ibex.opis/resources/slit_motors.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/goniometer_motors.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/linear_sample_changer.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/orientation.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sample_changer.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/stage_motors.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/xyz.opi

Resized the linking containers pointing at motors in various OPIs.
If there were only one or two linking containers. I have made them auto-resize to fit the new motors OPI at 100% scale. Some other OPIs have arrays/matrices of the motor OPIs, and so while making them of a reasonable size, they are a bit less than 100%, otherwise they would be too big.
this is for ISISComputingGroup/IBEX#1545
Go through all OPIs and check that any OPI using motors in linking contaners looks OK.
---

Ticket1545 fix motors linking containers

---

base/uk.ac.stfc.isis.ibex.ui.dashboard.tests/src/uk/ac/stfc/isis/ibex/ui/dashboard/tests/models/ObservableDecimalRatioTest.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/models/MonitorPanelModel.java
base/uk.ac.stfc.isis.ibex.ui/src/org/eclipse/wb/swt/SWTResourceManager.java

Checkstyle fixes for the ticket that was closed a while back.
ISISComputingGroup/IBEX#1632
Were the checkstyle guards around SWTResourceManager removed for a reason?
I have done the modifications via the github interface so, hopefully, they are okay.
Please check by running checkstyle in eclipse.
Does the checkstyle warnings listed in http://epics-jenkins.isis.rl.ac.uk/job/ibex_gui/570/ disappear?
---

Ticket1632 checkstyle fixes

---

base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocPanel.java

When the IOC table is updated (i.e. run state change) it triggers a number of actions. One is to replace all the rows in the table. This deselects all the rows and triggers various updates of the editor panel. The code previously attempted to restore the previous state of the editor panel by updating the ioc referenced by the panel. However, this still didn't leave the editor panel with the correct bindings.
What should really happen when the table replaces all its rows is that it should re select the row that was previously selected. This leaves the table in its original state and the editor with the correct bindings so that it gets updated appropriately when external changes occur.
https://github.com/ISISComputingGroup/IBEX/issues/1458
For each of these tests, make sure that the state …

Ticket1458 IOC status bug

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/BlockTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Block.java
base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/BlockLogSettingsViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockLogSettingsViewModel.java

Changed default log setting to be enabled and 30s.
Added some unit tests.
Fixed existing system test to reflect the changes in the GUI (see ISISComputingGroup/ibex_system_tests#27)
Updated manual system test spreadsheet (added test number 15-30)
Updated the user manual at http://shadow.nd.rl.ac.uk/ibex_user_manual/CreateandManageConfigurations#blocks-tab
ISISComputingGroup/IBEX#1635
When creating a new block, the default log settings are enabled and 30s rate. All the other functionality remains the same.
Unit and system tests pass
---

Ticket1635 blocks log by default

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/Configurations.java
base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/SetCommand.java

Purely added documentation, minor code change in that an unused method has been removed.

Added documentation to ConfigServer

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/row/Row.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/Table.java

Allows rows to be created by initially clicking in the top row, and then clicking on the row directly beneath a populated row. All columns are of the correct type.
https://github.com/ISISComputingGroup/IBEX/issues/1562
*List the acceptance criteria for the PR*
---

change row field types (position and period)

---

base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/ExponentialOnThresholdFormatTest.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/ExponentialOnThresholdFormat.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/VTypeDefaultFormatter.java

Numbers <0.001 or >=1000000 are represented in scientific notation (doubles only), taking into account also the PREC field of the PV.
I have also added new entries in the manual system tests spreadsheet (tests 21-7 to 21-23)
Note I have created some new PVs in the SIMPLE IOC, to make testing easier (see ISISComputingGroup/EPICS-SimpleIoc#1 )
This solves for example issues with small pressures being displayed as 0 in the GUI.
ISISComputingGroup/IBEX#1592
Create blocks using the PVs in SIMPLE IOC. For this purpose there are two ai records (with PREC 3 and 5, though you can change it at runtime) and a LONG. There is also a string record that could be used.
Test changing the PV values, some examples are in the table in the ticket itself.
Please also check edge cases: values just …

Ticket1592 scientific notation

---

base/uk.ac.stfc.isis.ibex.opis/resources/template.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template_inside_linking_container.opi

Added a template opi in resources/template.opi (is this the right place?)  covering the widgets normally used in our OPIs.
The template uses new font names and a couple of new colours. These all have a _NEW suffix, so for now the old and new style can co-exist, but when we retire the old style we can simply do a find-replace of the font/colour names in the text files.
I've also added a section in the wiki in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation which in turn links to a page of tips and gotchas when converting an existing OPI to the new style.
I have checked the OPI for colour blindness using ColorOracle (see link in doc), and changed the RED LED ON colour to be a bit brighter/fainter, so it's more easily distinguished from RED OFF. I have changed …

Ticket1621 opi template

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi

Change Eurotherm tab names from Eurotherm to Sensor
https://github.com/ISISComputingGroup/IBEX/issues/1713
---

Change Eurotherm tab names from Eurotherm to Sensor

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/row/Row.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/Table.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/TablePanel.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/View.java

The clear button should now clear all inputted data from the table (all table fields appear blank). 
https://github.com/ISISComputingGroup/IBEX/issues/1566
*List the acceptance criteria for the PR*
---

Script Generator: implement clear table methods

---

base/uk.ac.stfc.isis.ibex.client.product/pom.xml
base/uk.ac.stfc.isis.ibex.product/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.product/pom.xml

Set the master versions of client to be 0.0.0 on master branch so it is clear it is not a release version.
https://github.com/ISISComputingGroup/IBEX/issues/1549
Reported version of client on master branch is obviously not a release version
---

Set master branch version to 0.0.0

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java

Use correct DAE PVs for RBNUMBER and username
See ISISComputingGroup/IBEX#1743
Set RBNUMBER and username, check DAE info panel readback reflects this
Above test
---

Use correct DAE PV

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServerVariables.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHelper.java

Saving to file is now done as part of setting the current config. This operation is no longer necessary
https://github.com/ISISComputingGroup/IBEX/issues/1595
As https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/100
---
…ne between updating config details and initialising the config

Ticket1595 macro updates too slow

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHelper.java

Added the `DEV` OPI macro to the opi info file so that the macro can be set from the synoptic editor
https://github.com/ISISComputingGroup/IBEX/issues/1593
Check that the `DEV` macro and its description appear in the synoptic editor, can be set, and are applied to the OPI as expected.
---

Ticket1593 add sd test opi macro to opi info

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/ConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DeleteComponentsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DeleteConfigsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DisablingConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditCurrentConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/LoadConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/ConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/ViewConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigDetailsDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/EditConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/blockselector/BlockSelector.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/pv/PvSelector.java

Fixed both https://github.com/ISISComputingGroup/IBEX/issues/1410 and https://github.com/ISISComputingGroup/IBEX/issues/1667
Can now not edit blocks when looking at an instrument where you do not have write permission. Can now open a dialog to view a configuration when looking at an instrument where you do not have write permission.
Note: The viewing dialog still allows you to appear change items (even though nothing is sent to the instrument). I propose that this is fixed in another ticket as it requires quite a bit more work.
When viewing an instrument that you cannot write to:
* You cannot right-click to edit a block
* The Configurations menu now says view rather than edit
* You can open the current configuration to view
* When viewing the config titles are correct and save/save as …

Ticket1667: View Configs when connected to a read only instrument

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_uncalibrated.opi

For: https://github.com/ISISComputingGroup/IBEX/issues/1503
see https://github.com/ISISComputingGroup/EPICS-ioc/pull/98
---

Ticket1503 calibrated and uncalibrated op is

---

base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/ComponentDescription.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/SynopticDescription.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/component/ComponentDetailView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/model/SynopticViewModel.java

Fixed some checkstyle warnings.
NO CODE HAS BEEN CHANGED.

Fixed checkstyle for SynopticViewModel

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettings.java

Added javadoc to DaeSettings to fix checkstyle warnings. Check that it goes through ibex_gui_PRs on Jenkins as expected and merge.

Add javadoc to fix DAE settings checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/pv/BlockServerAddresses.java

Add missing javadocs for BlockServerAddresses

Add missing javadocs for BlockServerAddresses

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java

Add missing javadoc for editable configurations

Add missing javadoc for editable configurations

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java

*Note that spaces mid-name were already disallowed, this only applies to trailing spaces*
Don't allow spaces in the config name. The GUI doesn't actually save configs with spaces at the moment, but trims the name as it comes in. I've removed the trim. This won't have any effect on existing configurations but it will mean that if a user tries to save `name ` (i.e. with a space on the end) then they'll get an error message. This is potentially confusing since the space won't be visible, but I see this as preferable to making implicit assumptions about what the user means.
This doesn't require instruments to be updated as stated on the initial ticket because existing configurations will have saved the configs without the space.
https://github.com/ISISComputingGroup/IBEX/issues/1712 …

Ticket1712 dont allow spaces in config names

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java

Fix a couple of checkstyle warnings from fixed issue

Fix a couple of checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/VTypeFormat.java

Add missing javadoc for VTypeFormat class

Add javadoc for VTypeFormat

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Configuration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Ioc.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableIoc.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/Convert.java

Add missing javadocs for a few most offending files

Checkstyle warnings multiple files

---

base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/AboutDialogBox.java
base/uk.ac.stfc.isis.ibex.ui.help/src/uk/ac/stfc/isis/ibex/ui/help/VersionPanel.java

When the about dialog is opened, the server version gets given a width. If the server version changes to a longer version string, then the width isn't changed along with it.
Apart from tidying up some checkstyle, I've changed the width of the label to take up the full width of the parent dialog. That should give it plenty of room. I haven't done the same for the client version because that will be fixed.
I've added a couple of tests (Cat: Help) to the manual system tests.
To reproduce:
1. Open the GUI
1. Open the about dialog from the help menu
1. Do a caput on TE:NDWXXX:CS:VERSION:SVN:REV to change the PV to something long. The label previously would overflow beyond its bounds. Now all the text should be visible.
https://github.com/ISISComputingGroup/IBEX/issues/1344
As above. Note that …

Ticket1344 server version not displayed correctly

---

base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/RunControlSettingsPanel.java

https://github.com/ISISComputingGroup/IBEX/issues/1384
Before switching to this branch:
Run the GUI, open the run-control dialog then close it.
Close the GUI.
Eclipse should print an exception relating to `RunControlSettingsPanel` and `Caused by: org.eclipse.swt.SWTException: Device is disposed` 
Switching to this branch:
Run the GUI, open the run-control dialog then close it.
Close the GUI.
Eclipse should NOT print the exception described above.
The exception is not shown
---

Ticket 1384: exception on Close after opening run control 

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ConfigEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

This relates to https://github.com/ISISComputingGroup/IBEX/issues/1356. However, neither of the solutions presented there have been implemented. Instead the behaviour is:
* On a creating a new config/component: config name and description are both editable, however there is no validation until you go to the save dialog.
* On editing a config/configuration: only description is editable, there is validation on it. You can save as to rename the config as previously
I went with this solution as it solves the annoyance of a new config being immediately invalid on the first screen but still allows the user to change things, ensuring validation.
I'm open to debate about if this is a good solution or not...
Confirm that the above is correct
---

Ticket1356: redundant step in naming config

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/DeviceSceenListPanel.java

Modified the observer for the device screens so that the list of device screens becomes blank when the instrument is disconnected / unknown (e.g. switching to an offline instrument) rather than keeping on showing whatever was there before. (Would previously change with configurations)
Related PR: https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/104
https://github.com/ISISComputingGroup/IBEX/issues/1751
Device screen list reacts appropriately to changing instrument status, i.e.
- Clears list when instrument is disconnected
- Updates list when device screens are edited / when changing to a different instrument
---

Ticket1751 device screens per instrument

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/writing/ClosableSameTypeWriter.java
base/uk.ac.stfc.isis.ibex.synoptic.tests/src/uk/ac/stfc/isis/ibex/synoptic/tests/model/desc/TargetDescriptionTest.java
base/uk.ac.stfc.isis.ibex.targets.tests/src/uk/ac/stfc/isis/ibex/targets/tests/ViewTargetTest.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/RunState.java
base/uk.ac.stfc.isis.ibex.ui.logplotter/src/uk/ac/stfc/isis/ibex/ui/logplotter/Perspective.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/states/RecordLabelState.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/states/RecordSetterState.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/states/Status.java

Fix another handful of checkstyle warnings

Checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/ConfigEditorPanel.java

Moved components tab to top of list
https://github.com/ISISComputingGroup/IBEX/issues/1816
Components is first tab in edit config dialog
---

Moved components tab to top of list

---

base/uk.ac.stfc.isis.ibex.client.product/pom.xml
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.product/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.product/pom.xml

**PR for merge into release branch 2.2.1**
Change the Eurotherm example macro to fit with new naming.
To resolve merge, keep existing version numbers (i.e. 2.2.1). The merge conflict cannot be resolved on the branch because it will effect the PR for the master branch: https://github.com/ISISComputingGroup/ibex_gui/pull/384
https://github.com/ISISComputingGroup/IBEX/issues/1644
---

Ticket1644 eurotherm renaming (release 2.2.1)

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
base/uk.ac.stfc.isis.ibex.opis/resources/EurothermFileCheck.py
base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template.opi

- Added error labelling in the case of read error for ramp and calibration file
- Converted Eurotherm OPI to new format
https://github.com/ISISComputingGroup/IBEX/issues/1856
- New OPI looks ok
- All controls still work
- Error message appears when invalid file entered
- Functionality works across multiple sensors
---

Ticket1856 eurotherm calibration error

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper.opi

Changed the PV that the Mk3Chopper OPI points at to the new, shorter name
https://github.com/ISISComputingGroup/IBEX/issues/1895
---

Ticket1895_Shorten_MK3CHOPPER_name (master)

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper.opi

Changed the PV that the Mk3Chopper OPI points at to the new, shorter name
https://github.com/ISISComputingGroup/IBEX/issues/1895
---

Ticket1895_Shorten_MK3CHOPPER_name (Release 3.0.0)

---

base/uk.ac.stfc.isis.ibex.preferences/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/Activator.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/SynopticPresenter.java

Removed some of the messages printed to the log on startup.
https://github.com/ISISComputingGroup/IBEX/issues/1933
---

Ticket1933: Remove warnings on start

---

base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi

Tiny change to the horizontal alignment of the setpoint boxes in the Kepco OPI

Very minor horizontal spacing tweak

---

base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/database/ExpDataFieldsCreator.java
base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/database/ExperimentIDQuery.java

Corrects the SQL for the search dialog, and includes the start date in a couple of places
This code relates to Ticket #1765
Test by making sure that you can see all the entries you expect in the Experiment Details search dialog, and that all names related to an experiment are returned when the RB Number is set
---

Update the SQL query to allow the use of Start Date as part of the keys

---

base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/switcher/PerspectiveSwitcherView.java

Fixed bug described in https://github.com/ISISComputingGroup/IBEX/issues/1934
---

Ticket1934: Only add ampersand when required

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/CustomInput.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/Keithley2400.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/OutputMode.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/ResistanceMode.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java

Rename KEIT -> KHLY
See ISISComputingGroup/IBEX#2011
GUI and IOC work as before
---

Rename KEIT -> KHLY

---

base/uk.ac.stfc.isis.ibex.motor/src/uk/ac/stfc/isis/ibex/motor/observable/MotorVariables.java
base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/MinimalMotorView.java

The high limit switch should be mapped to HLS and the low limit switch to LLS.
https://github.com/ISISComputingGroup/IBEX/issues/1814
---

PV fields the wrong way around

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DataAcquisitionPanel.java

Russell (ALF) tried to set the monitor spectrum (DAE/Data acquisition tab) to ~1500 but the GUI only previously allowed a maximum of 100.
I asked Russell and the largest instrument he could think of supported 98000 spectra so I've set the new upper limit at 1,000,000 which gives adequate margin and doesn't make the text box look too big
https://github.com/ISISComputingGroup/IBEX/issues/2056
The monitor spectrum number can be set to any value that an instrument scientist might reasonably want.
---

Increase maximum monitor spectrum to 1 million

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java

Removed a nonsensical if statement that has been there for 2 years.
See https://github.com/ISISComputingGroup/IBEX/issues/2031
---

Ticket2031: Component name copied to save dialog

---

base/uk.ac.stfc.isis.ibex.opis/resources/muon_front_end.opi

Update the macros and opi to be new style.
https://github.com/ISISComputingGroup/IBEX/issues/1840
1) All position set and read work
2) Moving LED work
3) Details buttons show correct motor (based on macro)
4) New style is correct
---

Update macros to be correct for barn doors. And update OPI to be new style

---

base/uk.ac.stfc.isis.ibex.feature.base/feature.xml

See ISISComputingGroup/IBEX#2077
Clean setup and import of GUI works
above works
---

Add nicos and activemq

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

The motor details view had a stray widget at 
```
<x>-2147483647</x>
<y>2147483496</y>
```
This has been removed. Functionality of the OPI should be unaltered.
The justification for deleting rather than moving is that:
1. This is a grouping container, not a functional element.
1. It had `width=1` and `height=1` and is located at `x=-2147483647`, `y=2147483496` so would never have been visible anyway.
https://github.com/ISISComputingGroup/IBEX/issues/1987
---

Ticket1987 motor details hidden

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeTimingSource.java

Add option for TS1 only timing source to the GUI.
Requires the change to the ISIS DAE in https://github.com/ISISComputingGroup/EPICS-isisdae/pull/17 to work.
https://github.com/ISISComputingGroup/IBEX/issues/2076
---

Add dropdown menu item for ISIS timing source

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeTimingSource.java

*Checkstyle only, no code changes*
Fixes checkstyle warning from the original merge of https://github.com/ISISComputingGroup/IBEX/issues/2076

Fix checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/PvSelectorDialog.java

Add the title "Select PV" to the PV selector dialog
https://github.com/ISISComputingGroup/IBEX/issues/2059
A title is displayed in the PV selector dialog which is appropriate to the dialog's function
---

Add title to PV selection dialog shell

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/SaveSynopticDialog.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/InstrumentNameValidator.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/PvValidator.java

This PR adjusts the message when selecting "Save configuration as" to ensure that it's obvious that  lowercase characters are allowed.
https://github.com/ISISComputingGroup/IBEX/issues/2057
---
Note: I haven't added release notes because this is so minor I don't think it's worth it. Will add them if the reviewer thinks they're necessary.

Fix title to make it obvious lowercase characters are allowed

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/MQConnection.java

Fixes a resource leak in the ActiveMQ connection code.
https://github.com/ISISComputingGroup/IBEX/issues/2135
Use the java visual VM in `C:\Program Files\Java\jdk1.8.0_73\bin` to check that observed behaviour is like the following screenshots:
With this change: (CPU usage ~ 0)
Without this change: (CPU usage ~ 1/[number of CPU cores])
---

Move sleep statement so that connection is only tested once per second

---

base/uk.ac.stfc.isis.ibex.log/plugin.xml

This PR fixes a bug where the log messages do not switch
https://github.com/ISISComputingGroup/IBEX/issues/2087
---

Add an extension point for the activemq plugin

---

base/uk.ac.stfc.isis.ibex.activemq/.checkstyle
base/uk.ac.stfc.isis.ibex.epics/.checkstyle
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/.checkstyle
base/uk.ac.stfc.isis.ibex.ui.synoptic/.checkstyle

Fixes an accidentally committed `.checkstyle` file

Revert accidentally committed file (Ticket 2147)

---

build/build_msi.bat
build/ibex_client_master.wxs
build/jenkins_build.bat
build/wxs2wxi.xsl

Generate a client MSI kit at end of Jenkins build
See ISISComputingGroup/IBEX#1994
MSI kit is generated
---

Add MSI kit build

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi

In the motor OPI, make the jog button toggle. This is the same as in the motor details panel.
https://github.com/ISISComputingGroup/IBEX/issues/2021
---

Jog should be a toggle button

---

base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/CustomInput.opi

Point the custom input/output PVs to new, separate values
https://github.com/ISISComputingGroup/IBEX/issues/2045
See: https://github.com/ISISComputingGroup/EPICS-ioc/pull/125
---

Use separate read/write PVs on custom input screen

---

base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/models/package-info.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/package-info.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/views/package-info.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/TitlePanel.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/UsersConverter.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/package-info.java

Fixes https://github.com/ISISComputingGroup/IBEX/issues/1766
* Create a DAE title that contains ampersands
* Confirm that you can see the ampersands in the dashboard
* Repeat for Users
---

Ticket1766: Added converter to make ampersands literal

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.opis/resources/omron_plc.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/DeviceScreenListPanel.java

Stub OPI for the PLC on zoom which will be updated with "real" content as part of https://github.com/ISISComputingGroup/IBEX/issues/1232
https://github.com/ISISComputingGroup/IBEX/issues/2210
---

Add skeleton OPI for PLC

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk2Chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Create an OPI for the MK2 chopper
https://github.com/ISISComputingGroup/IBEX/issues/2130
Test in conjunction with the IOC: https://github.com/ISISComputingGroup/EPICS-ioc/pull/132
---

Ticket2130 mk2 chopper

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumView.java

Changed the text entry fields for selecting spectra / periods to spinners for easier input.
https://github.com/ISISComputingGroup/IBEX/issues/2052
Can successfully set spectra/periods using the spinner widgets.
---

Ticket2052 spectra plot spinners

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/MultipleConfigsSelectionDialog.java

Sort configs list case insensitively
https://github.com/ISISComputingGroup/IBEX/issues/2227
---

Sort configs case insensitively

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java
base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/ManagerModeModel.java
base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/ManagerModeObservable.java
base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/ManagerModeObserver.java
base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/ManagerModePvNotConnectedException.java
base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/PasswordHasher.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ManagerModeBannerModel.java
base/uk.ac.stfc.isis.ibex.ui.mainmenu/src/uk/ac/stfc/isis/ibex/ui/mainmenu/managermode/ManagerModeHandler.java

Fixes checkstyle warnings from 2082/2083
https://github.com/ISISComputingGroup/IBEX/issues/2225
---

Ticket2225 checkstyle

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/ConsoleSettings.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/PerspectiveReopener.java

Ensures that alarms perspective and scripting perspective close and reopen properly on instrument switch.
https://github.com/ISISComputingGroup/IBEX/issues/2232
---

Fix perspective closing/reopening on switch instrument

---

build/install_client.bat

Use delayed expansion to correctly find path to genie_python_install
ISISComputingGroup/IBEX#2249
Script calls genie_python_install correctly
---

Use delayed expansion to call genie_python_install

---

base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/Jaws_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/Jaws_polaris.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/single_jaw_gaps.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/single_jaw_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/single_jaw_setpoints.opi
build/install_client.bat

Onto release patch polaris stuff

Ticket2236 polaris jaws

---

base/uk.ac.stfc.isis.ibex.client.product/pom.xml
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/Jaws_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/Jaws_polaris.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/single_jaw_gaps.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/single_jaw_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/polaris_jaws/single_jaw_setpoints.opi
base/uk.ac.stfc.isis.ibex.product/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.product/pom.xml

Implemented minor changes to Polaris Jawset OPI requested by Ron after commisioning.
Related PR: https://github.com/ISISComputingGroup/EPICS-motorExtensions/pull/2/
https://github.com/ISISComputingGroup/IBEX/issues/2236
See ticket
---

Ticket2236 polaris jaws various minor changes

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/IocsTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockFactory.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/IocOverviewPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/AddIocDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/IocDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/PVSelectorPanel.java

When adding a component to a configuration, IOCs in said component are added to the configuration with all their settings, macros etc (same as blocks).
System test: https://github.com/ISISComputingGroup/ibex_system_tests/pull/44
https://github.com/ISISComputingGroup/IBEX/issues/1355
* Component IOCs show up in IOC tab after adding component to config.
* Settings of component IOC can be viewed, but not edited
* IOC is started with settings as set in component.
---

Ticket1355 show iocs from components

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/Dae.java
base/uk.ac.stfc.isis.ibex.devicescreens/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/navigation/InstrumentNavigationGraph.java
base/uk.ac.stfc.isis.ibex.targets/src/uk/ac/stfc/isis/ibex/targets/PerspectiveTarget.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/Perspective.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/Perspectives.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/NavigationPresenter.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/SynopticPresenter.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/beamline/BeamlineComposite.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/BasicComponent.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/ComponentView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/GroupView.java

Fixed and tidied a number of things in the synoptic viewer. Started due to https://github.com/ISISComputingGroup/IBEX/issues/2182
---

Ticket2182: Synoptic targets tidying

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/DeviceScreenListPanel.java

See https://github.com/ISISComputingGroup/IBEX/issues/2291
---

Ticket2291: Removed border from device screen table

---

PULL_REQUEST_TEMPLATE.md
base/uk.ac.stfc.isis.ibex.feature.base/feature.xml

Add missing managermode plugin and update PR template to request plugin validation
See ISISComputingGroup/IBEX#2308
GUI now builds without error
---

Ticket2308 missing managermode plugin

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewConfigHandler.java

See https://github.com/ISISComputingGroup/IBEX/issues/2317
Should be quite self explanatory
---

Ticket 2317: Fixed title on configuration dialog

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/IocOverviewPanel.java

Clear the "Selected" text box when the final IOC is deleted
https://github.com/ISISComputingGroup/IBEX/issues/2226
---

Ticket2226 clear selected ioc on delete

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk2Chopper.opi

Previously there was a "Spectral" interlock group box in the MK2 chopper OPI. This was a misinterpretation on my part when setting up the OPI
https://github.com/ISISComputingGroup/IBEX/issues/2272
The interlock indicators are all in boxes that make sense from a device perspective
---

Have a single interlock panel on MK2 Chopper OPI

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/PropertyDescription.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/DeviceScreensDescriptionViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens.tests/src/uk/ac/stfc/isis/ibex/ui/devicescreens/tests/TargetPropertiesViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/commands/ConfigureDeviceScreensHandler.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/ConfigureDeviceScreensTargetPanel.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/TargetPropertiesTable.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/TargetPropertiesWidget.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/dialogs/package-info.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/list/package-info.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/EditDeviceScreensDescriptionViewModel.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/TargetPropertiesViewModel.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/package-info.java

I moved the target properties in the device screens into a separate viewmodel. This made a number of bugs a bit more obvious to fix. See https://github.com/ISISComputingGroup/IBEX/issues/2254 for the specific bugs that this was specifically targeted towards.
* Ensure that properties of screens can be modified as expected
* Check that you can no longer reproduce the bugs outlined in the original ticket
* Check that the unit tests still all run correctly
---

Ticket2254: Fixed bugs around Devicescreens target properties

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi

As part of ticket 2290, a custom motor name can now be set for McLennans and Linmots. The box for displaying the name is fixed width. I've put a script in place to truncate and add an elipsis to the motor name if it's too long.
https://github.com/ISISComputingGroup/IBEX/issues/2290
Give a motor a long name. Check it fits in the name box
---

Ticket2290: Limit max size of motor name

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigDetailsDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/EditableIocsTable.java

A couple of minor changes to the aesthetics of bits of the configuration editor
Before checking out the branch:
1. Verify that there is a lot of room for the character limited IOC name, and a similar amount of room for the IOC description on the IOC tab of the configurations editor
1. Go to the groups page and resize the window into a smaller one, note that you can completely hide everything
With the branch checked out:
1. Verify that there is now more room for the descriptions on the IOC tab of the configurations editor
1. Looking at the groups tab, again try to resize the window to a smaller size, you should still be able to see all the buttons on the groups tab
1. There is more room available for IOC descriptions
1. You can't hide buttons and similar by reducing the size of the window …

Ticket2259 gui tweaks

---

base/uk.ac.stfc.isis.ibex.opis/resources/amint2l/amint2l.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

OPI of AMINT2l
See https://github.com/ISISComputingGroup/EPICS-ioc/pull/145
https://github.com/ISISComputingGroup/IBEX/issues/2270
1. OPI can be viewed
1. Graph ticks along even when value does not change
1. Over and Under range label shown on over and under range error conditions
1. Testable by running the emulator and using the backdoor to set the pressure to `'OR'`/`'UR'`
---

Add opi for the amint2l

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/DeviceDescription.java
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/EditDeviceScreensDescriptionViewModel.java

See https://github.com/ISISComputingGroup/IBEX/issues/2233
Also merge https://github.com/ISISComputingGroup/ibex_system_tests/pull/52
* Add a new device screen
* Confirm that the new screen has now been selected
---

Ticket2233: Automatically select new screen

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/ObservedSpectrum.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/spectra/Spectra.java
base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/SwitchableObservable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/ForwardingObservable.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/TransformingObservable.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectra/SpectrumView.java

- Only create spectra when DAE perspective is opened
- Don't create new spectra until spectra and period number have been stable for a second
- Close unwatched spectra observables to avoid excessive traffic from the ISISDAE IOC.
https://github.com/ISISComputingGroup/IBEX/issues/1968
The behaviour of the GUI should be largely unaffected. Check that the spectra plots still behave as expected. Make sure to do this where spectra (simulated/real) are available. Try looking at lots of spectra and make sure the plots don't freeze. Also, since I've changed the closing behaviour of the observables, check that things like the IOC list are unaffected and switching between instruments still works as before.
---
- Manual system tests for the functionality should be added if there are no automated …

Ticket1968 spectra not updating

---

base/uk.ac.stfc.isis.ibex.opis/resources/rot_sample_changer.opi

I changed the spelling of carousel in the rotating sample changer so the corresponding PVs needed changing in the OPI.
The STATUS_STRING PV has also been renamed to STAT
https://github.com/ISISComputingGroup/IBEX/issues/2412
---

Fix spelling mistake. Change PV STATUS_STRING to STAT

---

base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.opis/resources/Mk2Chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template.opi

Adds (optional) access security to the mk2 chopper IOC. 
https://github.com/ISISComputingGroup/IBEX/issues/2361
https://github.com/ISISComputingGroup/IBEX/issues/2360
---

Add indicator to OPI if manager mode is required but not enabled

---

base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/switcher/AlarmButton.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/switcher/FlashingButton.java
base/uk.ac.stfc.isis.ibex.ui.perspectives/src/uk/ac/stfc/isis/ibex/ui/perspectives/switcher/LogButton.java

Fixes exception when switching instruments while log button is flashing.
https://github.com/ISISComputingGroup/IBEX/issues/2333
•Switch to an instrument which is actually producing logs (e.g. add IOC and supply non-existent COM port)
•Switch away from the "IOC log perspective" so that the "IOC log" button starts to flash
•Now switch instruments
---

Ticket2333 exception on switch instrument

---

base/uk.ac.stfc.isis.ibex.opis/resources/TPG26x.opi
base/uk.ac.stfc.isis.ibex.opis/resources/TPG300.opi
base/uk.ac.stfc.isis.ibex.opis/resources/amint2l/amint2l.opi
base/uk.ac.stfc.isis.ibex.opis/resources/pdr2000.opi

Changed all pressure graphs on OPIs to logarithmic. As per https://github.com/ISISComputingGroup/IBEX/issues/2441
Confirm graphs on the following OPIs have logarithmic scales:
* PDR2000
* TPG (300/26x)
* amint2l
Confirm that there are no other pressure gauges to change
---

Ticket2441: Pressure graphs should be logarithmic

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk2Chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/single_chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/single_chopper_control_panel.opi

https://github.com/ISISComputingGroup/IBEX/issues/2381
Adds a combo box to the OPIs which enables only the allowed frequencies to be selected. Check that the combo box works with the IOC in sim mode.
The frequencies can be set using the combo box.
---

Ticket 2381: choppers OPI show valid frequencies

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/superlogics.opi

Adds an OPI for the superlogics device. See: ISISComputingGroup/IBEX#2378.
See main PR: ISISComputingGroup/EPICS-ioc#153

Superlogics OPI

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/ActiveMQ.java
base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/MQConnection.java
base/uk.ac.stfc.isis.ibex.alarm.tests/src/uk/ac/stfc/isis/ibex/alarm/tests/AlarmTest.java
base/uk.ac.stfc.isis.ibex.alarm/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.alarm/src/uk/ac/stfc/isis/ibex/alarm/AlarmSettings.java
base/uk.ac.stfc.isis.ibex.log/src/uk/ac/stfc/isis/ibex/log/preferences/PreferenceConstants.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/Nicos.java
base/uk.ac.stfc.isis.ibex.product/plugin_customization.ini

See https://github.com/ISISComputingGroup/IBEX/issues/2315
New documentation has also been added to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/ActiveMQ
Confirm that the following still work from the GUI (on local instrument):
* NICOS (can connect)
* Alarm Server (can connect and get new alarms)
* IOC Log (can connect and get messages)
---

Ticket 2315: Changed ActiveMQ port

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/XmlBackedDaeSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/periods/XMLBackedPeriodSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/updatesettings/XMLBackedUpdateSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/xml/XmlFile.java

This fixes the crashing view seen in the screenshot in https://github.com/ISISComputingGroup/IBEX/issues/2423. However, I did not fix the exception as:
* The DAE should never be in processing for a long period of time, this is a genuine error
* The only thing I can think to do on the exception is silently pass it or log a slightly less verbose message
* Start the GUI pointing at a processing DAE (IMAT is currently in processing)
* Confirm the dashboard is still visible
* Repeat 3 or 4 times (the original error appeared to have a ~1/4 chance of not happening)
---

Ticket2413: Fixed crashing view on processing DAE

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/Switcher.java
base/uk.ac.stfc.isis.ibex.log/src/uk/ac/stfc/isis/ibex/log/rdb/LogMessageQuery.java
base/uk.ac.stfc.isis.ibex.log/src/uk/ac/stfc/isis/ibex/log/rdb/SqlStatement.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/preferences/PreferenceConstants.java
base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

OPI for the fermi chopper
2355
---

2358 opi for fermi

---

base/uk.ac.stfc.isis.ibex.opis/resources/enginx_sample_position_system.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds an OPI for the Engin-X sample positioning system.
https://github.com/ISISComputingGroup/IBEX/issues/2401
---

Add Engin-X sample positioning system OPI

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/ConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditComponentHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/ViewConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/RunState.java

This fixes the sub title in the configuration editor so that it says "current" when editing the current config and the name of the config otherwise.
- Check that editing the current configuration sets the config name in the sub title to "current"
- Check that editing anther configuration sets the config name in the sub title to the name of the config
- Check that editing components show a sensible sub title.
- Code review
The issue is https://github.com/ISISComputingGroup/IBEX/issues/2536
---

Fix sub title in configuration

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java

Change to use RUNSTATE rather than RUNSTATE_STR PV, currently these are aliases but RUNSTATE_STR will be changing 
ISISComputingGroup/IBEX#2537
Run state is still displayed correctly
---

Change to use RUNSTATE instead of RUNSTATE_STR

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

Makes the eurotherm graphs update on the trigger PV instead of only on a PV value update.
https://github.com/ISISComputingGroup/IBEX/issues/2440
---

Fix eurotherm setpoint graphs

---

base/uk.ac.stfc.isis.ibex.opis/resources/stress_rig/channel_vs_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stress_rig/stress_rig.opi

- Changes the channel vs channel graph to update on X AND Y data.
- Changes the channel vs channel graph to use a large points buffer
- Provides a separate readback value for the channel selection, this got confusing before where they could update the channel on the device and the IOC was then in the wrong state
2338
Above points in description of work have been fixed.
---

Ticket2338 instron

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/coupled_slit.opi

*Which ticket does this PR fix?*
*List the acceptance criteria for the PR*
---

Modified due to back end jaw changes

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/DeviceScreenListPanel.java

- Put edit device screens button at the top (consistent with other views)
- Left align the button (consistent with other views and avoids having a button with lots of empty space)
https://github.com/ISISComputingGroup/IBEX/issues/2292
I haven't added a system test as the button function is already tested
---

Ticket2292 move edit button to top

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/component/ComponentDropListener.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/component/package-info.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/InstrumentTreeView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/package-info.java

Remove the hack of adding a default text string to the drag and drop and put in better code.
https://github.com/ISISComputingGroup/IBEX/issues/2571
1. Check components can be dragged and dropped in the synoptic editor
---

Correct drag and drop functionality in synoptic editor

---

base/uk.ac.stfc.isis.ibex.validators.tests/src/uk/ac/stfc/isis/ibex/validators/tests/InstrumentNameValidatorTest.java
base/uk.ac.stfc.isis.ibex.validators.tests/src/uk/ac/stfc/isis/ibex/validators/tests/PvValidatorTest.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/InstrumentNameValidator.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/PvValidator.java

Allows dashes in PV names.
https://github.com/ISISComputingGroup/IBEX/issues/2580
Client allows you to use dashes in PV names.
Check:
- Instrument switcher, custom instrument dialog
- Blocks dialog
- Synoptics dialog
- That you still can't have a "-" in a block name
---

Allow dashes in GUI pvs

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.e4.client/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocControlHandler.java
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/package-info.java

IOC Start stop menu item now works
IOC Start stop menu 
---

Convert handler for IOC start stop

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.ui.mainmenu/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.mainmenu/src/uk/ac/stfc/isis/ibex/ui/mainmenu/ExitHandler.java

Converted the exit menu to e4.
* Go to Instrument>Exit
* Confirm that the client closes, asking you if you are sure before hand
---

Ticket2587: Convert Exit Menu to E4

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/ObservableEditableConfiguration.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/ConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DeleteComponentsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/DeleteConfigsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditBlockHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditCurrentConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/LoadConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/blockselector/BlockSelector.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/pv/PvDetailViewModel.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/pv/PvSelector.java

Fix null pointer access when editing a configuration containing an unknown IOC.
https://github.com/ISISComputingGroup/IBEX/issues/2307
- Create a config with a nonsense IOC in it (you'll need to manually edit the XML)
- Edit the config from within ibex gui
- Check that edit configuration dialog comes up and works sensibly except for having an "unknown" description for the nonsense IOC
Also try:
- Somewhere in the editing configurations code, add `throw new RuntimeException()`
- Check that you get an error message when you use the relevant code (rather than nothing happening)
---

Ticket2307 bad configuration errors

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi

Adds extra diagnostic records
https://github.com/ISISComputingGroup/IBEX/issues/2660
Same things are now available in IOC as in labview
---

Add more diagnostics

---

base/uk.ac.stfc.isis.ibex.product/plugin_customization.ini

Add R2 broadcast address to EPICS_CA_ADDR_LIST
See ISISComputingGroup/IBEX#2700
* Check client can switch and access instruments OK outside of R2 network
* Check client can switch and access instruments OK from R2 network 
---

Add R2 broadcast address to EPICS_CA_ADDR_LIST

---

base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/EnableableImageLabel.java
base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/MinimalMotionIndicator.java

Added tooltips to icons on table of motors
https://github.com/ISISComputingGroup/IBEX/issues/2780
Hover over each of the icons under each axis in the Table of Motors and confirm that a sensible tool tip appears.
This is too closely coupled to SWT to easily unit test.
Functionality seems to small to warrant a system test.
Functionality seems to small to warrant documentation change 
---

Ticket 2780: Added tooltips to icons on Table of Motors

---

base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/multiple_choppers.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Mk3Chopper/single_chopper_control_panel.opi

- Add an LED for remote mode
- Clear up a couple of warnings about border colours in the OPI
https://github.com/ISISComputingGroup/IBEX/issues/2605
---

Add LED for remote mode

---

base/uk.ac.stfc.isis.ibex.opis/resources/emma_chopper_lift.opi
base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper_lift.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

https://github.com/ISISComputingGroup/IBEX/issues/2365
No unit tests applicable for OPIs
IOC system tests have been added, see IOC test framework pull request for details
Handover document added to the manuals shared drive
---

Ticket2365 emma chopper lift

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper_lift.opi

Add in forgotten ASG settings for emma fermi chopper

Add forgotten asgs

---

base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/SynopticModel.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/SynopticPresenter.java
base/uk.ac.stfc.isis.ibex.ui.targets/src/uk/ac/stfc/isis/ibex/ui/targets/OpiTargetView.java

Extra logging code for https://github.com/ISISComputingGroup/IBEX/issues/1575
https://github.com/ISISComputingGroup/IBEX/issues/1575
On error (remove address in synoptic xml) error is written to console.
Just logging so none
None
None
---

Add some extra error logging code

---

base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper_Master.opi

Changed PVs on park open/closed buttons to display correct values of angles.
Removed rule to control visibility of shaft position label so that it's always shown.
Reduced displayed precision of shaft angle to 1dp.  Also renamed 'position' to 'angle'.
https://github.com/ISISComputingGroup/IBEX/issues/2567
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide …

Ticket2567 skf chopper parking angles

---

base/uk.ac.stfc.isis.ibex.databases/src/uk/ac/stfc/isis/ibex/databases/Rdb.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalField.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/OnInstrumentSwitch.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer.tests/src/uk/ac/stfc/isis/ibex/ui/journalviewer/tests/JournalViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/models/JournalViewModel.java

Extracts journal data from the database and dumps it to the screen.
As per the ticket description, this does not do any fancy formatting, it just makes the data available.
https://github.com/ISISComputingGroup/IBEX/issues/2903
Viewmodel tests added. Model tests not added because it's hard to mock the database connection.
None. RCPTT tests no longer in development. Squish not set up yet.
---

Ticket2903 jv extract data

---

Jenkinsfile

Run jenkins build every day

---

base/uk.ac.stfc.isis.ibex.journal/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/Journal.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalField.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalRow.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/formatters/DateTimeJournalFormatter.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/formatters/DecimalPlacesFormatter.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/formatters/DurationJournalFormatter.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/formatters/IJournalFormatter.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/formatters/NoopJournalFormatter.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.journalviewer/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerUI.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/JournalViewerView.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/models/JournalViewModel.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

Adds a table to visualise the Journal in IBEX.
After discussion with @John-Holt-Tessella I also removed the continuous refresh, in favour of refreshing whenever the perspective is reopened.
https://github.com/ISISComputingGroup/IBEX/issues/2905
- Table displays journal data appropriately
Nothing testable, just GUI code.
No current system test framework
Not needed
---

Ticket2905 journal viewer table

---

Jenkinsfile
build/jenkins_build.bat

Copy E4 build to directory

---

build/install_client.bat
build/jenkins_build.bat

Making E4 build work correctly

Ticket2954 squish e4 client install

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

Adds individual interlocks to GUI for danfysik
https://github.com/ISISComputingGroup/IBEX/issues/2838
- Interlocks available
OPI, none
IOC system tests
Manuals added to shared drive
---

Ticket2838

---

base/uk.ac.stfc.isis.ibex.opis/resources/Lakeshore460/Lakeshore460.opi

OPI Changes to Lakeshore 460. 
Addition of 'Advanced' tab which displays the raw value PVs created in the IOC as part of this ticket.

Added 'Advanced' tab to OPI to display more values

---

base/uk.ac.stfc.isis.ibex.opis/resources/triton/triton.opi

Remove valve states from TRITON opi.
https://github.com/ISISComputingGroup/IBEX/issues/3030
Valve states are gone
Not applicable
None added, minimal change
---

Remove valves from OPI

---

base/uk.ac.stfc.isis.ibex.nicos.tests/src/uk/ac/stfc/isis/ibex/nicos/NicosModelTest.java
base/uk.ac.stfc.isis.ibex.nicos/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosModel.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/QueueScript.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/scriptstatus/GetScriptStatus.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/scriptstatus/QueuedScript.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/scriptstatus/ReceiveScriptStatus.java
base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/NicosView.java
base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/dialogs/ExistingScriptDialog.java
base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/dialogs/QueueScriptPanel.java
base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/models/QueueScriptViewModel.java

Added the ability to view the queued scripts in NICOS.
https://github.com/ISISComputingGroup/IBEX/issues/2540
* Queued scripts are displayed
* When the queue changes (new scripts added or old ones finishing) the display is updated
* When many scripts are queued there is a scroll bar
* 
Added unit tests to the backend for the nicos connection.
Not currently doing
No additional documentation required.
---

Ticket 2540: View NICOS Queue

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi

Added tool tips to the perspective buttons
See https://github.com/ISISComputingGroup/IBEX/issues/2892
Hover over each perspective button, confirm it gives a sensible tooltip.
---

Ticket 2892: Tooltips for perspectives

---

base/uk.ac.stfc.isis.ibex.opis/resources/JulaboFP50.opi
base/uk.ac.stfc.isis.ibex.opis/resources/TPG300.opi
build/check_build.py
build/check_jenkins_build.py
build/purge_archive_client.py

TPG300 and JulaboFP50 now update on HEARTBEAT.
Also updated the layout of TPG300.
https://github.com/ISISComputingGroup/IBEX/issues/3100
Ensure the graphs for both devices constantly update.
Check the OPI for TPG300 is correct.
None.
None.
None
---

Ticket3100 make graphs update

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/Table.java

Quick change, means that script generator is no longer sortable.
Flash reviewed by @John-Holt-Tessella

Added null comparator to script generator

---

base/uk.ac.stfc.isis.ibex.opis/resources/FZJ_DD_Fermi_Chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

OPI for the FZJ Digital Drive Fermi Chopper
https://github.com/ISISComputingGroup/IBEX/issues/2814
A fully functional OPI which adheres to the current standards.
Requires https://github.com/ISISComputingGroup/IBEX/issues/2856 to be completed first, although this OPI can be mostly tested with the emulator from that ticket, not necessarily the hardware.
---

Ticket2814 OPI for FZJ DD Fermi Chopper

---

base/uk.ac.stfc.isis.ibex.opis/resources/itc503.opi
base/uk.ac.stfc.isis.ibex.opis/resources/itc503/itc503.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds an OPI for the ITC 503
https://github.com/ISISComputingGroup/IBEX/issues/2593
OPI is appropriate (see labview in `C:\LabVIEW Modules\Oxford Software\SOLOITCFRONTPANEL` for a reference point)
None
See syststem tests pr
None
---

Add ITC OPI

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/experimentsetup/timechannels/XmlBackedTimeChannels.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/timechannels/TimeChannelsPanel.java

Fix databinding in the GUI. Wasn't working because it was running on the wrong thread
https://github.com/ISISComputingGroup/IBEX/issues/3232
- Databinding to GUI works (if you change TCB mode via python or a different GUI, the view updates)
None added - this is a UI/threading change and very hard to test
None
None
---

Ticket3252 tcb

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationViewModel.java

In the DAE run information tab, I added three new components:
-Buffer Used Fraction
-Data Size
-Data Rate
https://github.com/ISISComputingGroup/IBEX/issues/3131
On the GUI, in the DAE run information tab, the three new components should appear.
They should also have updating values with DAE3 instruments (ie ZOOM).
Not applicable.
Not applicable.
No related documentation found.
---

Added event mode parameters to the DAE run information tab.

---

base/uk.ac.stfc.isis.ibex.opis/resources/cryValve.opi
base/uk.ac.stfc.isis.ibex.opis/resources/double_monitor.opi
base/uk.ac.stfc.isis.ibex.opis/resources/monitor.opi

Fix the broken OPIs
https://github.com/ISISComputingGroup/IBEX/issues/3265
1. Monitor opi works when looking at LARMOR (NB monitor number is broken see #3268
1. Double monitor OPI works
1. Cry Valve OPI works with simulated IOC.
No needs it is an OPI change.
No needs it is an OPI change.
No needs fixes a bug.
---

update opis, so that they work again

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

Added LED display to signal problem in interlock water flow for Danfysik 8800.
https://github.com/ISISComputingGroup/IBEX/issues/3292
- There is a display that reflects the water interlock PV on Danfysik 8800.
None required.
None required.
None available.
---

Added LED display to signal problem in interlock water flow

---

base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/models/TargetPropertiesViewModel.java

Corrected a checkstyle error.
None as it's just a checkstyle error.
The checkstyle error is corrected
None.
None.
None.
---

Corrected checkstyle error

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

OPI stated that file was for ramping and lookup. It now states just PID and Max Output Lookup which is all it does.

Update label on OPI to avoid confusion

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product

Update the launchers name so that IBEx runs as ibex-client

Update launcher name

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi

Remove unneeded menu option

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java

For ticket: https://github.com/ISISComputingGroup/IBEX/issues/3330
All relevant details on the E3 pull request: https://github.com/ISISComputingGroup/ibex_gui/pull/757

Fix memory leak

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/NicosErrorState.java

Use script server instead of nicos

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/DefaultNamesTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/DefaultName.java

Fix bug when following workflow stated in ticket.
https://github.com/ISISComputingGroup/IBEX/issues/3438
Unit test added which exposes the bug and tests the fx
Not needed for this change - adequate unit test coverage
None.
---

Ticket3438

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

Label now shows ramp units in <temperature unit>/min
https://github.com/ISISComputingGroup/IBEX/issues/3263
- Ramp units are displayed correctly
- Ramp units change if new calibration file uses different units
None
None 
None
---

Added new label for ramp units

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayConfiguration.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/Subscription.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsMenu.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/HiddenGroupFilter.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/views/BlocksView.java

Added a message in the GUI to inform users when they are disconnected from the IBEX server
https://github.com/ISISComputingGroup/IBEX/issues/3420
- When an instrument is disconnected, the user can see an error.
- When the instrument connects, blocks display normally.
- When the instrument disconnects while the user is viewing it, the message shows again.
None
None
None
---

Ticket3420 gui message when server not started

---

base/uk.ac.stfc.isis.ibex.opis/resources/live_view.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Update PV names in liveview OPI and also add macro for multiple detectors
ISISComputingGroup/IBEX#3381
* A liveview with DET=1 or DET=2 can be added and connect to PVs
---

Update for new paths

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationViewModel.java

Just set the value of total current to the right value that is goodcurrent
https://github.com/ISISComputingGroup/IBEX/issues/3504
---

Fix total current

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plots.opi

Adds a spectrum plot OPI
https://github.com/ISISComputingGroup/IBEX/issues/3537
- Spectrum plot OPI displays spectra sensibly
None, OPI only
None, OPI only
None added
---

Add spectra plot OPI

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/Login.java

See https://github.com/ISISComputingGroup/IBEX/issues/3273
See https://github.com/ISISComputingGroup/EPICS/pull/136
---

Ticket 3273: Changed password due to changing NICOS protocol

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/ca/ca.xml
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevAdditionalInterpreterSettings.java

See https://github.com/ISISComputingGroup/IBEX/issues/3419
To test:
* Confirm you can access an instrument on a client through wifi/vpn
---

Ticket 3419: Corrected address list for diirt

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/component_pos.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_angle.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/setTooltipFromDescription.py

Add descriptions into OPI, for beamline parameters on front panel and question marks on tracking components on componetns tab.
Also make in motion and stop all buttons point at correct PV.
https://github.com/ISISComputingGroup/IBEX/issues/3586
1. Descriptions shown above theta and supermirror
1. Descriptions shown on hover over question mark
1. Stop all and in motion pv work.
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the …

Add description and fix stop all and in motion buttons

---

base/uk.ac.stfc.isis.ibex.opis/resources/induction_furnace.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Updates to OPI for induction furnace test board
https://github.com/ISISComputingGroup/IBEX/issues/3681
None
On manuals shared drive
---

Update OPI with new information.

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/vertical_jaws.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

This reverts commit 3e10a5edd0bf062da022e43b84fee62db0e4f9cd.
https://github.com/ISISComputingGroup/IBEX/issues/3717
---

Revert "removed jaws opi from this branch"

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper.opi

Add button to fermi chopper OPI to open troubleshooting wiki page.
https://github.com/ISISComputingGroup/IBEX/issues/3679
Button opens wiki page
None, OPI only
Added to wiki page.
---

Add button to OPI to open troubleshooting wiki page

---

base/uk.ac.stfc.isis.ibex.opis/resources/induction_furnace.opi

Flash reviewed by @John-Holt-Tessella

Update OPI to reflect changes made with user

---

base/uk.ac.stfc.isis.ibex.opis/resources/knr1050.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Created the Knauer 1050 HPLC OPI.
Fixes: https://github.com/ISISComputingGroup/IBEX/issues/3262
---

Ticket3262 add ioc knr1050

---

base/uk.ac.stfc.isis.ibex.opis/check_OPI_format_utils/colour_checker.py
base/uk.ac.stfc.isis.ibex.opis/check_opi_format_tests.py
base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi

Fixed the background colour on the Eurotherm OPI
See https://github.com/ISISComputingGroup/IBEX/issues/2809. I could not reproduce the reported issue but fixed this issue whilst testing.
---

Ticket 2809: Fixed background colour of eurotherm OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/astrium_choppers/astrium_choppers.opi
base/uk.ac.stfc.isis.ibex.opis/resources/astrium_choppers/single_chopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

See https://github.com/ISISComputingGroup/IBEX/issues/3740
Run the OPI with the device in RECSIM/DEVSIM and confirm it connects.
Also confirm that you can only press the calibrate button if both choppers are in E_STOP (see the ioc test for how to set this up)
---

Ticket 3740: Added Astrium Chopper OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/moxa1262.opi

Points OPI to correct PV names. Flash reviewed by @Tom-Willemsen

Fix PV names in OPI

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

FIx failing jenkins build
None
Jenkins build works
n/a
n/a
n/a
---

Fix javax mail dependency

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

The Eurotherm ramp set point was unclear, as it shared an identical name with the temperature set point. I updated the grouping of the temperature, ramp and, device controls into seperate group containers. Initially I was just going to prefix the setpoint name, but this would result in naming inconsistencies. I noticed that there were also layout inconsistencies as well. As such I felt the design could be modified to group these components together, with identical component layouts (i.e., SP inputs aligned). 
After some discussion the `Ramping` label was changed to `Heating` to provide distinction between being in the state of a ramp, and actively ramping to the setpoint temperature.
This ticket also absorbed the work of #3984. This was a minor change to change the RATE interest level to …

Ticket 3964 - Updated OPI to more clearly group controls and their set points

---

base/uk.ac.stfc.isis.ibex.opis/resources/live_view/live_view.opi

Add box to fix detector liveview period (0 meaning always show current period)
See ISISComputingGroup/IBEX#3839
In multiperiod run, period = 0 means data will cheangew with period. Other number will mean data will not update when the period is changed
---

Add fix period option for liveview

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
base/uk.ac.stfc.isis.ibex.opis/resources/template.opi

Add link and info making users aware of the different meanings of current and voltage.
Clicking on link opens external browser.
https://github.com/ISISComputingGroup/IBEX/issues/3912
1. Help text is useful and clicking `more information...` open Kepco page
None, opi change
None, it is hard to system test opi and it is not a big enough change to need a manual test.
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Kepco
and opi template
---

Add link to kepco page. Open external browser

---

base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/SynchrotronObservables.java
base/uk.ac.stfc.isis.ibex.beamstatus/src/uk/ac/stfc/isis/ibex/beamstatus/internal/Observables.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoView.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/SynchrotronPanel.java

Add parameters listed in https://github.com/ISISComputingGroup/IBEX/issues/3986
https://github.com/ISISComputingGroup/IBEX/issues/3986
- Parameters are visible in the GUI in a similar way to the existing parameters (frequency, current)
No testable logic added
No testable logic added
Not required.
---

Ticket3986

---

base/uk.ac.stfc.isis.ibex.opis/resources/induction_furnace.opi
base/uk.ac.stfc.isis.ibex.opis/resources/induction_furnace_thermocouple_details.opi

https://github.com/ISISComputingGroup/IBEX/issues/4042
---

Update induction furnace interface

---

base/uk.ac.stfc.isis.ibex.opis/resources/mezflipper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Add Mezei flipper OPI
https://github.com/ISISComputingGroup/IBEX/issues/3738
OPI works
n/a
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Mezei-Spin-Flipper
---

Ticket3738

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/blades_script.py
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_diagram.opi

Moved jaws calculations into one script and off of the GUI thread.
See https://github.com/ISISComputingGroup/IBEX/issues/3764
To test:
* On master create a jawset and reflectometry sever (see https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/191)
* Open a jaws OPI and reflectometry OPI
* Start a move of the jaws
* Switch between OPIs, notice that the GUI slows right down and stops getting updates from the motors as quickly
* Do the same on this branch, hopefully the speed will be much improved
* Confirm that the jaws diagram still works as expected
Added notes about threading in:
* https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-programming-tips-and-limitations
* https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OPI-Creation
---

Ticket 4081: Very unresponsive jaws

---

base/uk.ac.stfc.isis.ibex.logger.tests/.classpath
base/uk.ac.stfc.isis.ibex.logger.tests/.project
base/uk.ac.stfc.isis.ibex.logger.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.logger.tests/build.properties
base/uk.ac.stfc.isis.ibex.logger.tests/pom.xml
base/uk.ac.stfc.isis.ibex.logger.tests/src/uk/ac/stfc/isis/ibex/logger/tests/LoggerUtilsTests.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/LoggerUtils.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/DoubleListEditor.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/components/ComponentEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/groups/GroupEditorViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/groups/GroupsEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.dae.tests/src/uk/ac/stfc/isis/ibex/ui/dae/tests/DetectorDiagnosticsViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.dae/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/DaeViewModel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/detectordiagnostics/DetectorDiagnosticsPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/detectordiagnostics/DetectorDiagnosticsTable.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/detectordiagnostics/DetectorDiagnosticsViewModel.java

Cleaned up code in general and avoided exceptions in some places
See https://github.com/ISISComputingGroup/IBEX/issues/4076
---

Ticket 4076: Clean up exceptions

---

base/uk.ac.stfc.isis.ibex.opis/resources/ips.opi

Point OPI at new "user" field PVs rather than the ones straight from the device
https://github.com/ISISComputingGroup/IBEX/issues/3995
OPI displays user field appropriately
n/a, OPI
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OxfordInstrumentsIPS
---

Ticket3995

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/IocAvailablePVsTable.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/IocPVDetailsPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/IocPVsEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/PVSelectorPanel.java

* Fixed a bug where the PV values could not be edited (see https://github.com/ISISComputingGroup/IBEX/issues/4059)
* Added a button to copy PV values
* The bug outlined in the original ticket has gone.
* The duplicate PV Values button works as expected
UI heavy, would require a large refactor to be able to write tests
N/A
---

Ticket 4059: Setting PV Values

---

base/uk.ac.stfc.isis.ibex.opis/resources/dh2000.opi

Add second shutter
See ISISComputingGroup/IBEX#4161
* second shutter visible and controllable
---

Add second shutter

---

base/uk.ac.stfc.isis.ibex.opis/resources/mezflipper.opi

https://github.com/ISISComputingGroup/IBEX/issues/4124
---

Take filename off OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/lakeshore340.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Add OPI for lakeshore 340
https://github.com/ISISComputingGroup/IBEX/issues/3992
OPI is appropriate and has equivalent functionality to VI
Not required
See wiki
---

Ticket3992 lakeshore 340

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/pv/BlockServerAddresses.java

Remove unused command
https://github.com/ISISComputingGroup/IBEX/issues/4110
Works as before
n/a
n/a
n/a
---

Remove unused code

---

base/uk.ac.stfc.isis.ibex.opis/resources/jsco4180.opi

- Added tabbed container to hold User/Advanced content
- Reset device button added
- Label added to components to notify user to attempt a device reset if unable to set component values
- Moved the device error status to the front panel (not hidden)
- Updated record names to account for DB changes
Ticket: [#4199](https://github.com/ISISComputingGroup/IBEX/issues/4199)
---

Ticket 4199 - JASCO 4180 reset local component mode

---

base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/DisplayChannels.py
base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/DisplaySummary.py
base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/UpdateChannels.py

"Fix" import problem. In lieu of proper fix https://github.com/ISISComputingGroup/IBEX/issues/4350.
https://github.com/ISISComputingGroup/IBEX/issues/4341
None see ticket with proper fix
None see ticket with proper fix
None see ticket with proper fix
---

Hack to make imports work see #4350

---

base/uk.ac.stfc.isis.ibex.opis/resources/TPG36x.opi
base/uk.ac.stfc.isis.ibex.opis/resources/TPGx6x_common.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

OPI for TPG36x
https://github.com/ISISComputingGroup/IBEX/issues/3484
- OPI is appropriate
n/a
On wiki
---

Add OPI for TPG36x

---

base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper_Master.opi

Make chopper 3 on IMAT act like others
https://github.com/ISISComputingGroup/IBEX/issues/4111
chopper 3 is not special-cased to be a T0
n/a, opi only
n/a, opi only
n/a, opi only
---

Treat chopper 3 the same as the others.

---

base/uk.ac.stfc.isis.ibex.opis/resources/ips.opi

Removed the set persistent buttons from User, and added warning messages which appear in both User and Advanced if non-persistent mode is selected.
https://github.com/ISISComputingGroup/IBEX/issues/4426
---

Ticket4426: Added IPS non-persistent mode warning message.

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi

Use correct label

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupRow.java

Added new bindings to dynamically update the tool-tips when the value or description is updated.
https://github.com/ISISComputingGroup/IBEX/issues/3778
---

Made block tooltips update dynamically.

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

add default

---

base/uk.ac.stfc.isis.ibex.ui.help/resources/iconlicences.txt

Quick removal of typos from icon license file
https://github.com/ISISComputingGroup/IBEX/issues/4495
Icon sources are now correct
---

Ticket4495 GUI: Correct typos in icon license file

---

base/uk.ac.stfc.isis.ibex.opis/resources/heliox.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

OPI for a Mercury Heliox controller.
https://github.com/ISISComputingGroup/IBEX/issues/3739
- OPI is appropriate and contains the same information as the VI (except for the items covered in part 2 of this ticket)
None, OPI only
On wiki.
---

Ticket3739 heliox

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/wm323.opi

Added OPI for controlling the Watson-Marlow 323
https://github.com/ISISComputingGroup/IBEX/issues/3786
---

Added OPI for WM323 pump

---

base/uk.ac.stfc.isis.ibex.opis/resources/heliox.opi

Modifies OPI for regeneration of heliox.
https://github.com/ISISComputingGroup/IBEX/issues/4549
OPI sensible
n/a
On wiki
---

Add status

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/runinformation/RunInformationPanel.java

Make caption clearer
ISISComputingGroup/IBEX#4632
New caption displays as expected
---

Improve caption

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini

Hides NICOS by default
https://github.com/ISISComputingGroup/IBEX/issues/4634
NICOS hidden
n/a no code changes
n/a no code changes
n/a
---

Hide nicos by default

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Update spies feature again to make gui build work.

Update target platform

---

base/uk.ac.stfc.isis.ibex.opis/resources/mkspr4kb/mkspr4kb.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mkspr4kb/mkspr4kb_channel_details.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mkspr4kb/mkspr4kb_content.opi
base/uk.ac.stfc.isis.ibex.opis/resources/nimrod_gas_panel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds OPI for MKS PR4000B and NIMROD gas panel.
ISISComputingGroup/IBEX#4056
OPI is appropriate (both "user" and "details" screens)
n/a
see system tests PR
On wiki
---

Ticket4056 mks pr4000b

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/nimrod_manager.opi

Fixes an incorrect PV name in NIMROD jaws manager

Fix PV name

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/nimrod_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/single_jaw_manager.opi

* Hide setting beam centre
* Display readback of jaws 6 as 'size at sample'
* Run jaws script in different thread
https://github.com/ISISComputingGroup/IBEX/issues/4672
As per ticket
n/a OPI only
OPI only (see also system tests pr)
n/a
---

Minor tweaks for nimrod jaws

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_inout.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi

Updated OPI based on refl server changes
[#4322](https://github.com/ISISComputingGroup/IBEX/issues/4322)
---

Ticket 4322: Change MOVE to ACTION

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/ReadableComponentProperty.java

Adds a couple of files which were manually changed after a merge but didn't get re-added and pushed.

Add files that were accidentally not committed during merge

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Update target platform: spies

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/DeviceDescription.java
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/DeviceScreensDescription.java
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/desc/package-info.java
base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/Application.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/desc/package-info.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/package-info.java
base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/SynopticWriter.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/model/desc/package-info.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevAdditionalInterpreterSettings.java
base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PythonInterpreterProviderFactory.java

Fix a small number of checkstyle warnings introduced during dep. updates

Fix some checkstyles

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/MacroValueValidator.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlockStatusBorderColourConverter.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/RunControlBackgroundColourConverter.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/RunControlForegroundColourConverter.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/RunControlSymbolConverter.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/PVNameValidator.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/TitlePanel.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/widgets/UsersConverter.java
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocButtonPanel.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/component/PvStatusBorderColourConverter.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/GroupNameValidator.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/NumbersOnlyValidator.java
base/uk.ac.stfc.isis.ibex.validators/src/uk/ac/stfc/isis/ibex/validators/SummaryDescriptionValidator.java

Fixed a bunch of warnings of raw types being used.
To test:
* Look how many warnings there are in eclipse before this
* Confirm there are now less
* Confirm gui still builds
---

Fixed some raw type issues

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.ui.blocks.tests/.classpath
base/uk.ac.stfc.isis.ibex.ui.blocks.tests/.project
base/uk.ac.stfc.isis.ibex.ui.blocks.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.blocks.tests/pom.xml
base/uk.ac.stfc.isis.ibex.ui.blocks.tests/src/uk/ac/stfc/isis/ibex/ui/blocks/tests/HiddenGroupFilterTest.java

Updated existing code so that it is a module within the ibex_gui project.
[#4774](https://github.com/ISISComputingGroup/IBEX/issues/4774)
---

Ticket 4774: IBEX_GUI -  *.ui.blocks.tests update and add as module

---

base/uk.ac.stfc.isis.ibex.alarm/src/uk/ac/stfc/isis/ibex/alarm/Alarm.java
base/uk.ac.stfc.isis.ibex.databases/src/uk/ac/stfc/isis/ibex/databases/Rdb.java
base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
base/uk.ac.stfc.isis.ibex.epics/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java

Fix issue in ticket.
https://github.com/ISISComputingGroup/IBEX/issues/4777
See tiket
---

Various bug fixes see ticket

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Update the eclipse spies plugin

Update eclipse spies plugin

---

base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/AlarmButtonViewModel.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/FlashingButton.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/ScriptServerButtonViewModel.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/views/PerspectiveSwitcherView.java

Added visual indicator when the script is running in script server.
https://github.com/ISISComputingGroup/IBEX/issues/3905
Script Server button to show appropriate icon and flash when the script is running
---

Ticket3905 visual indicator nicos running

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_calibrated.opi
base/uk.ac.stfc.isis.ibex.opis/resources/danfysik_uncalibrated.opi

See:
* https://github.com/ISISComputingGroup/IBEX/issues/4348
* https://github.com/ISISComputingGroup/IBEX/issues/4267
* https://github.com/ISISComputingGroup/IBEX/issues/3583
---

Ticket 4348: Harmonise Danfysiks and RIKEN PSUs

---

base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/AlarmButtonViewModel.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/FlashingButton.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/controls/ScriptServerButtonViewModel.java
base/uk.ac.stfc.isis.ibex.e4.ui.perspectiveswitcher/src/uk/ac/stfc/isis/ibex/e4/ui/perspectiveswitcher/views/PerspectiveSwitcherView.java

Resolved checkstyle fix which was created after https://github.com/ISISComputingGroup/ibex_gui/pull/968 was merged onto master.

checkstyle fix from nicos branch merge

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamGraphView.java

Made changes to show week view beam log on top of 24 hours and last hour.
https://github.com/ISISComputingGroup/IBEX/issues/4755
---

Ticket4755 add week view beam log

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin.xml
base/uk.ac.stfc.isis.ibex.opis/resources/ips.opi

Display a warning when the IPS IOC is in major alarm state due to the ACTIVITY PV being Clamped.
https://github.com/ISISComputingGroup/IBEX/issues/4452
Not required
Not required
No changes
---

Ticket4452 ips remote mode and clamped warning

---

base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/IocStateTest.java

Fix compile failure

---

base/uk.ac.stfc.isis.ibex.ui.experimentdetails/src/uk/ac/stfc/isis/ibex/ui/experimentdetails/ExperimentDetailsPanel.java

just changed identifier name from prentComposite to parentComposite
flash review so no ticket
---

fixed mispelling

---

build/jenkins_build.bat

- Fix paths for python in the jenkins_build.bat
- Removed unused variables

Fix IBEX_GUI Jenkins build

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Accept any spies, as the choice doesn't matter.

Care less about exactly which spies are present.

---

base/uk.ac.stfc.isis.ibex.opis/resources/Common Scripts/CopyPVs.py

Jaws Manager now able to set Beam Scraper Jaws.
[#4731](https://github.com/ISISComputingGroup/IBEX/issues/4731)
---

Ticket4731 beam scraper jaws broken jaws manager

---

base/uk.ac.stfc.isis.ibex.feature.css/feature.xml

Fix JSON dependency

---

base/uk.ac.stfc.isis.ibex.feature.css/feature.xml

Removed incorrect json feature

---

base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Be less picky about CS-Studio versions, for https://github.com/ISISComputingGroup/IBEX/issues/4722
NOTE: once you are happy with this PR:
- Move `http://shadow.nd.rl.ac.uk/ICP_P2/css_gui_dependencies/` to `http://shadow.nd.rl.ac.uk/ICP_P2/css_gui_dependencies_old/`
- Move `http://shadow.nd.rl.ac.uk/ICP_P2/css_gui_dependencies_4722/` to `http://shadow.nd.rl.ac.uk/ICP_P2/css_gui_dependencies/`
- Change `css_gui_dependencies_4722` back to `css_gui_dependencies` in `base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target` on this branch
- Then merge the PR as usual

Be less picky about CS-studio build dates

---

base/uk.ac.stfc.isis.ibex.feature.base/feature.xml

Remove accidentally added dependency

---

base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/widgets/LogDisplay.java

The buttons have disappeared from the DAE page this puts them back
Flash
* Buttons are on DAE page
---

If model is non don't access methods on it

---

base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/widgets/LogDisplay.java

Fixed new checkstyle warnings introduced by https://github.com/ISISComputingGroup/ibex_gui/pull/993

Fix new checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ActionParameter.java

Reinstate tests
https://github.com/ISISComputingGroup/IBEX/issues/4759
Tests run under build.bat
---

Reinstate tests and correct inital problem in script generator

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

Mistake made to call incorrect class which could not be resolved. Now calling correct class UIUtils
---

Fixed UIUtils mistake

---

scriptgeneratorJenkinsfile

The script generator was only deploying from the Ticket4164 branch. We want to deploy from master, now changed.
---

Deploy from master

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/McrNewsPanel.java

Fixes UI thread hang when MCR news URL not available due to timeout
https://github.com/ISISComputingGroup/IBEX/issues/5058
closes https://github.com/ISISComputingGroup/IBEX/issues/5058

Fix MCR news hanging UI thread on connection loss

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_pressure.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/updateTabTargets.py
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds OPI for mercury itc pressure card
https://github.com/ISISComputingGroup/IBEX/issues/1286
OPI displays equivalent information as VI
n/a, opi only
none - lvdcom
On wiki.
---

OPI for mercury pressure card

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_pressure.opi

Remove alarm sensitive borders in opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/genesys.opi

Changes genesys OPI to match new style, and add field readbacks
https://github.com/ISISComputingGroup/IBEX/issues/5043
See ticket
none; opi only
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TDK-Lambda-Genesys
---

Ticket5043

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.e4.client.product/pom.xml
base/uk.ac.stfc.isis.scriptgenerator.client.product/pom.xml
base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/pom.xml

Script generator build would not find the correct python due to the build creating python to the wrong version. 
---

Fixing build versioning

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml

These tests were removed but not from the POM

Remove test suite which no longer exists

---

base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/FileMessageDialog.java

Python file was launched with default which happened to be python sometimes. Launch it with notepad++ instead

Fixing launching python file correctly

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Update Py4J version

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/templates/generator_template.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/test_configs/valid_config.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/test_generator.py

When testing on EMU we discovered that generated scripts fail linting. For now, we have decided to disable linting on the generated scripts as the person using them possibly does not have control over the actual code. Adding the `check_script=False` was not a preferred option of the EMU scientists.
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide …

Making sure tests work

---

build/install_script_generator.bat
build/purge_archive_client.py

Dont install genie python this is in the script generator. 
Also Delete old builds from correct directories
https://github.com/ISISComputingGroup/IBEX/issues/4522
Epics utils and genie python are not installed, script generator still works
Correct paths are purged on build.
None
None
None
---

Dont install genie python this is in the script generator. 

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product

Updated the clients java heap size to 1024MB in order to give nominal performance as configurations are edited/reloaded.
#5136

GUI: Updated heap size 512->1024mb

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/action_loader.py

Remove debug

---

build/install_client.bat

print start and finish times
* start and finish times printed
---

Add time start and finish printing

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ConfigLoaderTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/defined_actions/action_loader.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorPython.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ConfigLoader.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ConfigWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonNotReadyException.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

The bug we discovered was that IBEX was trying to get the configs whilst the python process was still beginning. We cannot simply wait for the process to end as it stays active whilst we are running the script generator. 
I have implemented a method to load and reload when python is starting. Python notifies Java that it is ready to accept calls by sending "Python Ready" through the error stream (I could not find a better way to send a signal if you have any ideas please discuss with me). When this signal is received listeners of the PythonInterface are notified that python is ready, they then reload the UI and are able to carry out normal operation. Normal operation is prevented by the PythonInterface when Py4J crashes or is not ready.
Reloading python is more robust than other …

Ticket5120 failure to load scriptgen in ibex

---

base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/PreferenceSupplier.java
base/uk.ac.stfc.isis.ibex.preferences/src/uk/ac/stfc/isis/ibex/preferences/package-info.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/Config.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ConfigLoader.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ConfigWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonNotReadyException.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

There was an increase in checkstyle warnings. Here are some fixes to lower the checkstyle warnings,

Checkstyle warnings fix

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/filters/AssociatedPvFilter.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/filters/FilterFromPVList.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/filters/PVAddressSearch.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/pvs/PVSelectorPanel.java

Adds performance
https://github.com/ISISComputingGroup/IBEX/issues/4648
Performance of find block dialog is better
Difficult (would need a performance test framework; see https://github.com/ISISComputingGroup/IBEX/issues/2102 )
---

Add some performance

---

base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py

- Removed method that was not required caused by merge from master
- Moved widget position check into the standard test class as the requirements for "strict" are somewhat broad

Ticket 4058 - Removed uneeded method and moved test

---

base/uk.ac.stfc.isis.ibex.ui.reflectometry/build.properties
base/uk.ac.stfc.isis.ibex.ui.reflectometry/pom.xml

Add icons dir to build path

---

base/uk.ac.stfc.isis.ibex.opis/resources/mezflipper.opi

https://github.com/ISISComputingGroup/IBEX/issues/4871
---

Ticket4871

---

Jenkinsfile
scriptgeneratorJenkinsfile

Add office 365 connector for jenkins
ISISComputingGroup/IBEX#5344
* Messages pushed to jenkins teams channel
---

Add microsoft teams connector

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.scriptgenerator/build.properties
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionLoader.java
base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini

Bug fixes found when testing the script generator. Formatting ini files to ensure we can manipulate them programmatically for the squish machine.
https://github.com/ISISComputingGroup/IBEX/issues/5090
---

Ticket5090 script gen behaviour testing

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml
base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.client.tycho.parent/suppressions.xml
base/uk.ac.stfc.isis.ibex.devicescreens.tests/.checkstyle
base/uk.ac.stfc.isis.ibex.devicescreens.tests/.project
base/uk.ac.stfc.isis.ibex.e4.client/.checkstyle
base/uk.ac.stfc.isis.ibex.e4.client/.project
base/uk.ac.stfc.isis.ibex.scriptgenerator/.checkstyle
base/uk.ac.stfc.isis.scriptgenerator.client.product/.checkstyle
base/uk.ac.stfc.isis.scriptgenerator.client.product/.project
base/uk.ac.stfc.isis.scriptgenerator.client/.checkstyle
base/uk.ac.stfc.isis.scriptgenerator.client/.project
base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/.project

Update checkstyle for newer checkstyle editors.
checkstyle fix is not possible without this from standup
Checkstyle works in the gui and build
---

Update check style to newest version and add to some projects

---

base/uk.ac.stfc.isis.ibex.ui.nicos/src/uk/ac/stfc/isis/ibex/ui/nicos/NicosCurrentScriptContainer.java

Nicos current script window (under 'Script Server') automatically scrolls to the highlighted line.
https://github.com/ISISComputingGroup/IBEX/issues/5146
Current script window automatically scrolls to the highlighted line when it is out of view.
Too difficult to unit test
None
None
---

Current script window auto-scrolls to highlighted line

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml

Add missing javadoc tests back in

---

build/build_script_generator.bat
build/jenkins_build_script_generator.bat

Use /MT with robocopy

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.ui/src/org/eclipse/wb/swt/ResourceManager.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/PvStateColour.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/StringUtils.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/UI.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/Utils.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/Waiting.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/ColumnComparator.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

Fix checkstyle

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java

For https://github.com/ISISComputingGroup/IBEX/issues/5416

Correctly select row after moving actions

---

build/install_script_generator.bat

Use robocopy to improve install speed of standalone script generator
---

Use robocopy rather than xcopy to install script generator

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi

See https://github.com/ISISComputingGroup/EPICS-ioc/pull/501 and https://github.com/ISISComputingGroup/IBEX/issues/4555
---

Ticket 4555: Added OPI for the SANS2D vacuum system

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/PyDevAdditionalInterpreterSettings.java

https://github.com/ISISComputingGroup/IBEX/issues/5391

Make pydev use ipython

---

base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/config/LoggingConfiguration.java

Fixes logging to console and file in the GUI
GUI logs to console and file correctly
n/a
---

Fix Log4j logging to file

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi

See https://github.com/ISISComputingGroup/IBEX/issues/4559
* Switch your configuration branch to NDXSANS2D
* Start your instrument
* Add a device screen for SANS2D vac system
* Confirm gauges are linked
---

Ticket 4559: Added link to gauge in SANS2D vac OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/dma4500m.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/crisp/important_params_CRISP.opi
base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java

When talking about the script generator to a scientist, we noticed the open manual button was greyed out. This was due to having a 3-millisecond timeout when checking if the manual URL was available to connect to. This PR increases the timeout to 3000 milliseconds and asserts that it is in milliseconds in the variable.
Dummy buttons have been added and the OPIs edited as part of the git hook.
*Highlight and …

Changed timeout

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/build.properties
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/EditSynopticHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/NewSynopticHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/SynopticEditorHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/EditSynopticDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/InstrumentTreeControls.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/instrument/InstrumentTreeView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/model/IInstrumentUpdateListener.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/model/UpdateTypes.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/pv/PvLabelProvider.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/validators/ComponentListValidator.java

Found bug if there is a invalid component because of duplicate names then making it a nested component remove the warning.
Also lots of checkstyle for project.
https://github.com/ISISComputingGroup/IBEX/issues/3376
- Warning showed when duplicate component is nested
None
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/59
None
---

Add validation on add component and checkstyle

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi

Adds auto/manual control for fast shutter on SANS2D
https://github.com/ISISComputingGroup/IBEX/issues/4590
See IOC PR
n/a
n/a
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/DAE-and-the-ICP
---

Add auto/maual control for fast shutter

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi

OPI for SANS2D scraper aperture
https://github.com/ISISComputingGroup/IBEX/issues/4592
---

Add SANS2D scraper aperture

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_level.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi

- Added blank vacuum tank opi
- Large size to account for OPI design (http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf)
- User and advanced tabs
- Advanced is manager mode protected with a Rule
- ~Move all button with no associated action added~ 
- Dummy buttons added to opis by commit hook
https://github.com/ISISComputingGroup/IBEX/issues/4577
sub-ticket of: https://github.com/ISISComputingGroup/IBEX/issues/4576
1. The IBEX GUI provides a blank OPI, ready to accept additional controls for the SANS2D vacuum tank.
1. The Vacuum Tank OPI could have "user" and "advanced" tabs
1. The "advanced" tab is under password control (manager mode)
1. ~The Vacuum Tank OPI provides a "Move All" button (c.f. Reflectometry), so that I can enter all the positions of …

Ticket4577 vacuum tank opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi

Rename aperture 6 axis from APERTURE to SCRAPER

Rename APERTURE to SCRAPER

---

base/uk.ac.stfc.isis.ibex.opis/resources/superlogics.opi

https://github.com/ISISComputingGroup/IBEX/issues/4594
---

Hide channel 1 if not present

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/front_panel.opi

Updated reflectometry IOC prefix in OPI.
Issue: https://github.com/ISISComputingGroup/IBEX/issues/5452

Standard IOC prefix for refl

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/ReceiveSession.java
base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java

Contains changes from https://github.com/ISISComputingGroup/ibex_gui/pull/1157. Already tested and merged into release by @FreddieAkeroyd.
---

Cherry pick release fix

---

base/uk.ac.stfc.isis.ibex.activemq/src/uk/ac/stfc/isis/ibex/activemq/message/MessageParser.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/TempEditableIoc.java

Checkstyle

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Configuration.java
base/uk.ac.stfc.isis.ibex.dashboard/build.properties
base/uk.ac.stfc.isis.ibex.dashboard/src/uk/ac/stfc/isis/ibex/dashboard/DashboardObservables.java
base/uk.ac.stfc.isis.ibex.dashboard/src/uk/ac/stfc/isis/ibex/dashboard/DashboardPv.java
base/uk.ac.stfc.isis.ibex.databases/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.databases/build.properties
base/uk.ac.stfc.isis.ibex.databases/src/uk/ac/stfc/isis/ibex/databases/Databases.java
base/uk.ac.stfc.isis.ibex.devicescreens/build.properties
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/InstrumentUtils.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/config/LoggingConfiguration.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/OpiViewModel.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratedLanguage.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionsWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ScriptGeneratorAction.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ConfigSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/DeleteComponentsDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/MultipleConfigsSelectionDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.dashboard/src/uk/ac/stfc/isis/ibex/ui/dashboard/models/BannerModel.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/ConnectionHandler.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/GraphingConnector.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/SearchInput.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/views/NavigationView.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/views/SelectorView.java

Mostly checkstyle, some project fixes to get rid of errors.
N/A
Nothing changed, project still builds and launches, synoptoic selection and navigation still appear.
N/A
N/A
N/A
---

Check style and project setup changes

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi
base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank_status.opi

Add a vacuum status to the OPI
https://github.com/ISISComputingGroup/IBEX/issues/4578
1. The IBEX GUI provides a visible indicator showing the status of the vacuum in the SANS2D vacuum tank
* a status message should clearly show the vacuum status: `ATMOSPHERE`, `VAC DOWN`, `AT VACUUM`, or `VENTING`
* if the vacuum status cannot be determined, the vacuum indicator should clearly show ERROR: STATUS UNKNOWN and IBEX should raise an alarm
1. genie_python provides a means of querying the vacuum status in the tank section of SANS2D.
1. The vacuum indicator should be duplicated on the Advanced tab.
*Mention any automated tests or manual tests that you have added or …

Set size correctly

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi

Adds OPI elements for SANS2D beam stops in vacuum OPI
https://github.com/ISISComputingGroup/IBEX/issues/4583
N/A
N/A
N/A (OPI change only)
---

Ticket4583

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi

Adds controls for the rear detector beam stop on advanced tab
https://github.com/ISISComputingGroup/IBEX/issues/4584
N/A (OPI only)
N/A (OPI only)
N/A (OPI only)
---
)

Add control for rear detector beam stop strip

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi

Added a part to the OPI that allows control of the front beam stop and notifies the user when inhibited.
https://github.com/ISISComputingGroup/IBEX/issues/4581
1. I can control the rotation of the front beam stop via the IBEX GUI.
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/350
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/SANS2D-Front-Beam-Stop-inhibit-movement
---

Front beamstop control and inhibited light

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_temp.opi

Remove alarm sensitivity on set points
https://github.com/ISISComputingGroup/IBEX/issues/5497
Alarm sensitivity doesn't show on set points
---

Remove alarm sensitivity on set points

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/sample_stack.opi

Change parameter name to be inline with everything else
https://github.com/ISISComputingGroup/IBEX/issues/5424
OPI shows polref config
NA
N/A
N/A
---

Update parameter for height2

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

Update to orbit dependency that exists (closest one)
N/A
GUi builds
-
-
N/A
---

Update orbit dependcy to available one

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/sample_stack.opi

Height should be SAMPHEIGHT like INTER not SAMPOFFSET this is Height2!
-
N/A
---

Fix param name

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi

https://github.com/ISISComputingGroup/IBEX/issues/4586
https://github.com/ISISComputingGroup/IBEX/issues/4586
See ticket
---

Add inidcators saying that motion is disabled

---

base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi

Display Positional Error In Aperture and Waveguide OPI
https://github.com/ISISComputingGroup/IBEX/issues/4572
- The IBEX GUI alerts me when there is a discrepancy between the motor position and the motor encoder on any of the aperture & guide motors.
- The positional error indicator should appear on both the "user" and "advanced" tabs.
---

Positional Error PV Added

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_system.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans2d_scraper_aperture.opi
base/uk.ac.stfc.isis.ibex.opis/resources/waveguide_aperture/waveguide_aperture.opi

https://github.com/ISISComputingGroup/IBEX/issues/5625
---

Minor tweaks

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/HasProtectedElementTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java

Fixed checkstyle warning
Removed unused imports
https://github.com/ISISComputingGroup/IBEX/issues/5062
https://github.com/ISISComputingGroup/ibex_gui/pull/1177
---

Fixed checkstyle warning

---

base/uk.ac.stfc.isis.ibex.opis/resources/mezflipper_v1.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

https://github.com/ISISComputingGroup/IBEX/issues/5545
---

Add back old opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi

https://github.com/ISISComputingGroup/IBEX/issues/4587
---

updated interval pv names

---

base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds the HTS magnet OPI with placeholder fields for the magnet's field, ramp control and calibration. 
ISISComputingGroup/IBEX#5660
- OPI works with existing KEPCO IOC and shows: 
- voltage
- current 
- current setpoint
- OPI Layout looks acceptable as per ISIS conventions
- OPI is added to device screens in GUI. 
- Other fields such as ramp rate, field and calibration are not yet filled in
- Details tab is blank (for this step)
None added or modified. 
None added or modified. 
None added - should I put something in the wiki? 
---

Ticket5660 HTS Magnet OPI first steps

---

base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi

We want to be able to set the min and max fields but not on the OPI, removed here
https://github.com/ISISComputingGroup/IBEX/issues/5660
---

Remove min and max OPI fields

---

base/uk.ac.stfc.isis.ibex.opis/resources/instetc/single_button.opi
base/uk.ac.stfc.isis.ibex.opis/resources/instetc/user_buttons.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Add user buttons
https://github.com/ISISComputingGroup/IBEX/issues/5410
After setup clicking a button runs the script
N/A just an OPI
N/A just an OPI
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Inst-etc-IOC
---

add opis for user buttons

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

https://github.com/ISISComputingGroup/IBEX/issues/5720
---

Add SANS sample changer opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi

Add button to reset and resend setpoints
https://github.com/ISISComputingGroup/IBEX/issues/3185
---

Add button to reset the device and resend setpoints

---

base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi

See https://github.com/ISISComputingGroup/IBEX/issues/5661
OPI, no tests
OPI, no tests
---

Ticket 5661: Hooked up ramping in HTS magnet OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/instetc/user_buttons.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF/important_params.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/POLREF_VERT/important_params.opi

Add laser activate and deactivate to OPI for POLREF
https://github.com/ISISComputingGroup/IBEX/issues/5458
Components can be moved in and out for laser mode
N/A
N/A
N/A
---

Add laser mode to OPI

---

base/uk.ac.stfc.isis.ibex.epics/resources/diirt/datasources/ca/ca.xml

Increase max_array_bytes, likely needed for POLREF
---

Increase max_array_bytes for POLREF

---

base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi

Hooked up selecting the calibration files and getting the field back in the HTS OPI.
See https://github.com/ISISComputingGroup/IBEX/issues/5662
---

Ticket 5662: Added selecting calibration file to HTS magnet opi

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/JavaActionParameter.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ActionParameter.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionLoader.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java

Ticket5968

---

base/uk.ac.stfc.isis.ibex.opis/resources/Metrolab_PT2025.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi
base/uk.ac.stfc.isis.ibex.opis/resources/instetc/single_button.opi
base/uk.ac.stfc.isis.ibex.opis/resources/instetc/user_buttons.opi
base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_flow.opi
base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_single_system.opi
base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

There are a few OPIs which have now deviated from using dummy buttons correctly, this PR fixes those current deviations.
https://github.com/ISISComputingGroup/IBEX/issues/6002
---

Correct dummy buttons

---

base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ActionTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ActionsTableTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ConfigLoaderTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ScriptGeneratorActionTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ScriptGeneratorJsonFileHandlerTest.java

https://github.com/ISISComputingGroup/ibex_gui/pull/1223/files added a new parameter to the ActionParameter but this was not added in the unit tests.
---

Add correct parameter to tests

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/tables/DataboundTable.java

Add a line numbers column to the script generator table
https://github.com/ISISComputingGroup/IBEX/issues/5998
---

Calculate line number; account for new non-editable column

---

base/uk.ac.stfc.isis.ibex.scriptgenerator.tests/src/uk/ac/stfc/isis/ibex/scriptgenerator/tests/ActionsTableTest.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

- Change text on Add/Duplicate/Delete buttons to be more intuitive
- Add insert action below button
https://github.com/ISISComputingGroup/IBEX/issues/5966
---

Ticket5966 inserting lines

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py

fixing typo in script definitions dir name

---

base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/ConfigInfoTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/configuration/HasProtectedElementTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/ConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/editing/EditableConfigurationTest.java
base/uk.ac.stfc.isis.ibex.configserver.tests/src/uk/ac/stfc/isis/ibex/configserver/tests/json/JsonConvertersTest.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Configuration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/ComponentFilteredConfiguration.java
base/uk.ac.stfc.isis.ibex.opis/resources/musr_rotation.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/tests/IocStateTest.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/components/ComponentEditorPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/summary/SummaryPanel.java

https://github.com/ISISComputingGroup/IBEX/issues/5096
---

Ticket5096 componentswitcher

---

base/uk.ac.stfc.isis.ibex.opis/resources/musr_rotation.opi

Added CAEN power supply status in MuSr rotation OPI
https://github.com/ISISComputingGroup/IBEX/issues/5955
- CAEN power supply status is shown in MuSR rotation OPI
- CAEN power supply status is shown in the IBEX banner
---
Make sure you are in the branch `Ticket5955` in your configs area.

Added CAEN power supply status

---

base/uk.ac.stfc.isis.ibex.opis/resources/musr_steering.opi

fix macro propagation in musr steering opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/itc503/musr_dual_itc503.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

OPI for two ITC503s side by side. TEMP1 and TEMP2 macros are to specify which IOCs to use
https://github.com/ISISComputingGroup/IBEX/issues/5958
see ticket
---

Ticket5958 musr dual itc503

---

base/uk.ac.stfc.isis.ibex.opis/resources/lakeshore340.opi

OPI additions to control excitation features in the lakeshore 340.
https://github.com/ISISComputingGroup/IBEX/issues/5950
---

Add setting excitation on input A to lakeshore 340 opi

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/DisplayBlock.java
base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/IsisLog.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/config/LoggingConfiguration.java
base/uk.ac.stfc.isis.ibex.opis/src/uk/ac/stfc/isis/ibex/opis/Opi.java
base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

**When merged, we will need to update `css_gui_dependencies` on `ICP_P2` to be the new branch and then change this PR back to pointing at that area. If you do not know how to do this please ask and I can show you**
https://github.com/ISISComputingGroup/IBEX/issues/5302
Open or create an OPI with errors, confirm that the errors appear in the log but do not appear in any BOY console within the GUI.
On master confirm that the errors do appear within the GUI in a BOY console.
N/a configuration/target platform changes only
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to …

Ticket5302

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

point target platform at build not ticket 5302 (see #5302)
https://github.com/ISISComputingGroup/IBEX/issues/5302
GUI builds
N/A
N/A
---

Update dependency path after ticket

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

Box containing slew rate info was placed over other parts of the OPI, move it
---

danfysik opi: Fix slew rate placement

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java

Offset editing support column from viewer table focus column and coax value into range
To test:
- Tab across table whilst entering values to affect the validity of the row
- Copy and paste rows (selecting both editable and non-editable rows)
- Check validity on inserted rows are correct
- Check log doesn't have any index out of bounds errors
https://github.com/ISISComputingGroup/IBEX/issues/6204
*Highlight and provide a link …

Fix script generator exception on entering data

---

base/uk.ac.stfc.isis.ibex.ui.banner.tests/src/uk/ac/stfc/isis/ibex/ui/banner/tests/ServerStatusViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ServerStatus.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ServerStatusColourConverter.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ServerStatusViewModel.java

rename running -> up

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/displaying/RuncontrolState.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockFactory.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/Dehexer.java
base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/internal/UserDetailsSerialiser.java
base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/sql/SqlWhereClause.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionLoader.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionsWrapper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/EditConfigurationsHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/RecentItems.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/ConfigHelper.java

Fixes checkstyle warnings.
* Confirm build still passes
* Confirm less checkstyle warnings
---

Fix various checkstyle warnings across the GUI

---

base/uk.ac.stfc.isis.ibex.opis/resources/3hefridge.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds a device screen for the 3he fridge system on musr. 
ISISComputingGroup/IBEX#6244
See ticket
None
None 
---

Ticket6244 - Adding OPI for 3he fridge system

---

base/uk.ac.stfc.isis.ibex.targetplatform/uk.ac.stfc.isis.ibex.targetplatform.target

https://github.com/ISISComputingGroup/IBEX/issues/6289
---

Point at ICP P2 area

---

base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_system/individual_magnet.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hifimags.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

https://github.com/ISISComputingGroup/IBEX/issues/6221
---

Ticket6221

---

base/uk.ac.stfc.isis.ibex.opis/resources/musr_rotation.opi

Add buttons to turn all PSUs on/off
https://github.com/ISISComputingGroup/IBEX/issues/6379
---

musr_rotation.opi: Add buttons to turn all psus on/off

---

base/uk.ac.stfc.isis.ibex.opis/resources/ttiex355p.opi

Move field to remove scrollbar as MuSR thought it was a button to set the output mode.
---

Fix placing to remove scrollbar

---

base/uk.ac.stfc.isis.ibex.opis/resources/musr_steering.opi

Ticket6133 musr steering save

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

rename live view to detector live view

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

See https://github.com/ISISComputingGroup/IBEX/issues/6392
---

Ticket 6392: Rename select changer to select rack

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

See https://github.com/ISISComputingGroup/IBEX/issues/6409
(Note: Contains changes from https://github.com/ISISComputingGroup/IBEX/issues/6392 so merge that first)
---

Ticket6409 select any position

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

Fix the issues that I should have fixed in https://github.com/ISISComputingGroup/IBEX/issues/6392
Moved every value to 2 dps.
---

Tidy up some minor requests from scientists

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

ISISComputingGroup/IBEX#6434
---

renaming line to action in script generator column names

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

(Note: contains changes from https://github.com/ISISComputingGroup/IBEX/issues/6409 so merge that first)
See https://github.com/ISISComputingGroup/IBEX/issues/6414
To test:
* With https://github.com/ISISComputingGroup/EPICS-motionSetPoints/pull/21 pulled and made start the samplechanger IOC_test_framework test
* Set an arbitrary position for x/y and confirm the motor move there
* Set a specific named position and confirm the motor moves there
---

Ticket 6414: Allow arbitrary position

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sample_changer.opi

Discovered when checking for https://github.com/ISISComputingGroup/IBEX/issues/6486. Fix incorrect stationary PVs.
---

Correct sample changer PVs

---

base/uk.ac.stfc.isis.ibex.opis/resources/fermi_chopper_lift.opi

The Emma OPI
https://github.com/ISISComputingGroup/IBEX/issues/6450
When running a SKF chopper in recsim, the OPI correctly displays the levitation status and the buttons. The buttons should not be clickable unless the status is idle or in alarm.
OPI are hard to test.
OPI are hard to test.
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Fermi-Chopper-Lifter
---

Ticket6450 Changed Emma chopper lift OPI to work with new chopper controller

---

base/uk.ac.stfc.isis.ibex.opis/resources/musr_steering.opi

To review: 
Check that default value display is shown when on NDXMUSR branch with correct values and looks sensible
---

Add default values display for musr steering opi

---

build/jenkins_build_script_generator.bat

Strip Release_Script_Gen_ rather than just Release_ from version
https://github.com/ISISComputingGroup/IBEX/issues/6402
---

Strip Release_Script_Gen_ rather than just Release_ from version

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/detectordiagnostics/DetectorDiagnosticsModel.java
base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/sql/SqlStatement.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/internal/PVPrefixFactory.java
base/uk.ac.stfc.isis.ibex.instrument/src/uk/ac/stfc/isis/ibex/instrument/list/InstrumentListUtils.java
base/uk.ac.stfc.isis.ibex.journal/src/uk/ac/stfc/isis/ibex/journal/JournalModel.java
base/uk.ac.stfc.isis.ibex.log/src/uk/ac/stfc/isis/ibex/log/rdb/LogMessageQuery.java
base/uk.ac.stfc.isis.ibex.log/src/uk/ac/stfc/isis/ibex/log/rdb/SqlStatement.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/IsisLog.java
base/uk.ac.stfc.isis.ibex.managermode/src/uk/ac/stfc/isis/ibex/managermode/PasswordHasher.java
base/uk.ac.stfc.isis.ibex.model/src/uk/ac/stfc/isis/ibex/model/ModelObject.java
base/uk.ac.stfc.isis.ibex.synoptic/src/uk/ac/stfc/isis/ibex/synoptic/internal/Variables.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/views/BannerView.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamGraphView.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/ConfigurationViewModels.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/DeleteComponentsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewBlockHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/SaveConfigDialog.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/macros/MacroPanel.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupTableViewer.java
base/uk.ac.stfc.isis.ibex.ui.journalviewer/src/uk/ac/stfc/isis/ibex/ui/journalviewer/models/JournalViewModel.java
base/uk.ac.stfc.isis.ibex.ui.log/src/uk/ac/stfc/isis/ibex/ui/log/save/LogMessageFileWriter.java
base/uk.ac.stfc.isis.ibex.ui.mainmenu/src/uk/ac/stfc/isis/ibex/ui/mainmenu/managermode/ManagerModeHandler.java
base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/TableOfMotorsSettingsViewModel.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorHelpMenuItems.java
base/uk.ac.stfc.isis.ibex.ui.synoptic/src/uk/ac/stfc/isis/ibex/ui/synoptic/SynopticPresenter.java
base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/TabIsShownListener.java

fixing more checkstyle warnings - easy wins

---

base/uk.ac.stfc.isis.ibex.experimentdetails.tests/src/uk/ac/stfc/isis/ibex/experimentdetails/tests/database/SqlStatementTest.java
base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/database/ExperimentIDQuery.java
base/uk.ac.stfc.isis.ibex.experimentdetails/src/uk/ac/stfc/isis/ibex/experimentdetails/sql/SqlStatement.java

Removed the GROUP_BY statement, on LET the GROUP_BY was being disallowed as the columns contained non-aggregate data when SELECTing. 
the GROUP_BY wasn't actually used so I have removed all instances of it in the experiment details model, and sorted by experiment id and role (so order should be the same as before)
ISISComputingGroup/IBEX#6451
See Ticket
Order by test added, group by test removed
---

Ticket6451-  RB number lookup

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/comms/ZMQSession.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/GetBanner.java
base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/NICOSMessage.java

The protocol is different between getbanner and other commands. Handle this correctly here.
https://github.com/ISISComputingGroup/IBEX/issues/6542
---

Correct handling of protocol to avoid flashing nicos git window

---

Jenkinsfile

- Get the git branch in a different way
---

Fix getting of branch name to enable gui builds to be deployed

---

base/uk.ac.stfc.isis.ibex.nicos.tests/src/uk/ac/stfc/isis/ibex/nicos/ZMQSessionTest.java

Call real methods of mock to ensure response and calls are correct
If wanting to test:
- Run ZMQSessionTest and confirm all now pass
Flash review
---

Fix failing tests to fix gui build

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/DoubleListEditor.java

Fix components missing scrollbar.
Steps:
- Create lots of components(I created about 30)
- Go to Edit Configuration
- In Components Tab there should be a scrollbar present if the number of components exceeds the default size of the list
- Move components from `Available` to `Selected` and check if the scrollbar appears in the `Selected` list and disappears in `Available`
Instance from the same class is used in another place
- Create lots of blocks ( I created more than 19)
- Go to Configurations->components->edit
- Select a component
- Go to the Groups tab and on the right-hand side check if the scrollbar is present in the `Available` list.
- Move blocks from `Available` to `Selected` and check if the scrollbar appears in the `Selected` list and disappears in `Available`
Also, check if …

List of components missing scrollbar fix

---

build/install_client.bat

Install python 3 instead of python2 in install_client.bat

---

base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml
base/uk.ac.stfc.isis.scriptgenerator.tycho.parent/pom.xml

Can test by running build_script_generator.bat and seeing it doesn't fail anymore
---

Fix build by adding the correct dependencies

---

base/uk.ac.stfc.isis.ibex.ui.help/resources/gethelp.txt

Update contact details
Details correct

Update help details

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/dialogs/SaveScriptGeneratorFileMessageDialog.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Added label with time & date of last script generation. 
Adjusted current parameters file to be updated on time.
https://github.com/ISISComputingGroup/IBEX/issues/6493
N/A
N/A
https://github.com/ISISComputingGroup/IBEX/pull/6616
---

Ticket6493 script gen time of last generation

---

base/uk.ac.stfc.isis.ibex.e4.client/plugin_customization.ini
base/uk.ac.stfc.isis.scriptgenerator.client/plugin_customization.ini

The link to the shadow manual was broken because the directory structure has changed. I have changed to reflect this and also point to the page higher than that one as it gives more options for troubleshooting etc.
---

Correct broken links and link to higher page

---

base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/config/LoggingConfiguration.java
base/uk.ac.stfc.isis.ibex.logger/src/uk/ac/stfc/isis/ibex/logger/preferences/PreferenceConstants.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Fixed file path with leading slash causing stream write errors on log file rollover.
and a few script generator checkstyle fixes
https://github.com/ISISComputingGroup/IBEX/issues/6573
GUI logs do not go blank over time
N/A
N/A
https://github.com/ISISComputingGroup/IBEX/pull/6626
---

Fix empty log file on rollover + script gen checkstyle fixes

---

base/uk.ac.stfc.isis.scriptgenerator.feature.base/feature.xml

Fix broken script generator build
https://github.com/ISISComputingGroup/IBEX/issues/6663
Existing test should be able to catch it
---

Fix script gen build

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java

setting from_ibex env var instead of variable in genie python startup

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionWrapper.java

Global parameters are now usable in script validation.
Genie_python minor fix: https://github.com/ISISComputingGroup/genie_python/pull/344
https://github.com/ISISComputingGroup/IBEX/issues/6620
* Global parameters can be used in the script validation
* Global parameters can be used in running the script
N/A
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/106
https://github.com/ISISComputingGroup/IBEX/pull/6697
---

Script Gen: validate global parameters

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py

https://github.com/ISISComputingGroup/IBEX/issues/6703
To review:
- Check out https://github.com/ISISComputingGroup/ScriptDefinitions/pull/7
- Change value of example param 2 to go in and out of range (1 to 3)
- See that validity updates with it
---

Validate global parameters individually

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

renaming labels

---

base/uk.ac.stfc.isis.ibex.nicos/src/uk/ac/stfc/isis/ibex/nicos/messages/GetBanner.java

This appears to fix the issue on my setup
https://github.com/ISISComputingGroup/IBEX/issues/6696
NICOS works correctly
N/A
N/A
N/A
---

Ticket#6696

---

base/uk.ac.stfc.isis.ibex.ui.configserver/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/AddBlockToComponentHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/AddBlockToConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditComponentHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/EditConfigHelper.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/EditConfigDialog.java

Created options in OPI menu to add the block to select which config or component to add it to
https://github.com/ISISComputingGroup/IBEX/issues/6308
* A user can choose which config/component a new block gets added to from the OPI menu
* There are tests for this
---

Add block to selected config/component from OPI menu

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToComponentHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToConfigHandler.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/helpers/AddBlockToComponentHelper.java

Fixed checkstyle warnings 
https://github.com/ISISComputingGroup/IBEX/issues/6308
---

Tidying up checkstyle warnings

---

base/uk.ac.stfc.isis.ibex.opis/resources/lsicorr.opi

https://github.com/ISISComputingGroup/IBEX/issues/5303
---

added wait pv to user interface

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/run_tests.bat
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/run_tests.sh
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
build/build.bat
build/build.sh
build/build_script_generator.bat
build/run_python_support_tests.bat
build/run_python_support_tests.sh

Run python-support tests as part of the GUI build (Windows and Linux build).
https://github.com/ISISComputingGroup/IBEX/issues/5249
---

Ticket5249 run python support tests

---

base/uk.ac.stfc.isis.ibex.opis/resources/mercuryiTC/mercuryiTC_flow.opi

add pressure readback to mercury itc flow cryostat OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/sans2d_vacuum_tank.opi

add Move all button for vacuum tank sans2d and display message
https://github.com/ISISComputingGroup/IBEX/issues/6785
---

SANS2D tank add move all button and remove older collision message

---

base/uk.ac.stfc.isis.ibex.opis/resources/danfysik.opi

The Dafysik 9X00 interlocks now displays MPS Not Ready instead of MPS Ready.

changed danfysik 9x00 to display not ready instead of ready

---

base/uk.ac.stfc.isis.ibex.e4.client/Application.e4xmi
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/EditSynopticHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/commands/SynopticEditorHandler.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/EditSynopticDialog.java
base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/dialogs/ViewSynopticDialog.java

View remote synoptics from your local IBEX.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/4957)
- Can view synoptics remotely 
- Does not break any other changes

View remote synoptics

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

See https://github.com/ISISComputingGroup/IBEX/issues/6736
---

Ticket 6736: Added messagebox for errors on the sans sample changer opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/sans_sample_changer.opi

Buttons were copied from Motor's OPI to preserve graphical consistency
[
*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6743)
Acceptance criteria:
Stop button in Sample changer OPI is present
Stop button stops the movement of relevant motors
---

Ticket6743 Added buttons to stop relevant motors to the OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi

add mntcycles sp to opi

---

base/uk.ac.stfc.isis.ibex.e4.client.product/ibex.product

add Dlog4j2.formatMsgNoLookups=true to ibex.product

---

base/uk.ac.stfc.isis.ibex.logger/.classpath
base/uk.ac.stfc.isis.ibex.logger/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.logger/build.properties

Fix reference to log4j for new update
---

Update references to new log4j

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi

removed uneccesary LED and spinners
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6033)
---

removed uneccesary LED and spinners

---

build/build.bat

making build.bat more verbose

---

base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Extra tab for new controller IOC.  Required for LET.
N/A
6th tab present on OPI
---

Added additional tab for 6th IOC

---

base/uk.ac.stfc.isis.ibex.ui.about/src/uk/ac/stfc/isis/ibex/ui/about/BaseVersionPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockGroupPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockGroupViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockLogSettingsPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockRunControlPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java

Edited the "add block" dialog to include a checkbox and dropdown that allows a user to add the block to the group. 
[*Link to Ticket*
](https://github.com/ISISComputingGroup/IBEX/issues/6307)
See ticket
---

Ticket6307 add block from context menu to group

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/WISH_Jaws.opi

See [ticket](https://github.com/ISISComputingGroup/IBEX/issues/7012) for information.
[7012](https://github.com/ISISComputingGroup/IBEX/issues/7012)
---

Removed drop-down, added sixth set, tidied layout

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsMenu.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java

Groups will now stack vertically in blocks menu. Option to sort groups according to a size-based algorithm added. Added buttons to collapse groups.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/3512)
---

Ticket 3512 GUI stack small groups on top of each other

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupRow.java
base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java

Implemented acceptance criteria. Additionally panel's code made more reliable - the groups will now no longer randomly become wider/smaller and jitter while resizing the panel.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7039)
Groups indicate that they are collapsed
Alarm status of blocks in a group transfers to group
---

Ticket7039 GUI groups panel improvements

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/webcam/webcam.opi

Add OPI to display data from WEBCAM ioc
https://github.com/ISISComputingGroup/IBEX/issues/7146
* image of webcam displayed in OPI
---

Add webcam opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/3hefridge.opi

Ticket6243 hardware testing

---

base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java

Bug fixed
[*Link to Ticket*
](https://github.com/ISISComputingGroup/IBEX/issues/7060)
---

 Ticket7060 GUI: Fix text in groups panel disappearing when resizing

---

base/uk.ac.stfc.isis.ibex.ui.banner/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocControlHandler.java

[*Add your own description here*](https://github.com/ISISComputingGroup/IBEX/issues/7137)
---

Ticket7137 bug fixed

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/tosca_sample_changer/tosca_sample_positioner.opi
base/uk.ac.stfc.isis.ibex.opis/resources/webcam/webcam.opi
base/uk.ac.stfc.isis.ibex.opis/resources/webcam/webcam_image.opi
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Use webcam opi for tosca smpchng

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Fix `opi_info.xml`
None
`opi_info.xml` is valid and relevant opis can be selected from gui
n/a
n/a
n/a
---

Fix opi_info.xml corrupted by Technix PSU merge.

---

base/uk.ac.stfc.isis.ibex.opis/resources/tosca_sample_changer/tosca_sample_positioner.opi

only show coarse/fine move box if in manager mode

---

base/uk.ac.stfc.isis.ibex.opis/resources/3hefridge.opi

Ticket7168 3he fixes

---

base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi

[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6774)
---

Ticket 6774 pearlpc cell and pump pressure

---

base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi

- Add pressure and pressure difference to opi. 
- Fix graph updates.
https://github.com/ISISComputingGroup/IBEX/issues/6770
See ticket
See support module PR for IOC tests.
---

Add pressure and pressure difference to opi. Fix graph updates.

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi
base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi

- https://github.com/ISISComputingGroup/IBEX/issues/6764
- https://github.com/ISISComputingGroup/IBEX/issues/7193
- https://github.com/ISISComputingGroup/IBEX/issues/7044
- https://github.com/ISISComputingGroup/IBEX/issues/6779
- https://github.com/ISISComputingGroup/IBEX/issues/6768
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide …

Ticket 7193

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm.opi

Add tabs for channels 8-10 added as part of https://github.com/ISISComputingGroup/IBEX/issues/7026 to Eurotherm OPI.

Add chan 8-10 tabs to Eurotherm OPI

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupText.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/ExperimentSetup.java

Should prevent changes not showing in the GUI
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7138)
---

Ticket7138 Introducing a potential fix to the problem entirely

---

base/uk.ac.stfc.isis.ibex.opis/resources/fmr.opi

enable PREC from PV for FMR PVs

---

base/uk.ac.stfc.isis.ibex.opis/resources/GP2.opi
base/uk.ac.stfc.isis.ibex.opis/resources/areaDetector/2DView.opi
base/uk.ac.stfc.isis.ibex.opis/resources/live_view/live_view.opi

Resize GP2 graphs to fix profile cross hairs issue, also make loc:// variables unique
Cross hairs appear in det summed view (still missing from det tof view, but not important)
---

Resize graphs and fix local variables

---

base/uk.ac.stfc.isis.ibex.ui/src/uk/ac/stfc/isis/ibex/ui/JMXServer.java

Adds JMX connection details to a file in the root directory of the client install

Add JMX connection details to a file

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Block.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableBlock.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/EditableConfiguration.java
base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/internal/DisplayUtils.java
base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/InstrumentSwitchers.java
base/uk.ac.stfc.isis.ibex.epics.switching/src/uk/ac/stfc/isis/ibex/epics/switching/ObservableFactory.java

Checkstyle fixes

---

base/uk.ac.stfc.isis.ibex.ui.configserver/plugin.xml

remove option to add block to a config - see ticket #7224

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.devicescreens.tests/.project
base/uk.ac.stfc.isis.ibex.feature.base/feature.xml
base/uk.ac.stfc.isis.ibex.model.tests/.classpath
base/uk.ac.stfc.isis.ibex.ui.configserver.tests/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/tests/IocPatternFilterTest.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/AddPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/IocPatternFilter.java
base/uk.ac.stfc.isis.ibex.ui.ioccontrol.tests/.classpath
base/uk.ac.stfc.isis.ibex.ui.ioccontrol.tests/.project
base/uk.ac.stfc.isis.ibex.ui.ioccontrol.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.ioccontrol.tests/build.properties
base/uk.ac.stfc.isis.ibex.ui.ioccontrol.tests/pom.xml
base/uk.ac.stfc.isis.ibex.ui.ioccontrol.tests/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/table/tests/IOCPatternFilterTest.java
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/IocPanel.java
base/uk.ac.stfc.isis.ibex.ui.ioccontrol/src/uk/ac/stfc/isis/ibex/ui/ioccontrol/table/IOCPatternFilter.java
base/uk.ac.stfc.isis.scriptgenerator.client.product/.project

Added search functionality for the IOC selection dialogs.
https://github.com/ISISComputingGroup/IBEX/issues/7236
See ticket.
Added unit tests to `ui.configserver.tests`, and added the project `ui.ioccontrol.tests`. Both test the correctness of the search filter.
---

Ticket7236 ioc selection dialog search

---

base/uk.ac.stfc.isis.ibex.opis/resources/technix.opi

OPI changes from hardware testing
https://github.com/ISISComputingGroup/IBEX/issues/7129
See ticket
---

OPI changes from hardware testing

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/inout_motion_setpoints.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position_part.opi

Added a pair of Labels and Text Inputs to the Motion Setpoints OPIs that show the Motion Setpoints file name and a possible error message that's shown if there was an error with processing the file.
https://github.com/ISISComputingGroup/IBEX/issues/6425
The information shown is correct and does not break the UI.
---

Ticket6425 add file checks

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/transtechnik.opi

https://github.com/ISISComputingGroup/IBEX/issues/6942
---

Add transtechnik OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/tjmper.opi

Added the TJMPER OPI.
https://github.com/ISISComputingGroup/IBEX/issues/7253
See ticket.
---

Ticket7253 tjmper phase 1

---

base/uk.ac.stfc.isis.ibex.opis/resources/Lakeshore336/Lakeshore336.opi

Updated the Lakeshore336 OPI to 4 outputs/loops.
https://github.com/ISISComputingGroup/IBEX/issues/7261
See ticket.
---

Ticket7261

---

base/uk.ac.stfc.isis.ibex.ui.configserver/plugin.xml

Reverted changes in https://github.com/ISISComputingGroup/IBEX/issues/7230.
https://github.com/ISISComputingGroup/IBEX/issues/7224
See ticket.
---

Ticket7224

---

base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/Activator.java

Forgot to add a couple of javadocs in a recent pr

Appease checkstyle

---

base/uk.ac.stfc.isis.ibex.opis/resources/technix.opi

Change text input to spinner on request by Richard Hale
Only changes commissioning view; not user view

Change text input to spinner with 500V steps

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single_temp.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

New OPI
Adds an OPI containing the `Eurotherm_single.opi`, similar to `Eurotherm.opi` but without the tabs.
Closes: ISISComputingGroup/IBEX#4673
User can use the new OPI to view a single temperature sensor.
---

4673 Eurotherm Single Temperature Sensor

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/hgaps.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/important_params.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/sample_stack.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/vgaps.opi

Added OFFSPEC OPIs for the Reflectometry Front Panel.
https://github.com/ISISComputingGroup/IBEX/issues/7328
See ticket.
---

Ticket7328

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/stress_rig/stress_rig.opi

https://github.com/ISISComputingGroup/IBEX/issues/7296
---

Ticket7296 instron arby

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

Fixed `Stop` button in Galil Engineering View OPI.
https://github.com/ISISComputingGroup/IBEX/issues/7342
See ticket.
---

Ticket7342

---

base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchWindowAdvisor.java

Multiple client instance detection is now handled by using a file lock.
https://github.com/ISISComputingGroup/IBEX/issues/7381
See ticket.
---

Ticket7381

---

base/uk.ac.stfc.isis.ibex.opis/resources/keylkg.opi

Updated the Keylkg OPI to allow controlling the scan rate.
https://github.com/ISISComputingGroup/IBEX/issues/7376
See ticket.
---

Ticket7376

---

base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/spectraplots/PersistedLocalChannel.java

Added background thread so that if the attempt to write an initial value to a local PV fails, the write is re-attempted. Has a re-attempt limit of 30 seconds.
[*Ticket #7386*](https://github.com/ISISComputingGroup/IBEX/issues/7386)
See manual system test **section 9, test 21**
---

Ticket #7386

---

base/uk.ac.stfc.isis.ibex.opis/resources/hts_magnet.opi

Fix several niggles on HTS magnet OPI
https://github.com/ISISComputingGroup/IBEX/issues/7397
See ticket
---

HTS niggles

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorProperties.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/ScriptGeneratorSingleton.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/AbstractGenerator.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorContext.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/generation/GeneratorPython.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/PythonInterface.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/pythoninterface/ScriptDefinitionsWrapper.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ScriptGeneratorAction.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

Added functionality to return custom outputs from a script when using the Script Generator. Can return any number of outputs and display each one as a new table column.
https://github.com/ISISComputingGroup/IBEX/issues/6382
See ticket and comments.
---

Ticket6382

---

base/uk.ac.stfc.isis.ibex.ui.graphing.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibModelTests.java
base/uk.ac.stfc.isis.ibex.ui.graphing.tests/src/uk/ac/stfc/isis/ibex/ui/graphing/tests/MatplotlibViewModelTests.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibCursorPosition.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigure.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibFigureViewModel.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketEndpoint.java
base/uk.ac.stfc.isis.ibex.ui.graphing/src/uk/ac/stfc/isis/ibex/ui/graphing/websocketview/MatplotlibWebsocketModel.java

When hovering over a matplotlib graph, coordinates of the hovered-over point are shown.
https://github.com/ISISComputingGroup/IBEX/issues/7406
See ticket
Yes
---

Ticket7406

---

base/uk.ac.stfc.isis.ibex.banner/src/uk/ac/stfc/isis/ibex/banner/ObservableCustomControl.java
base/uk.ac.stfc.isis.ibex.client.tycho.parent/checkstyle.xml
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/DeviceScreens.java
base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/DeviceScreensModel.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/CustomControlModel.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/views/BannerView.java

Remove finalizers and update our checkstyle config to ban finalizers
https://github.com/ISISComputingGroup/IBEX/issues/7275
See ticket
---

Remove finalizers

---

base/uk.ac.stfc.isis.ibex.configserver/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.epics.tests/META-INF/MANIFEST.MF
base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/json/LowercaseEnumTypeAdapterFactoryTest.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/json/LowercaseEnumTypeAdapterFactory.java
base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target

Fix deserialization of attributes marked with @SerializedName

---

base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/json/LowercaseEnumTypeAdapterFactoryTest.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/json/LowercaseEnumTypeAdapterFactory.java

A bad merge crept in during https://github.com/ISISComputingGroup/ibex_gui/pull/1496 , probably my fault.
Fix this and add a unit test to prevent it reocurring

Fix serialization again

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_align.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_list_redefine.opi

Added `Define`, `Move` buttons to the Reflectometry OPI redefinition tab.
https://github.com/ISISComputingGroup/IBEX/issues/7070
See ticket.
---

Ticket7070

---

base/uk.ac.stfc.isis.ibex.opis/resources/galil/general_io_standalone.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

See https://github.com/ISISComputingGroup/IBEX/issues/7479

Add standalone general i/o screen

---

base/uk.ac.stfc.isis.ibex.opis/resources/rules_tests.opi

Tests for https://github.com/ISISComputingGroup/cs-studio/pull/11

Add test case

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/sandals_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

add sandals jaws manager opi

---

base/uk.ac.stfc.isis.ibex.ui.banner.tests/src/uk/ac/stfc/isis/ibex/ui/banner/tests/ServerStatusViewModelTest.java
base/uk.ac.stfc.isis.ibex.ui.banner/src/uk/ac/stfc/isis/ibex/ui/banner/models/ServerStatusViewModel.java

fix dae status indicator, add test for this

---

base/uk.ac.stfc.isis.ibex.ui.banner.tests/src/uk/ac/stfc/isis/ibex/ui/banner/tests/ServerStatusViewModelTest.java

fix checkstyle - remove unused import of java.util.List

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml
base/uk.ac.stfc.isis.ibex.model.tests/pom.xml

Actually run all of the tests in the GUI.

Run the tests in the GUI

---

base/uk.ac.stfc.isis.ibex.opis/resources/keithley_2000.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

https://github.com/ISISComputingGroup/IBEX/issues/2460

Add OPI for keithley 2000

---

base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target

update target platform to pydev branch for disabling autocomplete

---

base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2290/Keithley2290.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Added Keithley 2290 power supply OPI.
https://github.com/ISISComputingGroup/IBEX/issues/7468
- Keithley 2290-10 can be controlled in IBEX
- Has emulator
- Has tests
- Has OPI
Unit tests in https://github.com/ISISComputingGroup/EPICS-KeithleyHVPS.git test operation in normal and error-state scenarios, including alarms.
The application has been tested manually through the OPI and by use of caget/caput.
https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Keithley-2290
---

Added Keithley 2290 power supply OPI.

---

base/uk.ac.stfc.isis.ibex.opis/resources/Eurotherm_single.opi

Ticket6931 eurotherm output rate control

---

base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/setup_graph.py
base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/superlogics.opi

Update the OPI to support a Strain Gauge module.
Adding the script that sets up the graph for each type of module also fixes the existing issue where if an input was marked as not connected the graph would show the Disconnected warning.
https://github.com/ISISComputingGroup/IBEX/issues/7561
See ticket.
---

Ticket7561

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Removed space in RIKEN vacuum target in `opi_info.xml`
---

Removed space in RIKEN vacuum target

---

base/uk.ac.stfc.isis.ibex.opis/resources/SKFG5Chopper/SKFChopper_Master.opi

Remove rule.

---

base/uk.ac.stfc.isis.ibex.opis/resources/spectra_plot.opi

using ISISDAE_01 for spectra plot heartbeat

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/ImportComponentDialog.java

Use shadow hosted user manual.

---

base/uk.ac.stfc.isis.ibex.opis/resources/ips.opi

After work on this [ticket](https://github.com/ISISComputingGroup/IBEX/issues/6891) and extra [correction](https://github.com/ISISComputingGroup/EPICS-ioc/pull/774/files), useful to have an indicator to show 'heater timer' status on OPI.
none - flash review as only an LED, label and visibility rule for both

Add heater on time OK indicator to IPS OPI

---

base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/HelpButton.java

Fix double creation.

---

base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon_energyspec.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAEN_hexagon_hvchannel.opi

Initial Hexagon GUI

---

base/uk.ac.stfc.isis.ibex.ui.synoptic.editor/src/uk/ac/stfc/isis/ibex/ui/synoptic/editor/target/selector/TargetSelectorViewModel.java

changed:  if (isIconDefault == false) to if (!isIconDefault) 
---

changed logic to complie with changestyle

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
base/uk.ac.stfc.isis.ibex.opis/resources/galil/single_axis_params.opi

Ticket4390 read homing routines as pv

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi

[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7837)
---

Ticket 7837

---

base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/RIKEN_magnet_PSUs.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row_kicker.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row_technix.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/indiviudal_port_row_transtechnik.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Magnet/psu_magnet_status_XFD.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/RIKEN_vacuum_synoptic.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/Vacuum/vacuum valve.opi

Fixed RB2 PVs, swapped on and off valve logic in opi, and corrected bb3 to lv3, added ability to open line valves

fix minor riken issues

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/horizontal_jaws.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/pearl_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/single_horizontal_jaw_manager.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Add PEARL jaws manager OPI, mostly a copy of sandals_manager.opi with slight modifications for the first jaw
https://github.com/ISISComputingGroup/IBEX/issues/6045
See ticket
No change
No change
No change
---

Ticket6045

---

base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2700/keithley_scanner_values.opi

Reset Timestamp OPI and Overflow status indicator added to the keithley2700
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7916)
See ticket
---

added a reset timestamp opu and indicator

---

base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi

Add RF Output ON/OFF switch
https://github.com/ISISComputingGroup/IBEX/issues/7877
See ticket
no tests
no tests
To make OPI work IOC db and protocol file needed modification to accommodate for new PV
---

Ticket 7877 opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi

https://github.com/ISISComputingGroup/IBEX/issues/6044
---

Ticket6044

---

build/install_gui_with_builtin_python.bat

Ticket7909 recopy pydev cmdhist

---

base/uk.ac.stfc.isis.ibex.opis/resources/kepco.opi

Display kepco range
See ISISComputingGroup/IBEX#7945
---

KEPCO: display current range mode

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelDelay.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Burst.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Delay.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Manage.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Outputs.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645StatusRegister.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Trigger.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi

Adding save and recall configurations into the OPI 
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7888)
---

Ticket7888 save load sttgs

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelDelay.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Burst.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Delay.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Manage.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Outputs.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645StatusRegister.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/comunity/srsDG645Trigger.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi

* read some dropdown items from PV rather than hardcode
* add experimental Advanced button based on community GUI
See ISISComputingGroup/IBEX#7893
---

Adjust to read items from PV, add advanced and local/remote

---

base/uk.ac.stfc.isis.ibex.opis/resources/moxa1242.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Added an opi for the 1242, and added that to the opi.xml
https://github.com/ISISComputingGroup/IBEX/issues/7875
N/A - we dot not run unit tests on OPIs
N/A - we do not (to my knowledge) check every single OPI during system tests
---

Ticket7875 add iologik1242 to our ioc

---

base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

add inter beckhoff diagnostics OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/TPG300.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

- Add status RBVs for each pressure gauge
- Title now controlled by PV so displays TPG500/TPG300 depending on model
- Hide 'Relay contact status' group and A/B threshold violation LEDs for TPG500s
- Add RBV for device error status
- Update OPI description
[#7458](https://github.com/ISISComputingGroup/IBEX/issues/7458)
---

Update TPG300 OPI to support TPG500

---

base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_eventspec.opi

Add event spectra files

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/pearl/singlemotoralignment.opi

An OPI was created for the single Galil which controls the Sample on PEARL, so they can now "tweak" it, along with moving it in other ways. This was created as a copy of the "mymotor.opi".
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6048)
---

New OPI for PEARL Sample Alignment created from mymotor copy

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.py

https://github.com/ISISComputingGroup/IBEX/issues/7889
---

Synchronise graphs

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/editing/BlockFactory.java
base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/NewBlockHandler.java

fix beam status block local box

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/ChannelRB.opi
base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi

This PR serves to merge only the automatic changes to the XML that are applied on saving an OPI in CS-Studio. (These are changes to whitespace and closing tag formatting that are not functional or visible in the OPI). Merging this PR should make it easier to review the second PR where the desired changes have been made.
[#7887](https://github.com/ISISComputingGroup/IBEX/issues/7887)
The changes should not alter the functionality or appearance of the OPI at all.

DG645 automatically applied OPI formatting changes 

---

base/uk.ac.stfc.isis.ibex.opis/resources/pre4500.opi

fix time axis for pre4500 - see NDXMERLIN vs local client

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/script_definition_loader.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/templates/generator_template.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_generator.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ActionsTable.java
base/uk.ac.stfc.isis.ibex.scriptgenerator/src/uk/ac/stfc/isis/ibex/scriptgenerator/table/ScriptGeneratorAction.java

Edited the template file to add a comment a stating the `action #` next to each corresponding action.
Edited the template file to add a comment stating where the main action running commands are ran from.
Preserved the params order for the actions by commenting out an unneeded conversion to a format it was already in that was, after debugging, causing the reordering of the `key:val` pairs within each dictionary of params in the list of actions.
[#6658](https://github.com/ISISComputingGroup/IBEX/issues/6658)
Thoughts from Muons on what would be useful:
- Ensure parameters in function call are in same order as in script generator table
- Generate comment above runscript calls that this is the actually executing code
- Generate comment next to each runscript instruction that links it to an …

Added the changes in Thomas' ticket comment

---

base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/git_utils.py
base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/test_git_utils.py
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

A pop-up message dialog was changed to remove ability to do git updates, in place of prompting the user to contact their local authority to do so. Some logic was also changed, to allow for a message dialog to tell the user they had a dirty repo, or unstaged/uncommitted changes, to the script generator repository.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/7932)
No Unit tests were added.
No system tests were added. For the reviewer, clone the[ script definitions git repository](https://github.com/ISISComputingGroup/ScriptDefinitions) to a Instrument/Settings/ibex_script_generator/ folder on your machine. 
1. After cloning, make sure you're up to date with the remote repo. 
2. Then, from eclipse, find scriptgenerator.product in …

Changed doGitActions to remove user ability to update

---

base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi

add clause for not disabling home button for a beckhoff

---

base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_current.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/temperature_table.opi

Simple OPI change that adds a linking container to temperature tabs pointing to magnet current opi.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8060)
---

Show magnet current in tabs

---

base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi

remove units sp option, add vent status and SP

---

base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_managers/pearl_manager.opi

remove superfluous mm label from pearl jaws manager opi

---

base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position_part.opi

show full filepath for motion setpoints

---

base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/VTypeFormatToConversionsTest.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/conversion/VTypeDefaultFormatter.java

In cases where precision was being set to a big number (say 8 or 12), the number used to occupy all the available space. Therefore the unit was no more visible. This was OK if the number had many significant digits, however if the number didn't have many significant digits, precision implementation was padding zeroes at the end. In such a case the unit not being visible is an issue. 
Refer #8013
https://github.com/ISISComputingGroup/IBEX/issues/8013
1. The code should follow standard coding practices - Formatting, style, commenting, copyright etc.
2. There should be adequate unit test coverage
3. The code should build and the fix should be verifiable on the GUI.
1. Tested the case where precision reduces the digits in the original number
2. Tested the case where precision increases the …

Ticket8013 unhide unit

---

base/uk.ac.stfc.isis.ibex.opis/resources/Common Scripts/setEnabled.py
base/uk.ac.stfc.isis.ibex.opis/resources/PEARLPC.opi

Add setEnabled script to pressure sp and control buttons

---

build/build.bat

make maven parallelised

---

base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/individual_magnet_table_25_to_32.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/MagnetTemperature/temperature_table.opi

Add missing taps onto second tab (RQ2 magnet)

Ticket8097 add missing taps

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/Constants.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
base/uk.ac.stfc.isis.ibex.ui.widgets/src/uk/ac/stfc/isis/ibex/ui/widgets/IBEXButtonFactory.java

Ticket8108 script gen refactor

---

base/uk.ac.stfc.isis.ibex.opis/resources/pearl/singlemotoralignment.opi

add manager mode visible statement to pearl alignment motor controls

---

base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon.opi
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsValidityChangeListener.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorView.java
base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

For meaningful changes check difference in commit 618482770b25b862442f604e4f0136e2a74a597b
The next one is just re-indenting all the lines in the file
https://github.com/ISISComputingGroup/IBEX/issues/6899
---

Ticket6899 script gen invalid action

---

base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi

add stop kinematics button which sends 0 to RUN_KINEMATICS

---

base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_event_energyspec.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_eventspec.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/psu_control.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/separator_tuning.opi
base/uk.ac.stfc.isis.ibex.opis/resources/aeroflex.opi
base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi
base/uk.ac.stfc.isis.ibex.opis/resources/dhp30330.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hifi_main_cryomag_advanced.opi
base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi
base/uk.ac.stfc.isis.ibex.opis/resources/moxa1242.opi
base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi
base/uk.ac.stfc.isis.ibex.opis/resources/pre4500.opi
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/param_move.opi
base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi
base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi

Add dummy widgets to opis that were missing them.
https://github.com/ISISComputingGroup/IBEX/issues/8117
---

Add missing dummy widgets to opis

---

base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java

This change fixes the tabbing issue described in https://github.com/ISISComputingGroup/IBEX/issues/8122
https://github.com/ISISComputingGroup/IBEX/issues/8122
---

Fixed Tab out issue for enum scripts

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/OFFSPEC/sample_stack.opi

swapping height and height2 on offspec sample stack panel

---

base/uk.ac.stfc.isis.ibex.opis/resources/LM500.opi
base/uk.ac.stfc.isis.ibex.opis/resources/LM500_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Add OPI for LM500
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6136)
---

Ticket6136 add opi lm500

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettings.java
base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettingsProperties.java

fix checkstyle - suppression not working

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/dataacquisition/DaeSettings.java
base/uk.ac.stfc.isis.ibex.ui.dae/src/uk/ac/stfc/isis/ibex/ui/dae/experimentsetup/DaeExperimentSetupSpinner.java

https://github.com/ISISComputingGroup/IBEX/issues/7944
---

Dispatch property change event on UI thread

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/ConfigServer.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToConfigHandler.java

disable adding block when there are no configs to add it to

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/AddBlockToConfigHandler.java

Include original enable condition for handler

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.opis/resources/ARGUS/magnet_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java

Added a new OPI directory for ARGUS and in there added an OPI file for ARGUS magnets' trans and long statuses.
[5879](https://github.com/ISISComputingGroup/IBEX/issues/5879)
1. The ARGUS Magnet Status OPI displays the following fields.
1. Magnet Temperature (inferred from water temperature)
1. Magnet Water Flow rate (l/m) (to 1 decimal place)
1. Klixon status (FAULT/OK)
1. Water flow status and rate of PSU (Longitudinal only)
1. MOL (Magnet On Light) status
---

Ticket5879_argus_magnet_status_opi

---

Jenkinsfile
parse_rules

Change parse rules and disable unstableOnWarning

---

base/uk.ac.stfc.isis.ibex.targetplatform/targetplatform.target

re enable auto complete in pydev

---

base/uk.ac.stfc.isis.ibex.utilities/.classpath
base/uk.ac.stfc.isis.ibex.utilities/.project
base/uk.ac.stfc.isis.ibex.utilities/src/uk/ac/stfc/isis/ibex/utilities/GetVMInfo.java

Added utility to get Debug port. The Java file has the description of the usage
---

Added utility to get Debug port

---

base/uk.ac.stfc.isis.ibex.client.tycho.parent/pom.xml

Added missing test to pom.xml file.
---

Update to pom.xml

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/Configurations.java
base/uk.ac.stfc.isis.ibex.epics/src/uk/ac/stfc/isis/ibex/epics/observing/LoggingObserver.java
base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxaInfoPanel.java
base/uk.ac.stfc.isis.ibex.ui.moxas/src/uk/ac/stfc/isis/ibex/ui/moxas/views/MoxasViewModel.java

The issue with the Moxa change with periodic auto-refresh is that after refresh the Moxa display state is lost. So an expanded Moxa is getting collapsed after refresh. Following changes have been done:
1. Added logic to extract hostname of the Moxa and use it as the key for registering expanded items.
2. Added logic to extract IOC port-list to match with the previously expanded Moxa items.
3. Added logic to create loggers with specific log level to log values through Logging Observable.
4. Used the new Logging Observable for Moxa details at Debug Level to avoid producing too many logs.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8185) …

Ticket 8185 ibex gui retain moxa display state

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_axis.opi

change beckhoff eng. view to allow TC_XX

---

base/uk.ac.stfc.isis.ibex.opis/resources/automatic_needle_valve.opi

See ISISComputingGroup/IBEX#8223
---

Add extra parameters

---

base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/Block.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockSetPanel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/BlockSetViewModel.java
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/blocks/EditBlockDialog.java

Add ability to create block sets.
[Here](https://github.com/ISISComputingGroup/IBEX/issues/7642)
You can add block sets to a block from the edit block dialogue.
---

Ticket7642 set blocks on config change

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/populate_list.py
base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/string_value.opi

fix string constants not being displayed correctly in the constants tab

---

base/uk.ac.stfc.isis.ibex.ui.motor/src/uk/ac/stfc/isis/ibex/ui/motor/views/MinimalMotorViewModel.java

See ticket for detailed description. Comment in file should help explain the solution.
---

Fix advanced view toggle bug

---

base/uk.ac.stfc.isis.ibex.e4.product/src/uk/ac/stfc/isis/ibex/e4/product/ApplicationWorkbenchAdvisor.java

Add message about server still running on client close

---

base/uk.ac.stfc.isis.ibex.ui.beamstatus/src/uk/ac/stfc/isis/ibex/ui/beamstatus/views/BeamInfoMenu.java
base/uk.ac.stfc.isis.ibex.ui.configserver/plugin.xml
base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/commands/CopyPVToClipboardHandler.java

add option to add PV to clipboard from device screen/ToM/beam status view

---

base/uk.ac.stfc.isis.ibex.opis/resources/Keithley2400/SourceMode.opi

This work extends the IOC functionality to the IBEX GUI to include input for Compliance Voltage and Current. 
https://github.com/ISISComputingGroup/IBEX/issues/8262
Contact Jamie Nutter - USG for actual safety compliance requirements to make sure IBEX passes
--Probably should be done after we've tested this from our own side
---

Add input fields for compliance volt and curr, and set limits for them

---

base/uk.ac.stfc.isis.ibex.opis/resources/HV/Scripts/DisplayChannels.py

Remove spurious quote character making python invalid and stopping caen summary from working

Fix typo in summary script

---

build/install_gui_with_builtin_python.bat

Add RMI hostname property
See ISISComputingGroup/IBEX#7615
ibex-client.ini modified as expected
---

Add RMI hostname after install

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/tekdmm40X0.opi

add OPI for tektronix dmm4040/4050 multimeters

---

base/uk.ac.stfc.isis.ibex.utilities/.classpath

Removed Absolute Dependency In Utilities package created for JVM Info
The GUI should not give any related error when building the eclipse workspace
None required
None required
---
No code change
No release notes

Removed Absolute Dependency In Utilities

---

base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/editing/iocs/dialog/AddPanel.java

Sets the search bar of the Add IOC panel to be focused on load via the filtered tree.
---

Set the search bar of the Add IOC panel to be focused on load

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Change SR850 device screen type to OSCILLOSCOPE

---

base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000.opi
base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000_single.opi
base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000_single_old.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Use original opi file in tabbed view as the default control ui

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Add missing xml tags to opi_info.xml

---

base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller/field_strength.opi

fixes the size of a container
For [Ticket8379](https://github.com/ISISComputingGroup/IBEX/issues/8379)

fix container size in zfmagfld

---

base/uk.ac.stfc.isis.ibex.opis/resources/inter_beckhoff_params.opi

Removes some stray labels which were to the right of the populated bit of the OPI - they are already shown in the "Errors" group box
---

remove some floating text fields which are already displayed

---

base/uk.ac.stfc.isis.ibex.opis/resources/reflectometry/SURF/important_params.opi

change sm in beam (no longer used) to FOM in beam

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java
base/uk.ac.stfc.isis.ibex.opis/resources/hameg/hm8123.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hameg/hm8123_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java

Ticket6210 chipir hameg

---

base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi

- Added identifying motor controller IOC to oscillating collimator OPI.
- Added motor number to oscillating collimator OPI.
[Ticket#8421](https://github.com/ISISComputingGroup/IBEX/issues/8421)
---

Added identifying motor controller to collimator OPI

---

build/jenkins_build.bat
build/jenkins_build_script_generator.bat

Added a '-' to the folder creation file for BUILDS
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8329)
Creation of Builds all follow the same format "BUILD-####"
---

Ticket 8329

---

base/uk.ac.stfc.isis.ibex.opis/resources/dds_tensile_stress_rig.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/sxd_tensile_stress_rig.opi

Add OPI for the DDS Tensile Stress Rig
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8265)
---

Ticket8265 add ioc dds stress rig

---

Jenkinsfile
base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py
base/uk.ac.stfc.isis.ibex.opis/resources/Motor/details.opi
base/uk.ac.stfc.isis.ibex.opis/resources/Motor/mymotor.opi
base/uk.ac.stfc.isis.ibex.opis/resources/OscillatingCollimator/OscillatingCollimator.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hifi_main_cryomag.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hrpd_in_situ_dsc.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/horizontal_jaws.opi
base/uk.ac.stfc.isis.ibex.opis/resources/jaws/jaws_base.opi
base/uk.ac.stfc.isis.ibex.opis/resources/pearl/singlemotoralignment.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stage/motion_setpoint_position.opi
base/uk.ac.stfc.isis.ibex.opis/resources/superlogics/superlogics.opi
base/uk.ac.stfc.isis.ibex.opis/resources/twincat/twincat_engineering.opi

This PR:
- Changes usages of const syntax to `loc://` PVs
- Adds a new test to `check_opi_format.py` to ensure we don't introduce const syntax again later
- Actually runs the `check_opi_format.py` tests properly in jenkins
- Removes some tests from "strict" `check_opi_format.py` tests as they fail on a large number of OPIs and we want to run these tests in CI.
https://github.com/isiscomputinggroup/ibex/issues/8278
See ticket for very detailed testing plan
`check_opi_format.py` in this PR verifies that we don't add these again in future.
I noticed `check_opi_format.py` wasn't actually running in Jenkins so have fixed that, which then meant I had to demote some colour tests from "strict" to "non-strict" to avoid this ticket balooning.
---

Replace uses of =1 with loc:// pvs

---

base/uk.ac.stfc.isis.ibex.opis/resources/ALDN1000/aldn1000.opi
base/uk.ac.stfc.isis.ibex.opis/resources/LM500_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/PS300.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/argus_magnet_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/chronus_magnet_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/RIKEN/magnet_status.opi
base/uk.ac.stfc.isis.ibex.opis/resources/chipir_collimator/chipircollimator.opi
base/uk.ac.stfc.isis.ibex.opis/resources/envmon.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hameg/hm8123.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hameg/hm8123_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/he3nmr/he3nmr.opi
base/uk.ac.stfc.isis.ibex.opis/resources/he3nmr/nmrscreen.opi
base/uk.ac.stfc.isis.ibex.opis/resources/lndyisw.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/pace5000.opi
base/uk.ac.stfc.isis.ibex.opis/resources/spinnaker/ADSpinnaker.opi
base/uk.ac.stfc.isis.ibex.opis/resources/sr850.opi
base/uk.ac.stfc.isis.ibex.opis/resources/stanford_sr400_photon_counter.opi
base/uk.ac.stfc.isis.ibex.opis/resources/tekdmm40X0.opi

Adds OPI support for the new environment monitor IOC and device.
- Features two boxes for each sensor, containing 2 values, temperature and relative humidity.
- If a sensor is not connected as per IOC macros then its box is not displayed.
- If neither sensor is connected then an error is displayed telling the user how to add sensors via IOC macros.
- If a sensor is said to be connected in the IOC macros but is not physically connected then this will raise an error for each PV not connected.
[Ticket8130](https://github.com/ISISComputingGroup/IBEX/issues/8130)
- Is the information from the device displayed clearly
- Does the new IOC appear within the IBEX client config menu / synoptic menu
One sensor connected
Both sensors connected but sensor B not physically connected
Neither sensor …

Ticket8130 add ioc envmon

---

base/uk.ac.stfc.isis.ibex.opis/resources/tekdmm40X0.opi

bug - tekdmm40X0 hardcoded to only show first IOC

---

base/uk.ac.stfc.isis.ibex.opis/resources/chipir_xyz_table.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

add opi for chipir xyz table

---

base/uk.ac.stfc.isis.ibex.opis/resources/chipir_filter_set.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

- Adds an OPI for the CHIPIR filter set
- Contains 6 LED's and 6 Buttons
- Shutter Open / Close readback
- Shutter Moving readback
- Shutter Open button
- Shutter close button
- Filter 1 open / close readback
- Filter 1 moving readback
- Filter 1 open button
- Filter 1 close button
- "" for filter 2
[Ticket6217](https://github.com/ISISComputingGroup/IBEX/issues/6217#issue-805738735)
- All functionality is brought over from SECI implementation
- Able to write to PV's to be able to open/close shutter/filters
- Check that the PVs allocated to buttons/LEDs are correct regarding CHIPIR docs
- Difficult to fully test- so will need to patch onto instrument
---

Ticket6217 chipir opi for filter set

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

lindy i power switch - default value for OPI

---

base/uk.ac.stfc.isis.ibex.opis/resources/chipir_xyz_table.opi

fix stop all button in chipir xyz table screen

---

base/uk.ac.stfc.isis.ibex.devicescreens/src/uk/ac/stfc/isis/ibex/devicescreens/components/ComponentType.java

add litron entry in ComponentType enum

---

base/uk.ac.stfc.isis.ibex.opis/resources/group3hallprobe.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_control.opi
base/uk.ac.stfc.isis.ibex.opis/resources/hifi_magnet_table.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Created an OPI for the Hifi magnet that follows the setup of the RIKEN magnets as the scientists will likely be use to that format.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6086)

Add Hifi magnet Opi

---

build/jenkins_build.bat

Exclude arm exe from kit

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/dg645.opi
base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

See https://github.com/ISISComputingGroup/IBEX/issues/6090.
Added an OPI for the Litron Laser Timing Control. Uses the DG645 IOC. Test that all existing functionality in LabView is represented here. (See https://github.com/ISISComputingGroup/IBEX/issues/6089#issuecomment-2102423879)

Ticket6090 add ioc litron laser timing control

---

base/uk.ac.stfc.isis.ibex.opis/resources/ldens3300.opi
base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

Adds an OPI for the L-Dens 3300 density sensor.

Adds opi for L-Dens 3300 density sensor

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml

This fixes the issue coming dur to merging opis into the opi_info file.

Merge issue fixed

---

base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/magnetometer_row.opi
base/uk.ac.stfc.isis.ibex.opis/resources/zero_field_controller_hifi/zero_field_controller_hifi.opi

https://github.com/ISISComputingGroup/ibex/issues/8401
---

Add OPI for hifi zero-field system

---

base/uk.ac.stfc.isis.ibex.opis/resources/litronlasertimer.opi

- Makes the error indicator clearer
- Makes more room for numbers in the delay readbacks box
- Adds an indicator while in mode "auto" that this has not been tested yet as not yet needed

Dg645 litron timing control fixes (Merge support first)

---

base/uk.ac.stfc.isis.ibex.opis/resources/muon_overviews/muon_front_end_overview.opi

hardcode IN:MUONFE:

---

base/uk.ac.stfc.isis.ibex.dae/src/uk/ac/stfc/isis/ibex/dae/DaeObservables.java

use RUNDURATION_STR and RUNDURATION_PD_STR

---

base/uk.ac.stfc.isis.ibex.opis/resources/DG645/Graph.opi

Closes https://github.com/ISISComputingGroup/IBEX/issues/8692
The issue was that a script was being "triggered" by a PV it was also writing to... Hence it was continuously triggering itself in a tight loop.
https://github.com/ISISComputingGroup/IBEX/issues/8692
This is not reproducible on a dev machine as dev machines are fast enough.
- Open VisualVM on your dev desktop
- Link VisualVM to client running on SCIDEMO
- Into `\\ndxscidemo\c$\Instrument\Apps\Client_E4\plugins\uk.ac.stfc.isis.ibex.opis_1.0.0.1\resources\DG645` copy the current master version of `Graph.opi`
- Remote desktop to NDXSCIDEMO
- Refresh/reopen OPI on SCIDEMO
- Look in visualVM, CPU use will be ~10%
- Into `\\ndxscidemo\c$\Instrument\Apps\Client_E4\plugins\uk.ac.stfc.isis.ibex.opis_1.0.0.1\resources\DG645` copy this …

Don't use excessive CPU in DG645 OPI

---

.github/workflows/lint.yml

What happens if we enable codeQL on the gui repo?

---

base/uk.ac.stfc.isis.ibex.ui.scripting/src/uk/ac/stfc/isis/ibex/ui/scripting/Commands.java

Sets matplotlib defaults as per ticket description. 
https://github.com/ISISComputingGroup/IBEX/issues/8578
---

set matplotlib defaults (figure.autolayout, font.size)

---

base/uk.ac.stfc.isis.ibex.opis/resources/dds_tensile_stress_rig.opi

Minor changes to OPI to corectly trigger the statemachine.
[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8666)
Use the gui to run the manual testing steps mentioned in the suppor pull request.

Allow gui to properly trigger statemachine

---

base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_channel.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_event_energyspec.opi
base/uk.ac.stfc.isis.ibex.opis/resources/CAENHexagon/CAEN_hexagon_eventspec.opi

Add extra energy sepctrum
